### ISSUE TITLE
Installed Node.js doesn't work

### ISSUE THREAD

**Issue by xxks-kkk** [jdneo/vscode-leetcode#1]
I typed `node -v` and got `v6.7.0` and then in VS Code, the error message shows `Command 'leetcode.refreshExplorer' not found`.
![screen shot 2018-02-19 at 9 44 24 pm](https://user-images.githubusercontent.com/2559051/36406710-56720f1a-15be-11e8-9f77-d8b9e281f2b0.png)

**Comment by jdneo** [comment]
Hi @xxks-kkk , thank you for the feedback.

Currently the explorer do have some bugs now. But I cannot repro this one: `Command 'leetcode.refreshExplorer' not found`

Could you please provide more information about this?

like the version of vs code, repro steps, etc. 😄

**Comment by xxks-kkk** [comment]
I'm using Viisual Studio Code Version 1.20.1 (1.20.1). The steps I take roughly like:

- I install plugin directly from the VS Code. 
- Once, I installed, I was notified that Node.js was not found from `PATH`. 
- So, I installed the node.js and run `node -v` with output `v6.7.0`. 
- Then I hit the refresh button of the plugin and the error message reported shows up.

I'm using Mac OSX 10.10.5.

Hope this description helps!

**Comment by jdneo** [comment]
@xxks-kkk I see. 

Currently, the extension will check the node runtime at the startup.

If user installed Node.js, then it will register related commands, otherwise, it just give a hint and return.

Could you please try to restart the VS Code (or maybe restart your Mac) and see if this issue still occur?

**Comment by jdneo** [comment]
Hi @xxks-kkk Does the problem still occurs?

**Comment by jdneo** [comment]
@xxks-kkk please feel free to reopen this issue if it still blocks you.

**Comment by leeguooooo** [comment]
我也遇到了这个问题， 我尝试把插件卸载重装，之后就好了！

**Comment by progerchai** [comment]
Try to upgrade vscode version, and I solved it.
