### ISSUE TITLE
[ERROR] Error: socket hang up

### ISSUE THREAD

**Issue by zhongyuchen** [jdneo/vscode-leetcode#101]
点击提交代码后，一直在等，最后也没提交上去，显示这个错误
- Sending code to judge
[ERROR] Error: socket hang up

**Comment by ddzy** [comment]
> 点击提交代码后，一直在等，最后也没提交上去，显示这个错误
> 
> * Sending code to judge
>   [ERROR] Error: socket hang up

应该是vscode的网络问题, 我的根本没法登录

**Comment by jdneo** [comment]
@zhongyuchen @ddzy 好像之前也有用户遇到类似的情况，试试看切换一下endpoint看看？

具体的操作步骤在这里：https://github.com/jdneo/vscode-leetcode/blob/master/docs/README_zh-CN.md#%E5%88%87%E6%8D%A2-leetcode-%E7%89%88%E6%9C%AC

**Comment by ddzy** [comment]
> @zhongyuchen @ddzy 好像之前也有用户遇到类似的情况，试试看切换一下endpoint看看？
> 
> 具体的操作步骤在这里：https://github.com/jdneo/vscode-leetcode/blob/master/docs/README_zh-CN.md#%E5%88%87%E6%8D%A2-leetcode-%E7%89%88%E6%9C%AC

thks, 已解决, 切换到中文版就行了

**Comment by zhongyuchen** [comment]
我登陆的是中文版账号，但是重启又可以用了.
emmmm

**Comment by Leslie-Wong-H** [comment]
同样出现了这样的问题，英文版账户

**Comment by Leslie-Wong-H** [comment]
重启是可以用但是不久后又会出现同样问题——

**Comment by Leslie-Wong-H** [comment]
而且这问题是我将英文版账户同步到中文版账户后才出现的，是不是中文版人气太弱？隐性地采取一些措施让用户使用中文版的endpoint？？？

**Comment by jdneo** [comment]
@Leslie-Wong-H Are you sure your network environment is fine?

**Comment by Leslie-Wong-H** [comment]
Probably, I am using College WiFi right now.  Maybe Switch to another network it will be fine. But the leetcode website always works good, making me doubt the network problem of vscode.

**Comment by Leslie-Wong-H** [comment]
账号登录状态那里应该改进一下，有时候wifi掉线了，提交代码的时候就timeout了，所以一直知道自己的账号是在线还是离线的话还是挺好的。那个sigh in图标一直在那里一成不变的，有时候真不知道自己有没有登录成功，有再次输入账号密码登录一次的强迫症——

**Comment by zwkcoding** [comment]
same problem...
