### ISSUE TITLE
Add PHP support

### ISSUE THREAD

**Issue by sohaha** [jdneo/vscode-leetcode#103]
目前 leetcode 是支持 php 的了，能否考虑加上？
（不加其实也没事，估计也没 写 php 的会用吧🙅‍♂️，逃）

**Comment by poppinlp** [comment]
@sohaha Hi
This feature depends on the leetcode-cli package.
I've sent a [PR](https://github.com/skygragon/leetcode-cli/pull/163) for PHP supporting and we'll support it after they merge and release. :)

**Comment by jdneo** [comment]
Considering the leetcode-cli is inactive for a long time. I'm thinking to fork and publish a temporary bit for it. Because currently there are too many issues blocked.

**Comment by poppinlp** [comment]
@jdneo And maybe we should export a JS module instead of the CLI for easy using and performance reason.

**Comment by jdneo** [comment]
@poppinlp That's exactly what I'm thinking.

But exporting a JS module might cost much more time, so in the short term, publishing a forked cli bit could be a workaround. For the long term, we need a library instead of depending on the cli.

**Comment by poppinlp** [comment]
@jdneo Agree. 👍

And if you like, maybe we could create a github org to contains the JS module, the CLI based on JS module, and extensions.
And i just find out that the owner of [leetcode package name](https://www.npmjs.com/package/leetcode) is a friend of me and it's long term inactive. So maybe we could use that package name. :)

**Comment by jdneo** [comment]
@poppinlp Ok, let me think more about it and I'll let you know the update when I have more thoughts on this. Thank you for your passion.

**Comment by jdneo** [comment]
Resolved in #179.
