### ISSUE TITLE
When try "Test in LeetCode" using customized test case, judge failed due to wrong data contract.

### ISSUE THREAD

**Issue by dumplingslove** [jdneo/vscode-leetcode#104]
Input data:
'12'

Actual
  √ runtime: 84 ms
  × answer: 2
  √ stdout: ''

Expected
  × Runtime Error
  × runtime: N/A
  × answer: 
  × stdout: ''
  × error: Line 36: ValueError: No JSON object could be decoded
  × error: ValueError: No JSON object could be decoded
    raise ValueError("No JSON object could be decoded")
Line 382 in raw_decode (/usr/lib/python2.7/json/decoder.py)
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
Line 364 in decode (/usr/lib/python2.7/json/decoder.py)
    return _default_decoder.decode(s)
Line 339 in loads (/usr/lib/python2.7/json/__init__.py)
Line 24 in to_string (/leetcode/python/__deserializer__.py)
Line 36 in _driver (Solution.py)
Line 49 in  (Solution.py)

**Comment by jdneo** [comment]
@dumplingslove What's the number of the problem?

**Comment by dumplingslove** [comment]
@jdneo Thanks for your reply! You can try question #91, i believe all string test case will get this error. I tried "12", '12' and '"12"', none of them can work.

**Comment by jdneo** [comment]
Dup with #60
