### ISSUE TITLE
Cannot retrieve time and memory result

### ISSUE THREAD

**Issue by dumplingslove** [jdneo/vscode-leetcode#105]
√ Accepted
  √ 258/258 cases passed (88 ms)
[WARN] Failed to get submission beat ratio.

**Comment by jdneo** [comment]
@dumplingslove What's the endpoint are you using? `leetcode` or `leetcode-cn`? Do you still have the issue on your side?

**Comment by jdneo** [comment]
Related issue: https://github.com/skygragon/leetcode-cli/issues/156

**Comment by dumplingslove** [comment]
Thanks for the checking.

**Comment by BrambleXu** [comment]
I have the same issue. Hope to see the new version to fix it.

**Comment by zfrxiaxia** [comment]
same problem, leetcode-cn

**Comment by jdneo** [comment]
Resolved in #179.
