### ISSUE TITLE
[ERROR] http error [code=404]

### ISSUE THREAD

**Issue by chinazhaghai** [jdneo/vscode-leetcode#106]
1. 题号： 简单001
2. 国内账号
3. 已清除缓存，提交依旧404

**Comment by EdXsuperhero** [comment]
met the same prob as well.

**Comment by EdXsuperhero** [comment]
rather than the 001, other problems can not be sanded to judge as well.

**Comment by jdneo** [comment]
@chinazhaghai @EdXsuperhero 

Please try to [switch the endpoint](https://github.com/jdneo/vscode-leetcode#switch-endpoint) to make sure you are using the right one.

The accounts of the global and Chinese version of LeetCode are not shared.

**Comment by MingNeo** [comment]
遇到了同样的问题。切换到国际版和中国版都有这个问题。

**Comment by neil4dong** [comment]
I met the same problem. It probably not wrong user configuring owing to the successful login, the 404 only occurred when submit answer or test answer.

@jdneo

**Comment by jdneo** [comment]
Hi all,

Could you please try the following steps:

1. Removing the cache: `$HOME/.lc`? 
2. Regenerate a new problem file
3. Test/Submit it.

**Comment by hiyjeain** [comment]
I met the same problem. 
I solved this problem by verifying my email of leetcode.com or leetcode-cn.com account. Because user cannot submit code until have the email or phone verified.

在leetcode.com 或者 leetcode-cn.com站上验证手机号或者邮箱可解决，因为没验证激活的账号不能提交代码

**Comment by jdneo** [comment]
@hiyjeain Thank you for providing the solution both in English and Chinese.

For anyone who encountered the same problem, please try the above solution and let us know if this solved your problem.

**Comment by timqian** [comment]
This should be in the readme

**Comment by jdneo** [comment]
@timqian It's already there: https://github.com/jdneo/vscode-leetcode#troubleshooting

**Comment by timqian** [comment]
@jdneo Thanks, did not see that 😅

**Comment by jdneo** [comment]
@timqian np~

**Comment by ziyi-yan** [comment]
> I met the same problem.
> I solved this problem by verifying my email of leetcode.com or leetcode-cn.com account. Because user cannot submit code until have the email or phone verified.
> 
> 在leetcode.com 或者 leetcode-cn.com站上验证手机号或者邮箱可解决，因为没验证激活的账号不能提交代码

Thanks! It just solved my problem.
