### ISSUE TITLE
command 'leetcode.signin' not found

### ISSUE THREAD

**Issue by Allen-Zfu** [jdneo/vscode-leetcode#108]
Hi,
Sometimes, I always got this error. command 'leetcode.signin' not found
I am connecting with US leetcode.

Thanks,

**Comment by jdneo** [comment]
@Allen-Zfu Make sure the following requirements are satisfied:
1. VS Code version > 1.23.0
2. Node.js version > 8.
  > You can check by `node -v`

**Comment by Allen-Zfu** [comment]
@jdneo , Thank you for the help. I need to upgrade Node.
Thanks,

**Comment by hanyahui88** [comment]
mac

node :v11.12.0
vs code:1.32.3 (1.32.3)

command 'leetcode.signin' not found
command 'leetcode.toggleLeetCodeCn' not found

**Comment by sepetboy** [comment]
vxcode Version: 1.32.3
Chrome: 66.0.3359.181
Node.js: 10.2.0
OS: Windows_NT x64 10.0.17134

Tip：There is no data provider registered that can provide view data.
What is the reason for this?
