### ISSUE TITLE
proxy issue: log in time out

### ISSUE THREAD

**Issue by shaoxul** [jdneo/vscode-leetcode#117]
Dear friends,

For the sake of the gateway firewall, the http proxy must be used to connect internet.
But the log-in always times out. It looks like to try to connect to the leetcode server directly instead of through the proxy.

Is there any configuration I missed?

**Comment by jdneo** [comment]
@shaoxul Hmm, I have not met this problem before. But just found that the VS Code has proxy related settings. Maybe you can have a try?

![image](https://user-images.githubusercontent.com/6193897/52612638-a39e3400-2ec5-11e9-84d0-18e9b0a41036.png)

**Comment by shaoxul** [comment]
@jdneo Thank you for your reply. Yes, I tried, but it works for the VS code itself(e.g. extension market), but not works for this this extension.

**Comment by jdneo** [comment]
So far, I have no idea what I can do for your problem...

Need some more investigation here...

**Comment by MiloJason** [comment]
@shaoxul I have met the same problem as you.

**Comment by zfrxiaxia** [comment]
same problem

**Comment by edvardchen** [comment]
@shaoxul  It seems that vscode's proxy setting does't work. Try to start vscode with command line arguments

```
code --proxy-server=yourproxy
``` 

or setting the global env variables before run code. [See more in official document ](https://code.visualstudio.com/docs/setup/network)

**Comment by jdneo** [comment]
@edvardchen Provided a solution in #147.

The root cause is that when we trigger a leetcode-cli command, we will spawn a new child_process to send the request, which may bypass the proxy setting in VS Code.

So, we need to read the proxy setting of VS Code. and set it in the created child_process.

More details can be found in #147
