### ISSUE TITLE
Please redirect the debug info to the terminal in VS code

### ISSUE THREAD

**Issue by duxingzhe** [jdneo/vscode-leetcode#118]
It will be more formal to output the information of debug to the terminal. I think it will be content with the normal behavior of our programmer.

**Comment by jdneo** [comment]
Hi @duxingzhe, 
Could you explain more about `information of debug`? What is that for?

**Comment by duxingzhe** [comment]
The result of Leetcode. Error, AC, etc.

**Comment by jdneo** [comment]
Hmm, so I'm guessing that you do not like to switch between the `Output` panel and the `Terminal` panel?

Unfortunately, the reason why the results are all going to the `Output` panel is that:

- It's a common practice for VS Code extension to print is own information into its own output channel. You could verify this in most of the popular extensions.
- A more important reason is that currently there is no API to get the output from the terminal. So it's (at least as far as I know) impossible to implement what you request. 

Base on that, I'm closing this issue for now. But the discussion is still open. For people who have some ideas about this issue, please feel free to comment.

Thanks.
