### ISSUE TITLE
Customize the sub-directory to save the file generated by 'Show Problem'

### ISSUE THREAD

**Issue by liuyangc3** [jdneo/vscode-leetcode#119]
例如把生成文件的目录设置为, 当前打开文件夹下的 任意某个文件夹

**Comment by jdneo** [comment]
Is #120 what you are asking for?

**Comment by liuyangc3** [comment]
@jdneo not quite same,for example is it possiable generate `.java` file in `somedir`

![image](https://user-images.githubusercontent.com/6705844/52688563-f8a77c00-2f91-11e9-934e-7bc00602b2bf.png)

**Comment by ringcrl** [comment]
Maybe should add a vscode config like：

"leetcode.outputPath": "tag", // somedir Or other

**Comment by jdneo** [comment]
@ringcrl I'm thinking exactly the same thing.

We need to figure out if it is possible to combine this issue with #120 and give out an overall solution.

**Comment by ringcrl** [comment]
| Setting Name | Description | Default Value |
|---|---|---|
| `leetcode.outputPath` | Which path will the problem generate to. `root` for  root directory，`tag` for create a directory based on the tag of the problem，`custom_path` for User-defined directory  | `root` |

**Comment by jdneo** [comment]
@ringcrl LGTM, just some small improvement.

The `leetcode.outputPath` specifies the relative path to save the problem files. Meanwhile, we have several preserved values for it, which will be resolved according to the actual situation. Those preserved values are:
- `${tag}` - a directory based on the problem's tag. For example, if the problem belongs to: `Binary Indexed Tree`, then a folder named `binary_indexed_tree` will be used here.
- `${language}` - a directory based on the language used. For example, `java` for Java language
- `${difficulty}` - a directory based on the problem's difficulty. For example, `easy`
> If this setting is not set, the files will be generated to `root`

**Comment by ringcrl** [comment]
OK~I will finish it later

**Comment by jdneo** [comment]
@ringcrl Great! Thank you.

**Comment by jdneo** [comment]
@all The PR has been merged and will be released in 0.11.0.

Thank you all for your participation.

**Comment by wangjunwei87** [comment]
I really need this feature, when will version 0.11.0 release?

**Comment by jdneo** [comment]
@wangjunwei87 It should be released recently

**Comment by jdneo** [comment]
@wangjunwei87 0.11.0 has been released

**Comment by wangjunwei87** [comment]
@jdneo Thanks for your great work, and I am wondering if it's possible to use preserved value for interpolation, like "something-${tag}-${language}-something".

**Comment by jdneo** [comment]
@wangjunwei87 great idea. Would you mind to create an issue for that？

**Comment by wangjunwei87** [comment]
Sure, my pleasure.
