### ISSUE TITLE
Show Problem With Tag

### ISSUE THREAD

**Issue by ringcrl** [jdneo/vscode-leetcode#120]
I wanna to generate a Problem and auto put it to a classified folder by tag suck like：

![image](https://user-images.githubusercontent.com/16740021/52641597-2b129400-2f14-11e9-9ce2-c8a39300f138.png)

![image](https://user-images.githubusercontent.com/16740021/52641615-3796ec80-2f14-11e9-879a-fdf03f883360.png)

I have implemented this requirement through this commit：https://github.com/ringcrl/vscode-leetcode/commit/b8b91a6a0d8fa1c8a1cbbfc2bdc66573f562c1c7

I Hope to get some advice...😁

**Comment by jdneo** [comment]
@ringcrl Let's track & discuss in #119
