### ISSUE TITLE
why vscode-leetcode plugin not show in ative bar?

### ISSUE THREAD

**Issue by huguoliang1314** [jdneo/vscode-leetcode#122]
see picture:
![image](https://user-images.githubusercontent.com/13847571/52680472-74de9700-2f73-11e9-9bef-cdbabd32c065.png)
node version:  v8.11.1
vscode version:  1.22.2
expect result:   the icon of vscode-leetcode show in active bar, example:
![image](https://user-images.githubusercontent.com/13847571/52680623-14038e80-2f74-11e9-85af-a1732ee46c3e.png)

**Comment by huguoliang1314** [comment]
i hope get some advices， @jdneo

**Comment by jdneo** [comment]
@huguoliang1314 VS Code version needs to be higher than 1.23.0
