### ISSUE TITLE
Wrong search result match

### ISSUE THREAD

**Issue by taoweicn** [jdneo/vscode-leetcode#128]
<img width="598" alt="wx20190217-100701 2x" src="https://user-images.githubusercontent.com/25795549/52907389-cc467500-329b-11e9-8610-f09a125dcc4c.png">
I think the AC rate should not be matched.

**Comment by jdneo** [comment]
@taoweicn 
One solution is to move `AC Rate` from the `details` to `description`. As below:

<img width="721" alt="screen shot 2019-02-20 at 8 17 41 pm" src="https://user-images.githubusercontent.com/6193897/53091425-e3f85480-354c-11e9-8ebd-30fecd9c81cf.png">

But I still prefer the original UI layout.

**Comment by jdneo** [comment]
Hey @taoweicn ,

I'm sorry that I'll close this issue since we do not get feedback from other users about the UI and it's currently a limitation about the VS Code API.

But still, thank you for your engagement.
