### ISSUE TITLE
Signed out after switching endpoint, even if it's the same endpoint.

### ISSUE THREAD

**Issue by kevjin** [jdneo/vscode-leetcode#129]
**What happens**
If I am initially signed into leetcode.com (US Endpoint) and I decide to click "Switch Endpoint" and I choose the US Endpoint, the app will sign me out of my leetcode account anyway.

**What should happen**
If I am already signed into an endpoint and I choose the _same_ endpoint again from the Switch Endpoint button, either A. nothing should happen, or B. a notification that says "You are already signed in. Use the Sign Out command to sign out" appears. 

This is a very small issue pertaining to UX. It's not something a user would expect would happen and it doesn't make much sense for users to sign out by relying on the switch endpoint button. It would be nice to have this fixed, and I can make a PR for it as well. Thanks!

**Comment by jdneo** [comment]
@kevjin Thank you for reporting this issue. It will be great if you would like to send out a PR for this. Give it a shoot!
