### ISSUE TITLE
安装之后，无法找到打开的方式

### ISSUE THREAD

**Issue by stevenlii** [jdneo/vscode-leetcode#133]
安装之后，使用LeetCode: Sign in，无任何反应或显示未找到结果。。
![image](https://user-images.githubusercontent.com/8954758/52928401-75639d00-337a-11e9-8777-352ce84b54a8.png)
上图中的示例页面，到底是怎么打开的？？？

**Comment by jdneo** [comment]
Are all the requirements satisfied on hour side?https://github.com/jdneo/vscode-leetcode/blob/master/docs/README_zh-CN.md#%E8%BF%90%E8%A1%8C%E6%9D%A1%E4%BB%B6

**Comment by jdneo** [comment]
@stevenlii As the document shows. Please make sure your VS Code version is higher than `1.23` and Node.js higher than `8`

**Comment by jdneo** [comment]
There is also a troubleshooting page that you may want to take a look.

https://github.com/jdneo/vscode-leetcode/wiki/Troubleshooting

**Comment by lijinxi1314** [comment]
what is the password for the sign in?

**Comment by jdneo** [comment]
@stevenlii Did your problem been solved?

**Comment by jdneo** [comment]
Closed for inactive.
