### ISSUE TITLE
mac login error

### ISSUE THREAD

**Issue by relengxing** [jdneo/vscode-leetcode#136]
login: pass: - Signing in leetcode.com
[ERROR] Error: tunneling socket could not be established, cause=connect EHOSTUNREACH 0.0.4.63:80 - Local (10.0.0.11:59146)

**Comment by jdneo** [comment]
@relengxing Is this issue stably repro?

**Comment by relengxing** [comment]
我的是稳定登陆不了，我觉得可能是代理问题，我用了shadow socks,但是我关掉也没用
I think is stably. It may proxy problem, I was use shadow socks, but it still can login when I close SS


On Feb 20, 2019, at 10:11, Sheng Chen <notifications@github.com<mailto:notifications@github.com>> wrote:


@relengxing<https://github.com/relengxing> Is this issue stably repro?

**Comment by jdneo** [comment]
@relengxing What if you switch to a new network environment?

**Comment by relengxing** [comment]
relengxing@relengxingdeMacBook-Pro  ~  curl cip.cc<http://cip.cc>
IP      : 113.118.186.11
地址    : 中国  广东  深圳
运营商  : 电信

数据二  : 广东省深圳市 | 电信

数据三  : 中国广东省深圳市 | 电信

I have closed my SS, but still can’t login

v11.10.0
Active Name Version Desc
----------------------------------------------------------------------------------------------------
✔ company 2017.12.18 Plugin to query by company for free user.
✔ cache default Plugin to provide local cache.
✔ retry default Plugin to retry last failed request if autologin.enable is on.
✔ leetcode.cn<http://leetcode.cn> 2018.11.25 Plugin to talk with leetcode-cn APIs.
✔ leetcode default Plugin to talk with leetcode APIs.
Active Name Version Desc
----------------------------------------------------------------------------------------------------
✔ company 2017.12.18 Plugin to query by company for free user.
✔ cache default Plugin to provide local cache.
✔ retry default Plugin to retry last failed request if autologin.enable is on.
✔ leetcode.cn<http://leetcode.cn> 2018.11.25 Plugin to talk with leetcode-cn APIs.
✔ leetcode default Plugin to talk with leetcode APIs.
[ERROR] You are not login yet?
Active Name Version Desc
----------------------------------------------------------------------------------------------------
✔ company 2017.12.18 Plugin to query by company for free user.
✔ cache default Plugin to provide local cache.
✔ retry default Plugin to retry last failed request if autologin.enable is on.
✘ leetcode.cn<http://leetcode.cn> 2018.11.25 Plugin to talk with leetcode-cn APIs.
✔ leetcode default Plugin to talk with leetcode APIs.
[ERROR] You are not login yet?
login: pass: - Signing in leetcode.com<http://leetcode.com>
[ERROR] Error: tunneling socket could not be established, cause=connect EHOSTUNREACH 0.0.4.63:80 - Local (10.0.0.11:59146)
login: pass: - Signing in leetcode.com<http://leetcode.com>
[ERROR] Error: tunneling socket could not be established, cause=connect EHOSTUNREACH 0.0.4.63:80 - Local (10.0.0.11:53373)

On Feb 20, 2019, at 10:17, Sheng Chen <notifications@github.com<mailto:notifications@github.com>> wrote:


@relengxing<https://github.com/relengxing> What if you switch to a new network environment?

**Comment by jdneo** [comment]
Hmm, I have no idea about this issue for now. If anyone has the solution, please let us know. Thanks!

**Comment by sunb0002** [comment]
Me too. 
Is there a configuration to disable the tunnelling?

[ERROR] You are not login yet?
login: login: login: pass: login: login: pass: - Signing in leetcode.com
[ERROR] Error: tunneling socket could not be established, cause=connect EHOSTUNREACH 0.0.31.144:80 - Local (10.213.103.196:56318)
login:
