### ISSUE TITLE
connect ETIMEDOUT & Failed to get submission beat ratio

### ISSUE THREAD

**Issue by McKenzieIT** [jdneo/vscode-leetcode#137]
第一次使用出现几个问题
登录节点为leetcode.com
1:登录时出现 
login: pass: - Signing in leetcode.com
- Retrieving user favorites
[WARN] Failed to retrieve user favorites: Error: Client network socket disconnected before secure TLS connection was established
- Retrieving user profile
Successfully login as xxxxx
2.提交时有时会提交不了
- Sending code to judge
- Waiting for judge result
[ERROR] Error: connect ETIMEDOUT 104.18.51.23:443
3.提交成功也会出现问题
- Sending code to judge
- Waiting for judge result
  ✔ Accepted
  ✔ 29/29 cases passed (36 ms)
[WARN] Failed to get submission beat ratio.

希望大佬们方便能解决我的问题

**Comment by jdneo** [comment]
Thank you for reporting.

Looks like 1&2 are network issue.

3 is tracked by #105

**Comment by McKenzieIT** [comment]
I can't find the submit.js and leetcode.js in my mac. Where can I find it?@jdneo

**Comment by jdneo** [comment]
@McKenzieIT Are you looking for the module in the `leetcode-cli`? If yes, you can find them in the `node_modules` of the extension.

**Comment by McKenzieIT** [comment]
Thanks for your help! It seems like if I change the two files, all the three issues could be fixed!

**Comment by jdneo** [comment]
@McKenzieIT Woo!

Could you share the changes you made to make it work? Maybe it can also help others.

**Comment by superhen** [comment]
Mckenzie，
Can you share the change please. I have the same issue




| |
Henry
邮箱：surudo_tyou@163.com
|

Signature is customized by Netease Mail Master

On 02/19/2019 12:25, Sheng Chen wrote:

@McKenzieIT Woo!

Could you share the changes you made to make it work? Maybe it can also help others.

**Comment by McKenzieIT** [comment]
> Mckenzie， Can you share the change please. I have the same issue | | Henry 邮箱：surudo_tyou@163.com | Signature is customized by Netease Mail Master On 02/19/2019 12:25, Sheng Chen wrote: @McKenzieIT Woo! Could you share the changes you made to make it work? Maybe it can also help others. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

You want me to email you ?

**Comment by superhen** [comment]
Yes, thank you so much




| |
Henry
邮箱：surudo_tyou@163.com
|

Signature is customized by Netease Mail Master

On 02/19/2019 12:31, McKenzie wrote:

Mckenzie， Can you share the change please. I have the same issue | | Henry 邮箱：surudo_tyou@163.com | Signature is customized by Netease Mail Master On 02/19/2019 12:25, Sheng Chen wrote: @McKenzieIT Woo! Could you share the changes you made to make it work? Maybe it can also help others. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

You want me to email you ?

**Comment by McKenzieIT** [comment]
Firstly, find out the folder of your vs-code, for me, a mac user, it's location is ~/.vscode. Then, you get into the extensions/shengchen.vscode-leetcode-x.x.x/node_modules/leetcode-cli/lib/. After that, change two files, 
one is the leetcode.js in /plugins, on line 339, need to update
`re = body.match(/distribution_formatted:\s('[^']+')/);`
to
`re = body.match(/runtimeDistributionFormatted:\s('[^']+')/);`,
the other is the submit.js in /command, on line 79, change
` if (parseFloat(score[0]) > myRuntime)`
to
`if (parseFloat(score[0]) >= myRuntime)`
Last, save the files and restart the vscode, then see what would happen.(My English is very bad...)

**Comment by superhen** [comment]
Thank you for your help




| |
Henry
邮箱：surudo_tyou@163.com
|

Signature is customized by Netease Mail Master

On 02/19/2019 12:43, McKenzie wrote:

Firstly, find out the folder of your vs-code, for me, a mac user, it's location is ~/.vscode. Then, you get into the extensions/shengchen.vscode-leetcode-x.x.x/node_modules/leetcode-cli/lib/. After that, change two files,
one is the leetcode.js in /plugins, on line 339, need to update
re = body.match(/distribution_formatted:\s('[^']+')/);
to
re = body.match(/runtimeDistributionFormatted:\s('[^']+')/);,
the other is the submit.js in /command, on line 79, change
if (parseFloat(score[0]) > myRuntime)
to
if (parseFloat(score[0]) >= myRuntime)
Last, save the files and restart the vscode, then see what would happen.(My English is very bad...)

**Comment by jdneo** [comment]
@McKenzieIT So this is to fix the No.3 problem right?

**Comment by McKenzieIT** [comment]
Yes! And the others are not happen now.
