### ISSUE TITLE
 Some suggestion and bugs feedback

### ISSUE THREAD

**Issue by jessewkun** [jdneo/vscode-leetcode#139]
Bugs:
1. When I entering the username just after installed the extension, the password box cannot be popped up. After restarting the vscode, it's worked.
2. The checkmark could not be display After the code commit success. After restarting the vscode, it's worked.
3. I could not see the previous commit code after restarting vscode. . .
4. The login information could not be saved. I have to login in again when I restarted the vscode.

Suggestion:
1. The latest version of vscode's left directory tree can filter specific files. It would be nice if the extension support similar features.
2. If it possible to put the "Test in LeetCode" command in the editor, just like "submit to LeetCode"

**Comment by jdneo** [comment]
@jessewkun Could you please create separate issues? The combined issue is very hard for tracking.

To answer your questions:

> 1. When I entering the username just after installed the extension, the password box cannot be popped up. After restarting the vscode, it's worked.

Suggest to create a new issue

> 2. The checkmark could not be display After the code commit success. After restarting the vscode, it's worked.

Tracking by #91

> 3. I could not see the previous commit code after restarting vscode.

See: https://github.com/jdneo/vscode-leetcode#pick-a-problem Check if the files are in `$HOME/.leetcode/`

> 4. The login information could not be saved. I have to login in again when I restarted the vscode.

If you sign into the LeetCode in browser, your local session will be invalid. This is a limitaion from LeetCode

> 1. The latest version of vscode's left directory tree can filter specific files. It would be nice if the extension support similar features.

Create issue

> 2. If it possible to put the "Test in LeetCode" command in the editor, just like "submit to LeetCode"

Create issue

**Comment by jdneo** [comment]
Hi @jessewkun,

Thank you for your feedback.

I've gone through all of them, and some of them having tracking issues, some of them have solution/answer and I've added my comment below.

Some of them need more information.

Considering tracking multiple problems in one issue is difficult and is not recommended, I will close this issue for now. If you have more comments, feel free to let me know, or you can create new issues for them.

Thanks
