### ISSUE TITLE
A suggestion for 'Show Problem'

### ISSUE THREAD

**Issue by McKenzieIT** [jdneo/vscode-leetcode#141]
When I click to show the problems, the plugin always create a new file. For example, the question[1]Two Sum, when I showed the problem firstly, it created a new file named two-sum.py. After that, I showed the problem again, it created a new file two-sum.0.py rather than opening the two-sum.py. In my opinion, the plugin open the file which has been created is more reasonable.

**Comment by jdneo** [comment]
Hi @McKenzieIT 

Thank you for your suggestions. It looks like this is what #59 is talking about. (Sorry that we discussed in Chinese in #59). Let's track this one in #59.

Closing this one for now. Please feel free to let me know if you have any other problems.

Thanks.
