### ISSUE TITLE
用java写算法时代码写完后测试，提示NoSuchMethodError

### ISSUE THREAD

**Issue by exceting** [jdneo/vscode-leetcode#142]
比较奇怪的问题，我在网站的调试器里是可以正常运行的：
![qq 20190219234217](https://user-images.githubusercontent.com/11971245/53027878-ba81ef00-34a0-11e9-9756-47eabecff6ad.jpg)
但是到了vscode里，启用test却ba报了这个错误：
![qq 20190219234419](https://user-images.githubusercontent.com/11971245/53027906-c5d51a80-34a0-11e9-8f36-59fc10eef733.jpg)
请问是哪里写的有问题吗？还是触发了leetcode的bug？

**Comment by jdneo** [comment]
@exceting Would you mind to share your source code?

**Comment by exceting** [comment]
This is my code：
```java
class Solution {
    public ListNode addTwoNumbers(ListNode l1, ListNode l2) {
        int a = 0;
        int b = 0;

        int i = 1;
        while (l1 != null) {
            a += l1.val * i;
            l1 = l1.next;
            i *= 10;
        }

        int j = 1;
        while (l2 != null) {
            b += l2.val * j;
            l2 = l2.next;
            j *= 10;
        }

        int c = a + b;

        char[] cArr = String.valueOf(c).toCharArray();
        ListNode result = new ListNode(Integer.parseInt(cArr[cArr.length - 1] + ""));

        ListNode holder = result;
        int r = cArr.length - 2;
        while (r >= 0) {
            holder = holder.add(Integer.parseInt(cArr[r] + ""));
            r--;
        }

        return result;
    }
}

class ListNode {
    int val;
    ListNode next;

    ListNode(int x) {
        val = x;
    }

    public ListNode add(int val) {
        next = new ListNode(val);
        return next;
    }
}
```

**Comment by exceting** [comment]
The first problem of medium difficulty

**Comment by jdneo** [comment]
@exceting I get the same error in LeetCode using your code.

<img width="707" alt="Screen Shot 2019-03-15 at 7 49 52 PM" src="https://user-images.githubusercontent.com/6193897/54429440-875b1480-475b-11e9-908f-0963a9de2e87.png">

**Comment by jdneo** [comment]
Closing for inactive for a long time. @exceting please feel free to let us know if you still meet the problem.

Thanks.
