### ISSUE TITLE
Don't mask as completed problem on left-screen when submit passed all test-case from LeetCode

### ISSUE THREAD

**Issue by hiepndd** [jdneo/vscode-leetcode#145]
**What happens**
Suppose I have passed all test-cases from a problem on LeetCode, it doesn't mark as completed this problem on left-screen

**What should happen**
When I completed a problem on LeetCode, it should be marked as completed this problem on left-screen
This is a very small issue to UI-UX. It would be nice to have this fixed, and I can make a PR for it as well. Thanks!

**Comment by jdneo** [comment]
@hiepndd We have a tracking issue for that: #91 

To easy track the issues. I'm closing this one. Please feel free to discuss in #91 if you want. 

Yes PR are welcome, very looking forword to it! 👍
