### ISSUE TITLE
could provide an option to hide the `Submit to LeetCode` button in the editor?

### ISSUE THREAD

**Issue by AEPKILL** [jdneo/vscode-leetcode#146]
I always accidentally click it when editing the file

**Comment by taoweicn** [comment]
+1
And I think it's better to replace `Submit` with `Test`.

**Comment by poppinlp** [comment]
Agree with it. And a switch in settings too. :)

**Comment by Eskibear** [comment]
My suggestion is to 1) simply add a switch for the code lens, 2) keep both "Submit" and "Test" if  codelens is turned on. 

The config is: 
```json
"leetcode.showShortcuts": {
    "type": "boolean",
    "default": true
}
```

It looks like:
```
...
piece of code
...

Submit | Test
```
