### ISSUE TITLE
Faild to get submission beat  ratio

### ISSUE THREAD

**Issue by ddzy** [jdneo/vscode-leetcode#152]

**Comment by ddzy** [comment]
## Issue Type 
bug
## Current Feature
提交之后, 无法正常显示已击败百分比.
![issue_1](https://user-images.githubusercontent.com/33921398/53315571-e406a480-38fe-11e9-8fa3-2ed45ad4a71d.png)
## Expected Feature
`0.11.0`之前的版本都可以正常显示

**Comment by jdneo** [comment]
This is tracked by #105

It's a leetcode-cli issue, we are waiting for it get released.
