### ISSUE TITLE
when the desciption exist exponential,In Vscode it show integer and wrong

### ISSUE THREAD

**Issue by halu886** [jdneo/vscode-leetcode#153]
I am try a algorithms of leetcode in vscode.  
[**reverse-integer**](https://leetcode-cn.com/problems/reverse-integer/description/)  
id=7 lang=javascript  

the description in **VsCode** show:  

    [−231,  231 − 1]

![1](https://user-images.githubusercontent.com/22374024/53379464-92b0f080-39a4-11e9-807c-e75a4abae080.png)

the desciption in **WEB** show:  

    [−2^31,  2^31 − 1]
  
![image](https://user-images.githubusercontent.com/22374024/53379523-d4419b80-39a4-11e9-9612-d67d31a1b5fa.png)

**Comment by jdneo** [comment]
@halu886 Thank you for reporting.

This issue is dup with #74
