### ISSUE TITLE
login error

### ISSUE THREAD

**Issue by m9zjl** [jdneo/vscode-leetcode#154]
login: pass: - Signing in leetcode.com
- Retrieving user favorites
[WARN] Favorite not found?
- Retrieving user profile
Successfully login as Another

logs are as show , when it

**Comment by jdneo** [comment]
@m9zjl could you provide more information about the problem you are meeting with?

**Comment by zhoushengdong** [comment]
Failed to sign in. Please open the output channel for details.

**Comment by zhoushengdong** [comment]
> @ m9zjl你可以提供有关你遇到的问题的更多信息吗？看起来内容是切片的。

----------------------------------------------------------------------------------------------------
   √     company            2017.12.18      Plugin to query by company for free user.
   √     cache              default         Plugin to provide local cache.
   √     retry              default         Plugin to retry last failed request if autologin.enable is on.
   √     leetcode.cn        2018.11.25      Plugin to talk with leetcode-cn APIs.
   √     leetcode           default         Plugin to talk with leetcode APIs.
[ERROR] You are not login yet?
login: pass: - Signing in leetcode.com
[ERROR] Error: connect ETIMEDOUT 47.99.228.218:443

**Comment by jdneo** [comment]
@zhoushengdong What if you switch to another network environment? Or are you behind the proxy?

**Comment by ttskym** [comment]
> @zhoushengdong What if you switch to another network environment? Or are you behind the proxy?

i have same error as @zhoushengdong . I'm behind the proxy and i have already set  the http_proxy, https_proxy and registry, what else do i need to do?

**Comment by jdneo** [comment]
@zhoushengdong @ttskym Have you set the proxy setting in VS Code? See: https://github.com/jdneo/vscode-leetcode/issues/117#issuecomment-462615941

**Comment by ttskym** [comment]
@jdneo thanks. i have set th proxy in vs code ,but get an new error.

> [ERROR] You are not login yet?
> login: pass: - Signing in leetcode.com
> [ERROR] Error: unable to verify the first certificate

I can not figure out the problem is  caused by the extension or my proxy!

**Comment by jdneo** [comment]
@edvardchen Any thoughts here?

**Comment by edvardchen** [comment]
I'll take a look later.

**Comment by ttskym** [comment]
@jdneo @edvardchen  i have also tried to login using leetcode-cli and got the same error.

**Comment by ruozhiertong** [comment]
> login: pass: - Signing in leetcode.com
> 
> * Retrieving user favorites
>   [WARN] Favorite not found?
> * Retrieving user profile
>   Successfully login as Another
> 
> logs are as show , when it

i have the same problem. Last line shows 'Successfully login as xxx' . When i login via chrome web it is correct.SO have any solution?

**Comment by jdneo** [comment]
@ruozhiertong So can you submit/show the problem after login in the extension?

**Comment by edvardchen** [comment]
@ttskym It seems that your user login token in local cache was invalid. 
Try `rm rm ~/.lc/leetcode/user.json ` then login again

**Comment by ttskym** [comment]
i can not find user.json in windows os. i delete the cache folder in the .lc/leetcode and it does not work.

> @ttskym It seems that your user login token in local cache was invalid.
> Try `rm rm ~/.lc/leetcode/user.json ` then login again

**Comment by eeliu** [comment]
I got the same error, can't log in !

``` 
[ERROR] You are not login yet?
login: cookie: - Retrieving user favorites
[WARN] Failed to retrieve user favorites: Error: connect ETIMEDOUT 104.18.34.28:443
- Retrieving user profile
c:\Users\eeliu\.vscode\extensions\shengchen.vscode-leetcode-0.16.1\node_modules\vsc-leetcode-cli\lib\log.js:55
      let s = args.map(x => x.toString()).join(' ');
                              ^

TypeError: Cannot read property 'toString' of undefined
    at c:\Users\eeliu\.vscode\extensions\shengchen.vscode-leetcode-0.16.1\node_modules\vsc-leetcode-cli\lib\log.js:55:31
    at Array.map (<anonymous>)
    at Object.log.<computed> [as info] (c:\Users\eeliu\.vscode\extensions\shengchen.vscode-leetcode-0.16.1\node_modules\vsc-leetcode-cli\lib\log.js:55:20)
    at c:\Users\eeliu\.vscode\extensions\shengchen.vscode-leetcode-0.16.1\node_modules\vsc-leetcode-cli\lib\commands\user.js:121:13
    at c:\Users\eeliu\.vscode\extensions\shengchen.vscode-leetcode-0.16.1\node_modules\vsc-leetcode-cli\lib\plugins\leetcode.js:529:14
    at Request._callback (c:\Users\eeliu\.vscode\extensions\shengchen.vscode-leetcode-0.16.1\node_modules\vsc-leetcode-cli\lib\plugins\leetcode.js:428:19)
    at self.callback (c:\Users\eeliu\.vscode\extensions\shengchen.vscode-leetcode-0.16.1\node_modules\request\request.js:185:22)
    at Request.emit (events.js:210:5)
    at Request.onRequestError (c:\Users\eeliu\.vscode\extensions\shengchen.vscode-leetcode-0.16.1\node_modules\request\request.js:881:8)
    at ClientRequest.emit (events.js:210:5)
login: cookie: - Retrieving user favorites
[WARN] Failed to retrieve user favorites: Error: connect ETIMEDOUT 104.18.34.28:443
- Retrieving user profile
c:\Users\eeliu\.vscode\extensions\shengchen.vscode-leetcode-0.16.1\node_modules\vsc-leetcode-cli\lib\log.js:55
      let s = args.map(x => x.toString()).join(' ');
                              ^

TypeError: Cannot read property 'toString' of undefined
    at c:\Users\eeliu\.vscode\extensions\shengchen.vscode-leetcode-0.16.1\node_modules\vsc-leetcode-cli\lib\log.js:55:31
    at Array.map (<anonymous>)
    at Object.log.<computed> [as info] (c:\Users\eeliu\.vscode\extensions\shengchen.vscode-leetcode-0.16.1\node_modules\vsc-leetcode-cli\lib\log.js:55:20)
    at c:\Users\eeliu\.vscode\extensions\shengchen.vscode-leetcode-0.16.1\node_modules\vsc-leetcode-cli\lib\commands\user.js:121:13
    at c:\Users\eeliu\.vscode\extensions\shengchen.vscode-leetcode-0.16.1\node_modules\vsc-leetcode-cli\lib\plugins\leetcode.js:529:14
    at Request._callback (c:\Users\eeliu\.vscode\extensions\shengchen.vscode-leetcode-0.16.1\node_modules\vsc-leetcode-cli\lib\plugins\leetcode.js:428:19)
    at self.callback (c:\Users\eeliu\.vscode\extensions\shengchen.vscode-leetcode-0.16.1\node_modules\request\request.js:185:22)
    at Request.emit (events.js:210:5)
    at Request.onRequestError (c:\Users\eeliu\.vscode\extensions\shengchen.vscode-leetcode-0.16.1\node_modules\request\request.js:881:8)
    at ClientRequest.emit (events.js:210:5)

**Comment by eeliu** [comment]
> I got the same error, can't log in !
> 
> ```
> [ERROR] You are not login yet?
> login: cookie: - Retrieving user favorites
> [WARN] Failed to retrieve user favorites: Error: connect ETIMEDOUT 104.18.34.28:443
> - Retrieving user profile
> c:\Users\eeliu\.vscode\extensions\shengchen.vscode-leetcode-0.16.1\node_modules\vsc-leetcode-cli\lib\log.js:55
>       let s = args.map(x => x.toString()).join(' ');
>                               ^
> 
> TypeError: Cannot read property 'toString' of undefined
>     at c:\Users\eeliu\.vscode\extensions\shengchen.vscode-leetcode-0.16.1\node_modules\vsc-leetcode-cli\lib\log.js:55:31
>     at Array.map (<anonymous>)
>     at Object.log.<computed> [as info] (c:\Users\eeliu\.vscode\extensions\shengchen.vscode-leetcode-0.16.1\node_modules\vsc-leetcode-cli\lib\log.js:55:20)
>     at c:\Users\eeliu\.vscode\extensions\shengchen.vscode-leetcode-0.16.1\node_modules\vsc-leetcode-cli\lib\commands\user.js:121:13
>     at c:\Users\eeliu\.vscode\extensions\shengchen.vscode-leetcode-0.16.1\node_modules\vsc-leetcode-cli\lib\plugins\leetcode.js:529:14
>     at Request._callback (c:\Users\eeliu\.vscode\extensions\shengchen.vscode-leetcode-0.16.1\node_modules\vsc-leetcode-cli\lib\plugins\leetcode.js:428:19)
>     at self.callback (c:\Users\eeliu\.vscode\extensions\shengchen.vscode-leetcode-0.16.1\node_modules\request\request.js:185:22)
>     at Request.emit (events.js:210:5)
>     at Request.onRequestError (c:\Users\eeliu\.vscode\extensions\shengchen.vscode-leetcode-0.16.1\node_modules\request\request.js:881:8)
>     at ClientRequest.emit (events.js:210:5)
> login: cookie: - Retrieving user favorites
> [WARN] Failed to retrieve user favorites: Error: connect ETIMEDOUT 104.18.34.28:443
> - Retrieving user profile
> c:\Users\eeliu\.vscode\extensions\shengchen.vscode-leetcode-0.16.1\node_modules\vsc-leetcode-cli\lib\log.js:55
>       let s = args.map(x => x.toString()).join(' ');
>                               ^
> 
> TypeError: Cannot read property 'toString' of undefined
>     at c:\Users\eeliu\.vscode\extensions\shengchen.vscode-leetcode-0.16.1\node_modules\vsc-leetcode-cli\lib\log.js:55:31
>     at Array.map (<anonymous>)
>     at Object.log.<computed> [as info] (c:\Users\eeliu\.vscode\extensions\shengchen.vscode-leetcode-0.16.1\node_modules\vsc-leetcode-cli\lib\log.js:55:20)
>     at c:\Users\eeliu\.vscode\extensions\shengchen.vscode-leetcode-0.16.1\node_modules\vsc-leetcode-cli\lib\commands\user.js:121:13
>     at c:\Users\eeliu\.vscode\extensions\shengchen.vscode-leetcode-0.16.1\node_modules\vsc-leetcode-cli\lib\plugins\leetcode.js:529:14
>     at Request._callback (c:\Users\eeliu\.vscode\extensions\shengchen.vscode-leetcode-0.16.1\node_modules\vsc-leetcode-cli\lib\plugins\leetcode.js:428:19)
>     at self.callback (c:\Users\eeliu\.vscode\extensions\shengchen.vscode-leetcode-0.16.1\node_modules\request\request.js:185:22)
>     at Request.emit (events.js:210:5)
>     at Request.onRequestError (c:\Users\eeliu\.vscode\extensions\shengchen.vscode-leetcode-0.16.1\node_modules\request\request.js:881:8)
>     at ClientRequest.emit (events.js:210:5)
> ```

It's blocked by some ...

**Comment by AielloChan** [comment]
what? Me either☹️
