### ISSUE TITLE
题目名字有误

### ISSUE THREAD

**Issue by hemingyuan** [jdneo/vscode-leetcode#155]
在vscode中显示867题为 "新21点"

![image](https://user-images.githubusercontent.com/22365305/53402748-463dd300-39ed-11e9-9e39-c1cd358df3ef.png)

力扣867题为 "转置矩阵"

![image](https://user-images.githubusercontent.com/22365305/53402845-71282700-39ed-11e9-8434-9c11aed7e0ec.png)

![image](https://user-images.githubusercontent.com/22365305/53402899-8f8e2280-39ed-11e9-85d8-3fd7c98c2b9c.png)

**Comment by hemingyuan** [comment]
501 题也对不上
从744开始到最后，好像都有问题

**Comment by LuVx21** [comment]
我也遇到了 如925

**Comment by LucasDove** [comment]
我也遇到

**Comment by poppinlp** [comment]
@hemingyuan @LuVx21 @LucasDove 请问可以提供一下重现的步骤么？感谢。

**Comment by jdneo** [comment]
@poppinlp I also met this problem. Still, this is restricted by the `leetcode-cli` 😢 

I think we need to write our own lib ASAP. Let's discuss in the Gitter channel in details.

**Comment by LuVx21** [comment]
没什么特殊的
1. 登录
2. 选择一个题,如925
3. 获取到后就能发现问题了
![image](https://user-images.githubusercontent.com/10940827/53708785-fbe6a700-3e6f-11e9-86cb-be32d107a58c.png)
题目和内容不匹配

**Comment by hemingyuan** [comment]
@poppinlp 
现象描述:
据我观察，使用插件获取到的题目，从744题开始 题目标题与题目内容不符。题目内容是正确的，只有题目标题显示错误。


操作步骤:
1. 登陆力扣
2. 查看题目

我尝试过
1. 刷新题目
2. 退出重新登陆
3. 卸载插件重装

均无法解决问题。
Vscode 版本 1.31.1

下图为截取的一段题目与力扣上题目对比，可以看到都不对

![image](https://user-images.githubusercontent.com/22365305/53709509-9c8a9600-3e73-11e9-8be0-29775530a1e2.png)
![image](https://user-images.githubusercontent.com/22365305/53709542-d360ac00-3e73-11e9-8095-6af0e97232f0.png)





题目内容是正确的，只有题目名字错误。

![image](https://user-images.githubusercontent.com/22365305/53709834-44549380-3e75-11e9-96c9-630f84fff626.png)

**Comment by COKID** [comment]
743和744命名重复，一个中文命名，一个英文命名，导致后面题号和问题错位

**Comment by xuzaixian** [comment]
It's a leetcode-cli plugin`(leetcode.cn.js)` bug.
I have sent a [pr[(https://github.com/skygragon/leetcode-cli-plugins/pull/32) to fix this issue.
But I am not sure if the owner is still maintaining...

**Comment by poppinlp** [comment]
@xuzaixian Hi. Thanks for your help. The leetcode-cli seems not active for a while.

@jdneo  So... looks like we need to fork the plugin like we fork the CLI?  😢

**Comment by jdneo** [comment]
@poppinlp Yes, how about fork both the leetcode-cli and leetcode-cli-plugin into here: https://github.com/leetcode-tools?

**Comment by poppinlp** [comment]
@jdneo  Yep. Sure.
The current vsc-leetcode-cli is in your private repo?

**Comment by jdneo** [comment]
Yes, I forked it into my repo for now. This should not be in our long-tern plan.

**Comment by blanquizel** [comment]
746使用最小花费爬楼梯（leetcode）在leetcode网页版完成后，在插件中显示完成的是746前缀和后缀搜索（插件）。
在插件中提交747使用最小花费爬楼梯（插件）进行测试时，使用的默认测试用例是748至少是其他数字两倍的最大数（插件）的。

![Uploading image.png…]()
![Uploading image.png…]()

**Comment by jdneo** [comment]
Closing this issue since this issue is addressed in `0.14.0` which will be released recently.

**Comment by haixinn** [comment]
version 0.14.1 
![image](https://user-images.githubusercontent.com/12841947/57139457-e34f2a80-6de7-11e9-86ef-c6b0254b65dd.png)

**Comment by haixinn** [comment]
delete cache

**Comment by jdneo** [comment]
For anyone who encounters this problem, please try delete cache first. (It's located at `$HOME/.lc/`)
