### ISSUE TITLE
同一个账号，不同机器上题目的完成状态无法动态同步更新

### ISSUE THREAD

**Issue by toyijiu** [jdneo/vscode-leetcode#157]
Hi，两台电脑登录同一个leetcode账号，并设置了git同步更新到我的remote repo，但是发现插件的问题状态无法动态的同步，PC1提交问题1测试通过状态更新了，在PC2上必须要手动重新跑一次test才能更新问题状态。

**Comment by jdneo** [comment]
@toyijiu What if you refresh the explorer in PC2?

**Comment by toyijiu** [comment]
@jdneo  Hi jdneo, the status I mentioned morning is not the explorer's but the status of the plug-in's  question list(The green hook). In one computer it also can not update to the finished status dynamically aftering passing the CI test. So I guess maybe it is better to add this function and I do not need to press the refresh button manually every time.

**Comment by jdneo** [comment]
@toyijiu So I guess it's dup with #91 .

Closing it for now and let's track it in #91

**Comment by phdsky** [comment]
I also encounted the same problem, press the refesh button in the extension on any pc is no use, unless re-submit... Can anyone help?
