### ISSUE TITLE
Failed to get submission beat ratio again

### ISSUE THREAD

**Issue by McKenzieIT** [jdneo/vscode-leetcode#158]
I found that the author fixed or optimized the problem that when we show a problem, the plugin will find if the file has been created, this is good! But it seems like that all the files were uploaded and the submission beats ratio can not be gotten again. I hope the problem can be fixed totally.

**Comment by jdneo** [comment]
@McKenzieIT May I ask what do you mean by: `all the files were uploaded`?

**Comment by McKenzieIT** [comment]
I mean that after you upload the files, my modifications which can fix the problem about the issue were reloaded.

**Comment by jdneo** [comment]
Yes, that is because once the extension has been updated, the extension files will be replaced. Let's track this issue in #105.

I'm planning to resolve it in recently.
