### ISSUE TITLE
整数反转描述错误

### ISSUE THREAD

**Issue by JesseHeisenberg** [jdneo/vscode-leetcode#159]
#### 这是整数反转的描述：
假设我们的环境只能存储得下 32 位的有符号整数，则其数值范围为 [−231,  231 − 1]。请根据这个假设，如果反转后整数溢出那么就返回 0。
#### 正确的应为：
假设我们的环境只能存储得下 32 位的有符号整数，则其数值范围为 [−2<sup>31</sup>,  2<sup>31</sup> − 1]。请根据这个假设，如果反转后整数溢出那么就返回 0。

**Comment by jdneo** [comment]
@JesseHeisenberg Thank you for reporting

This is dup with #74
