### ISSUE TITLE
Need to check the setting for 'outputFolder' before generating the file

### ISSUE THREAD

**Issue by Jotanrua** [jdneo/vscode-leetcode#160]
![image](https://user-images.githubusercontent.com/32889679/53484555-0e9f5b80-3abf-11e9-8477-6e3c52e15972.png)
点show problem之后就这样，输出栏也没有说明
vscode和nodejs是最新的，翻了下好像还没人遇到这个问题

**Comment by JesseHeisenberg** [comment]
设置输出路径为绝对路径会有这个问题，貌似那个是相对路径。清空后恢复正常

**Comment by Jotanrua** [comment]
@JesseHeisenberg 解决了，确实是工作区的相对路径

**Comment by jdneo** [comment]
Need to check the setting before generating the file

**Comment by jdneo** [comment]
@Jotanrua Let's reopen this issue since we figured out there is still something need to be improved there.

**Comment by jdneo** [comment]
Addressed in #336
