### ISSUE TITLE
Not supported languageXXX

### ISSUE THREAD

**Issue by McKenzieIT** [jdneo/vscode-leetcode#162]
There has a problem while I'm using the plugin. When I 'Show the problem', if the question doesn't support the language that I use, for example the python3. How can I change my using language in the current interface rather than changing the configuration files?

**Comment by McKenzieIT** [comment]
There has a problem while I'm using the plugin. When I 'Show the problem', if the question doesn't support the language that I use, for example the python3, the problem about the issue will turn up. How can I change my using language in the current interface rather than changing the configuration files?(My first comment lack some sentences.)

**Comment by jdneo** [comment]
Dup with #115
