### ISSUE TITLE
The icon in viewsContainers is blur in MacOSX

### ISSUE THREAD

**Issue by Eskibear** [jdneo/vscode-leetcode#165]
You might compare it with other icons, it looks uncomfortable. 

<img width="51" alt="screen shot 2019-02-28 at 1 18 12 pm" src="https://user-images.githubusercontent.com/2351748/53542860-58d61a80-3b5b-11e9-911c-0db43715a681.png">

**Comment by jdneo** [comment]
Fixed in #175 

Thank you @poppinlp for help!
