### ISSUE TITLE
Add issue templates

### ISSUE THREAD

**Issue by poppinlp** [jdneo/vscode-leetcode#169]
We may add some Github issue templates such as bug report template and feature request template.

The bug report template is to collect some basic information from submitting a new issue. This may be useful for analysis and reproduce the problem. Here are what I thought of:

- operation system
- extension settings
- nodejs version
- vscode version(or is insider version)
- extension version(although there's an auto upgrade)

The feature request template is to make the request clear. It may include:

- What's the situation right now?
- What do you expect?
- Would you like to submit a PR for it? If so, what's your solution?

**Comment by jdneo** [comment]
LGTM.

So would you like to submit a PR for it? 😀

**Comment by jdneo** [comment]
Resolved. @poppinlp Nice job!
