### ISSUE TITLE
如何同步VsCode 和 LeetCode网页上的内容

### ISSUE THREAD

**Issue by DioCin** [jdneo/vscode-leetcode#177]
在vsCode 上提交完以后  网页上 显示本道题 solved 但是点进去 网页上的编译器里面的内容是空的。。如何才能同步网页编译器里的内容 和Vscode 题目的编写的内容？

**Comment by taoweicn** [comment]
试一下编辑框右上角的这个按钮，可以恢复最近一次提交的代码。

![image](https://user-images.githubusercontent.com/25795549/53680059-bf506980-3d10-11e9-97b0-bb7129fe199c.png)

**Comment by poppinlp** [comment]
@DioCin Hi. 请问上面的方案可以满足你的需求么？我觉得这个看起来并不是一个应该属于 vscode 插件的功能，因为 leetcode 题目的网页上展示的代码其实是来自浏览器本地 `localstorage` 之中，例如：
![image](https://user-images.githubusercontent.com/1970625/53690362-194e3f00-3da4-11e9-9c9e-aecb551ba811.png)

**Comment by jdneo** [comment]
Closing since it is not in the extension's scope for now.

@DioCin Feel free to let us know if you have other problems.
