### ISSUE TITLE
Wrong order of the difficulty node in explorer

### ISSUE THREAD

**Issue by jdneo** [jdneo/vscode-leetcode#181]
<img width="304" alt="screen shot 2019-03-03 at 7 32 24 pm" src="https://user-images.githubusercontent.com/6193897/53694603-1d05b400-3dec-11e9-8f44-05bb9831d373.png">

Should be Easy -> Medium -> Hard

**Comment by taoweicn** [comment]
How about adding an `All` problem list, maybe there are some one like me who want to solve the problems in order?

**Comment by jdneo** [comment]
@taoweicn Sure, please feel free to create an issue for it
