### ISSUE TITLE
这个插件做题的时候能不能debug？该怎么使用？

### ISSUE THREAD

**Issue by wanmeng8888** [jdneo/vscode-leetcode#183]
Before you submit an question we recommend you to check out the [DOCUMENT](https://github.com/jdneo/vscode-leetcode/blob/master/README.md) and [TROUBLESHOOTING PAGE](https://github.com/jdneo/vscode-leetcode/wiki/Troubleshooting) first.

## 💬 Questions and Help

Please outline the questions.
我想知道可不可以进行debug？

**Comment by jdneo** [comment]
Hi @wanmeng8888, 

Unfortunately, for now, the extension does not support debugging, and it's not in our roadmap so far.
