### ISSUE TITLE
Add an `All` problem list

### ISSUE THREAD

**Issue by taoweicn** [jdneo/vscode-leetcode#184]
## 🚀 Feature Proposal

Add a new problem list which contains all leetcode problems.

## Motivation

Maybe someone such as me wants to solve problems in order.

**Comment by yucaowang** [comment]
+1

**Comment by jdneo** [comment]
@Vigilans I'm thinking to refactor the explorer before adding new features to it. For example, extract the logic of node reference to a cache called something like `xxxCache` or `nodeManager`...
