### ISSUE TITLE
The width occupied by the status bar is too wide

### ISSUE THREAD

**Issue by luffyli** [jdneo/vscode-leetcode#187]
![pic](https://user-images.githubusercontent.com/10166950/53804681-237a6400-3f83-11e9-89bb-13738615aa4a.png)

I hope it's adaptive width.

**Comment by jdneo** [comment]
@luffyli I'm afraid that the VS Code does not provide an API to control the width of the status bar item.

But, if I can provide a configuration to hide this status bar item, will it work for you?

**Comment by luffyli** [comment]
@jdneo I found that the VS Code status bar itself is adaptive width, and this problem was actually solved by bug #112.

The problem with bug #112 is that the username obtained is the selected part of the image below.

![pics](https://user-images.githubusercontent.com/10166950/53878691-7ddcf880-4047-11e9-8c43-2e02a0e28c3c.png)

**Comment by jdneo** [comment]
OK I'll take a look.

**Comment by jdneo** [comment]
Closing this and tracking in #112
