### ISSUE TITLE
可以不依赖 Node.js 吗？Can we not rely on node. js

### ISSUE THREAD

**Issue by KevinZhangt** [jdneo/vscode-leetcode#191]
## 🚀 Feature Proposal
对于后端来说，Node 环境不是必选项，因为这个插件安装 node 显得有点麻烦。能不能移除对 Node 的依赖？
For a backend developer, We are not  need  Node environment all  the time ,and It's a little trouble if  we install  Node  only use for this plugin.Can we not rely on node please?

**Comment by jdneo** [comment]
For now, since the extension is based on `leetcode-cli`. There is no easy way to remove the dependency on `Node.js`. We are considering to write our own lib, but this will take times and will not happen in the near future.

**Comment by jdneo** [comment]
Closing it for now.
