### ISSUE TITLE
[Not Found]186. Reverse Words in a String II

### ISSUE THREAD

**Issue by yuchaozh** [jdneo/vscode-leetcode#194]
## 🐛 Bug Report

`186. Reverse Words in a String II` is not found

## To Reproduce
search `186. Reverse Words in a String II`

## Expected behavior
shows up in the search result

## Your Environment

- *os*: Windows
- *extension settings*:
- *nodejs version*:
- *vscode version*: 1.32.1
- *extension version*: 0.12.0

**Comment by jdneo** [comment]
Can you see it after opening the setting: [leetcode.showLocked](https://github.com/jdneo/vscode-leetcode#settings)

**Comment by yuchaozh** [comment]
yeah. It works.
