### ISSUE TITLE
Can't update problem status with [WARN] Failed to get memory percentile.

### ISSUE THREAD

**Issue by tomleung1996** [jdneo/vscode-leetcode#195]
## 🐛 Bug Report

When I submitted the answer and get accepted, the last line of the response was `[WARN] Failed to get memory percentile.`

And with this warning, the problem status cannot be updated, even though my answer was accepted.

![problem](https://i.loli.net/2019/03/09/5c83197d22b33.png)

![response](https://i.loli.net/2019/03/09/5c83199cbb0f3.png)

## To Reproduce

Just submit the question.

## Expected behavior

Problem status not updated

## Your Environment

- *os*: Windows 10, 1809
- *extension settings*:
- *nodejs version*: v10.15.2
- *vscode version*: 1.32.1
- *extension version*: 0.12.0

**Comment by aaronbai** [comment]
I have the same issue  on Mac using Golang.

**Comment by tomleung1996** [comment]
> In fact, the submit command and result provider do not contain logic to update/refresh the tree explorer...
> 
> Seems that with or without the `[WARN] Failed to get memory percentile` message, the problem status will not be updated?
> 
> Do you mean after refreshing, the problem status still is not updated?

Yes, after refreshing

**Comment by Vigilans** [comment]
@tomleung1996  Could you please provide the accepted code for the convenience of reproducing the bug?

**Comment by tomleung1996** [comment]
> @tomleung1996 Could you please provide the accepted code for the convenience of reproducing the bug?

It seems that this situation has some uncertainty. Some questions' status can be updated today, but others still not.
Solution for No.112 Pathsum
<pre>
class Solution(object):
    def hasPathSum(self, root, sum):
        """
        :type root: TreeNode
        :type sum: int
        :rtype: bool
        """
        if not root:
            return False
        sum -= root.val
        if sum == 0 and not root.left and not root.right:
            return True
        return self.hasPathSum(root.left, sum) or self.hasPathSum(root.right, sum)
</pre>

**Comment by jdneo** [comment]
@tomleung1996 Will your problem be solved if adopting the workaround that @Vigilans provides?

**Comment by tomleung1996** [comment]
> @tomleung1996 Will your problem be solved if adopting the workaround that @Vigilans provides?

Works fine for me, thanks! XD

**Comment by jdneo** [comment]
Cool!
