### ISSUE TITLE
加入package name做本地测试直接提交会报错。建议增加提交时自动去除package name功能

### ISSUE THREAD

**Issue by liulanghai** [jdneo/vscode-leetcode#196]
Before you submit an question we recommend you to check out the [DOCUMENT](https://github.com/jdneo/vscode-leetcode/blob/master/README.md) and [TROUBLESHOOTING PAGE](https://github.com/jdneo/vscode-leetcode/wiki/Troubleshooting) first.

## 💬 Questions and Help

Please outline the questions.

**Comment by zombie110year** [comment]
建议贴出你解题使用的语言与测试工具, 不然的话不知道 "package name 报错" 是什么意思,
以及它需要满足什么要求.

**Comment by liulanghai** [comment]
show problem 之后生成了.go文件，这个go文件缺少package名称 ，完成了算法函数的填充，此时是无法再本地做单测的，手动加上package leetcode, 此时可以本地go test 做单测，但是此时直接右键提交报错。

**Comment by Vigilans** [comment]
A better solution would be automatically pre-include these packages, provide intellisense and make it possible to use local debugger.
I am currently working on this.

**Comment by jdneo** [comment]
Same as #418. This should be addressed in `0.15.5`.

Please have a try and let us know if the problem has been solved.

Thanks
