### ISSUE TITLE
Support deleting session

### ISSUE THREAD

**Issue by codenot** [jdneo/vscode-leetcode#198]
![屏幕快照 2019-03-11 下午12 32 37](https://user-images.githubusercontent.com/3368517/54100544-e508fd00-43f9-11e9-84f3-4ca6f82ad158.png)

**Comment by jdneo** [comment]
For now, the extension does not support deleting the session.

As a workaround, you can go to the official site of LeetCode, and manage your session in your settings page.

**Comment by codenot** [comment]
囧，我还以为是插件自带的session管理呢，好吧，知道了，感谢。
