### ISSUE TITLE
无法显示所有的题目, 比如题目367就找不到

### ISSUE THREAD

**Issue by nilinyi-test** [jdneo/vscode-leetcode#199]
是不是无法显示premium的题目?

**Comment by jdneo** [comment]
I can find it. 

![image](https://user-images.githubusercontent.com/6193897/54251411-1d3b4780-4582-11e9-9138-73b1e76b0151.png)

If you want to show the locked problem, there is a setting for doing this. See: [leetcode.hideSolved](https://github.com/jdneo/vscode-leetcode/blob/master/docs/README_zh-CN.md#%E6%8F%92%E4%BB%B6%E9%85%8D%E7%BD%AE%E9%A1%B9)

**Comment by bennygato** [comment]
me too. such as problem 339 that is shown as 'unlocked' on my leetcode page (I got premium account), but couldn't find it in vscode. 
I guess the question is,is that possible to support questions under premium account? thank you!

**Comment by nilinyi-test** [comment]
Now I can find it too. That's weird. I'm pretty sure I cannot find it yesterday.
