### ISSUE TITLE
Solution webview doesn't highlight python3 language

### ISSUE THREAD

**Issue by Vigilans** [jdneo/vscode-leetcode#205]
## 🐛 Bug Report

The `highlight.js` seems unable to recognize python3, and will not highlight the code fences.

## To Reproduce

Execute `Show Top Voted Solution` on any problem with language python3, then we'll get
![image](https://user-images.githubusercontent.com/20227484/54288145-ea28a080-45e1-11e9-95bd-9d405b912eb9.png)

## Expected behavior

Alter `Solution.lang: python3` to `python` when passed to `highlight.js`.

**Comment by jdneo** [comment]
@Vigilans I think this should be fixed in #224, right?

**Comment by Vigilans** [comment]
@jdneo Yes, I have tested it.
