### ISSUE TITLE
python3本地调试会报错

### ISSUE THREAD

**Issue by jlhxxxx** [jdneo/vscode-leetcode#206]
## 🐛 Bug Report

设置python3为默认语言，使用leetcode默认定义在本地调试会报错：undefined name name，这可能应该算python调试插件的问题

## To Reproduce
提交代码至leetcode没有问题。
就是本地debug报错。屏蔽flake8(F821)也不行。

```
class Solution:
    def twoSum(self, nums: List[int], target: int) -> List[int]:
```

报错信息：

```
{
	"resource": "/d:/work/Workspaces/MYGitHub/leetcode/1.两数之和.py",
	"owner": "python",
	"code": "F821",
	"severity": 8,
	"message": "undefined name 'List'",
	"source": "flake8",
	"startLineNumber": 30,
	"startColumn": 28,
	"endLineNumber": 30,
	"endColumn": 28
}
```

## Expected behavior

可以正常调试，不报错。

## Your Environment

- *os*: win7_x64
- *python version*: 3.7.2
- *extension settings*: ms-python.python-2019.2.5558
- *nodejs version*: 10.15.3
- *vscode version*: 1.32.1
- *extension version*: ms-python.python-2019.2.5558

**Comment by Vigilans** [comment]
> "message": "undefined name 'List'"
 add `from typing import List`

**Comment by jdneo** [comment]
You can have a try as @Vigilans said.

For now, the leetcode extension does not have the syntax highlighting feature there. So if users want to have this feature, they need to install some language-specific extensions, also there are some additional works to do to make them work together.

**Comment by jlhxxxx** [comment]
> > "message": "undefined name 'List'"
> 
> add `from typing import List`

Thank you, it works.

**Comment by illuca** [comment]
def twoSum(self, nums: 'List[int]', target: int) -> 'List[int]':
add '' to List
