### ISSUE TITLE
Cannot search problem with subscription while the account has one

### ISSUE THREAD

**Issue by ZanneZankyo** [jdneo/vscode-leetcode#209]
## 🐛 Bug Report

Search problem cannot show the problem that needs a subscription (like 186.)

## To Reproduce

>LeetCode: Search Problem
then input
186.

## Your Environment

- *os*: Windows 10 Version	10.0.17763 Build 17763
- *extension settings*: {}
- *nodejs version*: 10.2.0
- *vscode version*: 1.32.1
- *extension version*: 0.12.0

**Comment by jdneo** [comment]
Dup with #194 

Solution: https://github.com/jdneo/vscode-leetcode/issues/194#issuecomment-472341071

I'll add it into the trouble shooting page later.

**Comment by ZanneZankyo** [comment]
Sorry, It was clearly written in the doc.
