### ISSUE TITLE
Preview webview won't change title when switched to another problem

### ISSUE THREAD

**Issue by Vigilans** [jdneo/vscode-leetcode#210]
## 🐛 Bug Report

As the title describes.

## To Reproduce

Open preview window on any problem:
![image](https://user-images.githubusercontent.com/20227484/54433041-d443e880-4765-11e9-81b5-f68505654365.png)

Keep the window open and click another problem:
![image](https://user-images.githubusercontent.com/20227484/54433084-f3db1100-4765-11e9-8882-6be6bb4596d5.png)

## Expected behavior

The title should change when switched to another problem.

**Comment by jdneo** [comment]
@Vigilans Thank you for raising this. In the next version `0.13.1` we can address several bugs as a stable release.

New features can be held on for the `0.14.0`.
