### ISSUE TITLE
Miss problem 159 Longest Substring with At Most Two Distinct Character. 

### ISSUE THREAD

**Issue by wz30** [jdneo/vscode-leetcode#218]
## 🐛 Bug Report

Miss problem 159.

## To Reproduce

select the search button and input 159 or related keywords 

## Expected behavior

159 problem pops up!

## Your Environment

- *os*:
- *extension settings*:
- *nodejs version*:
- *vscode version*:
- *extension version*:

**Comment by jdneo** [comment]
See: https://github.com/jdneo/vscode-leetcode/wiki/Troubleshooting#thinking-cannot-show-the-locked-problems
