### ISSUE TITLE
Incompatible with VIM extension

### ISSUE THREAD

**Issue by Summerslyb** [jdneo/vscode-leetcode#219]
## 🐛 Bug Report

Cannot work with vim extension

## To Reproduce

1. Install this extension
2. Install vim extension
3. Open any problem
4. A error prompt show and cannot input any character

## Expected behavior

![QQ截图20190318001337](https://user-images.githubusercontent.com/10459559/54494267-50c7fa00-4913-11e9-8322-bc1add423544.png)

## Your Environment

- *os*: Windows 10
- *extension settings*: none
- *nodejs version*: 10.x
- *vscode version*: 1.30.2
- *extension version*: 0.13.1

**Comment by Summerslyb** [comment]
![QQ截图20190318001337](https://user-images.githubusercontent.com/10459559/54494248-25dda600-4913-11e9-8168-e67b0b5fff35.png)

**Comment by jdneo** [comment]
From the screenshot, you can see that this bug comes from the `vim` extension.

My suggestion is to report this bug to the repo of `vim` extension.

So far we can do nothing for it. Please also let me know if you need any help.

Thanks.
