### ISSUE TITLE
Failed to sign in. Please open the output channel for details

### ISSUE THREAD

**Issue by ngunauj** [jdneo/vscode-leetcode#220]
```
leetcode插件 : 0.13.1
nodejs : v10.15.3
ubuntu16.04
今天突然登录不了了。换帐号也登录不了

----------------------------------------------------------------------------------------------------
   ✔     solution.discuss   2019.02.03      Plugin to fetch most voted solution in discussions.
   ✔     company            2017.12.18      Plugin to query by company for free user.
   ✔     cache              default         Plugin to provide local cache.
   ✔     retry              default         Plugin to retry last failed request if autologin.enable is on.
   ✘     leetcode.cn        2018.11.25      Plugin to talk with leetcode-cn APIs.
   ✔     leetcode           default         Plugin to talk with leetcode APIs.
[ERROR] You are not login yet?
login: pass: - Signing in leetcode.com
[ERROR] session expired, please login again [code=-1]
login: pass: - Signing in leetcode.com
[ERROR] session expired, please login again [code=-1]
login: pass: - Signing in leetcode.com
[ERROR] session expired, please login again [code=-1]
```

**Comment by jdneo** [comment]
@ngunauj What's your targeting endpoint? `leetcode` or `leetcode-cn`

**Comment by ngunauj** [comment]
> @ngunauj What's your targeting endpoint? `leetcode` or `leetcode-cn`

leetcode

**Comment by ngunauj** [comment]
@jdneo leetcode

**Comment by ngunauj** [comment]
@jdneo  我试着选中文办leetcode-cn 能登录，leetcode登录不了。不过能做题就行了...

**Comment by jdneo** [comment]
LeetCode has different endpoints which do not share the accounts.

So according to your description, you have registered in `leetcode-cn`, not `leetcode`.

The websites of them are different.

**Comment by lizhaoliu-Lec** [comment]
My endpoint is correct same for my password, I can still login in my web browser. But I can't sign in in this extension, receving the error below:
[ERROR] You are not login yet?
login: pass: - Signing in leetcode.com
[ERROR] session expired, please login again [code=-1]

**Comment by jdneo** [comment]
@lizhaoliu-Lec what will happen if you remove the cache folder: `$HOME\.lc`?

**Comment by HenryCharles** [comment]
I have the same question...and I don't know how to solve it..

**Comment by HenryCharles** [comment]
按照操作步骤进行的时候会弹出Failed to sign in. Please open the output channel for details 
然后选择open之后，信息如下：
login: pass: - Signing in leetcode.com
- Retrieving user favorites
[WARN] Favorite not found?
- Retrieving user profile
Successfully login as JustinAngeles
但是我左边没有出现题目，还是sign in to leetcode, 请问是什么原因？

**Comment by soldier828** [comment]
> 按照操作步骤进行的时候会弹出Failed to sign in. Please open the output channel for details
> 然后选择open之后，信息如下：
> login: pass: - Signing in leetcode.com
> 
> * Retrieving user favorites
>   [WARN] Favorite not found?
> * Retrieving user profile
>   Successfully login as JustinAngeles
>   但是我左边没有出现题目，还是sign in to leetcode, 请问是什么原因？

I have the exactly same output. Have you solve it?

**Comment by soldier828** [comment]
> 按照操作步骤进行的时候会弹出Failed to sign in. Please open the output channel for details
> 然后选择open之后，信息如下：
> login: pass: - Signing in leetcode.com
> 
> * Retrieving user favorites
>   [WARN] Favorite not found?
> * Retrieving user profile
>   Successfully login as JustinAngeles
>   但是我左边没有出现题目，还是sign in to leetcode, 请问是什么原因？

I solve it. I disable my shadowsocks and login in successfully.

**Comment by jdneo** [comment]
@soldier828 I cannot repro it on my side. Is there anything suspicious that you have observed?

**Comment by jdneo** [comment]
@HenryCharles Please check @soldier828's [answer](https://github.com/jdneo/vscode-leetcode/issues/220#issuecomment-517123735) and have a try.

**Comment by HenryCharles** [comment]
OK，Thanks for your help.


| |
赵富强
|
|
fuqiang_vip@163.com
|
签名由网易邮箱大师定制


On 08/1/2019 13:48，Sheng Chen<notifications@github.com> wrote：

@HenryCharles Please check @soldier828's answer and have a try.

**Comment by nicemz** [comment]
I met this problem once.I have a idea.if your account is china,you should switch to china version then sign in.

**Comment by jdneo** [comment]
Close for inactive for a long time
