### ISSUE TITLE
Sort by Problem No.

### ISSUE THREAD

**Issue by dilin-MS** [jdneo/vscode-leetcode#221]
## 🚀 Feature Proposal

 Can we sort problem list by its number? 

## Motivation

Currently problem list can only be sorted and listed by difficulty, tag, company or favorite. Can we sort problem list by number? It's supported on Leetcode official website. Some people(like me) may prefer to just check problems by order.

## Contribution

Please describe the solution if you'd like to submit a PR.

**Comment by jdneo** [comment]
@dilin-MS Thank you for reporting.

Let's track in #184 for duplication.
