### ISSUE TITLE
不能通过插件登录

### ISSUE THREAD

**Issue by zhning12** [jdneo/vscode-leetcode#222]
## 可以通过官网成功登陆，但是无法通过插件登录
![image](https://user-images.githubusercontent.com/28998173/54558606-1fc1f500-49f9-11e9-826f-97b546451698.png)

试了npm install leetcode 等的解决方案，也无法登陆，不知道是什么原因？

**Comment by jdneo** [comment]
Please try the troubleshooting here: https://github.com/jdneo/vscode-leetcode/wiki/%E7%96%91%E9%9A%BE%E8%A7%A3%E7%AD%94#thinking-%E6%97%A0%E6%B3%95%E7%99%BB%E5%BD%95

Also please let us know if this could solve your problem.

**Comment by zhning12** [comment]
Thanks, that solves my problem. This occurs since I choose the **Chinese** version.
