### ISSUE TITLE
已完成的绿色对勾无法显示

### ISSUE THREAD

**Issue by WRN1111** [jdneo/vscode-leetcode#223]
## To Reproduce

Steps to reproduce the behavior.

## Expected behavior
win10系统下尝试过完全重装 以后依然无法显示绿色对勾 check.png文件也没有缺失 但是在另一台电脑上没有问题 是什么设置的问题吗
![捕获](https://user-images.githubusercontent.com/18515547/54574408-223d4280-4a2b-11e9-9513-0ee82bf5d1bb.PNG)

**Comment by jdneo** [comment]
Are you using the same account and the same session?

**Comment by WRN1111** [comment]
I created a new session，new account(leetcode and leetcode-cn),submit a problem,It still doesn't display correctly.

**Comment by jdneo** [comment]
@WRN1111 So far the explorer won't refresh automatically. Try clicking the refresh button on the navigation bar at the top of the LeetCode explorer.

**Comment by WRN1111** [comment]
yeah i click the refresh button,it still doesn't display,but It seems to be my own problem.Another computer no problem.

Thank you for your help！！

**Comment by jdneo** [comment]
Make sure your two computers are using the same session of the same account under the same endpoint.

Feel free to let us know if you have any more questions.
