### ISSUE TITLE
when using behind proxy,it shows command 'leetcode.xxxx' not found

### ISSUE THREAD

**Issue by zhuxiangxiao** [jdneo/vscode-leetcode#226]
## 🐛 Bug Report

command 'leetcode.xxx' not found error when using behind a proxy.
with environment viriable HTTP_PROXY=127.0.01:6152 and HTTPS_PROXY=127.0.01:6152

## To Reproduce

I'm using zsh as my defaul shell 

export HTTP_PROXY=127.0.0.1:6152
export HTTPS_PROXY=127.0.0.1:6152

## Your Environment
macOS 10.14.3
vscode 1.32.3
vscode-leetcode 0.13.1
node 11.10.0

**Comment by jdneo** [comment]
Should be the same as this issue, please take a look: https://github.com/jdneo/vscode-leetcode/issues/201#issuecomment-472289712

**Comment by jdneo** [comment]
@zhuxiangxiao If you want to enable the proxy in the extension. Just simply update the proxy setting in VS Code.

See: https://github.com/jdneo/vscode-leetcode/issues/117#issuecomment-462615941
