### ISSUE TITLE
"There is no data provider registered that can provide view data."

### ISSUE THREAD

**Issue by gislu** [jdneo/vscode-leetcode#238]
When I installed the plugin and restart my VSCode, I only got this message: "There is no data provider registered that can provide view data."
I guess this happened because my company ban some kinds of request  ( but I am still able to log in leetcode website and solve question). Do you guys have any idea of my issue?

**Comment by jdneo** [comment]
@gislu Please provide more information about your environment etc... to help us understand your situation. Meanwhile, you can check if this document could help: https://github.com/jdneo/vscode-leetcode/wiki/Troubleshooting

**Comment by LiRongbupt** [comment]
@jdneo emmm, I meet the same problem, baby. I have intalled nodejs v8.x, v10.x and v11.x, but vscode still told me that command leetcode.signin not found. My os is ubuntu 18.04 LTS. Interesting, I didn't meet this problem last week when I used vscode on ubuntu 16.04.

**Comment by jdneo** [comment]
@LiRongbupt Could you try to remove `$home/.lc`?

**Comment by gislu** [comment]
Solve this when I reinstall with old version 0.12.0.
So I guess there might be some code issue here.

**Comment by gislu** [comment]
But I can login leetcode in browser normally. Does we use different way to make login post?

**Comment by jdneo** [comment]
@gislu You can open `Help` > `Toggle Developer Tools` to see if there is any log there

**Comment by LiRongbupt** [comment]
> @LiRongbupt Could you try to remove `$home/.lc`?

I'm sorry that it doesn't work. Everytime I restart vscode, the directory .lc is created automatically.

**Comment by jdneo** [comment]
@LiRongbupt Are you using the 3-party bash in Ubuntu?

**Comment by LiRongbupt** [comment]
@jdneo No, but I solved the problem. First I uninstall vscode and remove .lc/ and .vscode/, then I re-install code and the plugin works well.

**Comment by jdneo** [comment]
@LiRongbupt Good to know them problem get solved. I'll leave an eye on this problem in the future.

**Comment by Fern9** [comment]
> @LiRongbupt Good to know them problem get solved. I'll leave an eye on this problem in the future.

I meet the same problem. My os is macOS 10.14, and vscode 1.32.3, node v11.12.0, bash is iTerm2。I have tried restart vscode and OS, but it still says leetcode.signin not found

**Comment by jdneo** [comment]
@Fern9 This is because you are using iTerms2, while when the extension spawns a new child process, it will use the system default bash.

This problem should be resolved within this issue: https://github.com/jdneo/vscode-leetcode/issues/227

**Comment by jdneo** [comment]
Closing this issue and tracking with #227.

**Comment by nina-h-g** [comment]
I’m not sure if this will help, and my computer knowledge is very limited, so it might not be directly relevant to your issue. I encountered the same error message in VSCode and spent hours searching without success. What finally worked for me was closing the workspace, opening the TMC extension, and then reopening the workspace (where the error would usually appear) AFTER closing any unnecessary exercises. After that, the extension started working.
