### ISSUE TITLE
Cant connect to leetcode.com

### ISSUE THREAD

**Issue by littlebeandog** [jdneo/vscode-leetcode#240]
## 🐛 Bug Report

It's fine to access leetcode.com using chrome,but unable to login or submit problem with the extension.
Error message:
[ERROR] Error: connect ETIMEDOUT 104.24.124.31:443

This condition didn't appear until 2019.03.27, is it my network problem?

**Comment by jdneo** [comment]
Are you behind a proxy?

**Comment by gislu** [comment]
Got the same issue while I can login in browser normally....

**Comment by guozongkui** [comment]
Same issue, No proxy.

**Comment by littlebeandog** [comment]
> Are you behind a proxy?

nope.. and it happens frequently since I firstly report this issue.

**Comment by jdneo** [comment]
@all

Is this a stable repro issue or does it just appear sometimes?

**Comment by gislu** [comment]
for me it always failed like that

**Comment by jdneo** [comment]
Solution: 

We should embed the plugins by default and remove the `install plugin` logic in the code to avoid user get blocked because of the network issue.

**Comment by littlebeandog** [comment]
> Solution:
> 
> We should embed the plugins by default and remove the `install plugin` logic in the code to avoid user get blocked because of the network issue.

Dude, I've read and tried to understand your reply for couple times, but still can't get it - -

I think gislu is right, it seems like network promblem cuz endpoint leetcode-cn works perfectly.
Is that possible to add a feature to config proxy for this plugin?

**Comment by jdneo** [comment]
Config proxy is supported, actually, the extension should honor the proxy setting in VS Code. 

See: https://github.com/jdneo/vscode-leetcode/issues/117#issuecomment-466770086

**Comment by littlebeandog** [comment]
> Config proxy is supported, actually, the extension should honor the proxy setting in VS Code.
> 
> See: [#117 (comment)](https://github.com/jdneo/vscode-leetcode/issues/117#issuecomment-466770086)

Thanks !

**Comment by jdneo** [comment]
@littlebeandog Is that works?

**Comment by littlebeandog** [comment]
> @littlebeandog Does that work?

It works fine.

**Comment by Dark-Existed** [comment]
@jdneo hi, I have the same problem 
![image](https://user-images.githubusercontent.com/24956657/55529679-25942780-56d5-11e9-8387-e65ae9d03b51.png)
I didn't use any proxy,  leetcode-cn work for me in broswer.
when I test my code, or submit my code, this error happen.
[ERROR] Error: connect ETIMEDOUT 47.99.228.218:443

**Comment by jdneo** [comment]
The needed plugins are now embedded into the cli.

**Comment by Leslie-Wong-H** [comment]
Using 0.13.3 right now, but still got this problem.  

Error: connect ETIMEDOUT 104.24.125.31:443

**Comment by jianlong-yuan** [comment]
Same problem:
[ERROR] Error: connect ETIMEDOUT 47.99.228.218:443

**Comment by chenxli** [comment]
I also meet this problem today, but since yesterday I can't open the leetcode page, and then the vscode appear this problem too, but the day before yesterday everything is OK..... I don't know the reason.....

**Comment by Hxyspace** [comment]
Same problem:
Error: connect ETIMEDOUT 104.18.35.28:443

**Comment by fismoilov20** [comment]
[SOLVED]

For me I turned off my VPN extension on my browser through Manage Extensions, it accessed leetcode.com instantly!
Interesting, why these VPN extensions specifically block some websites... [obviously]... [is that allowed?]
