### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by chnjames** [jdneo/vscode-leetcode#243]
- Issue Type: `Performance`
- Extension Name: `vscode-leetcode`
- Extension Version: `0.13.1`
- OS Version: `Windows_NT x64 10.0.17134`
- VSCode version: `1.32.3`

:warning: Make sure to **attach** this file from your *home*-directory: `C:\Users\14272\shengchen.vscode-leetcode-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by jdneo** [comment]
Thank you @chnjames for reporting this to us.

VS Code has its official [Explain: extension causes high cpu load](https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load) for the issue. 

>  it (VS Code) doesn’t isolate different extensions from each other. Due to the single threaded nature of JavaScript, an extension can, willingly or not, monopolize the extension host thread, block all other extensions, and make operations appear as unresponsive.

> Sometimes it's not code execution but code loading (which is also blocking) which causes unresponsive extension host. Profile then are harder to read. The problem is that there are too many, often little, files that all need to be read and loaded. 
https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load#code-loading

So far, I have no plan to optimize the problem unless there are more and more users encountering the same problem and the UX is hurted.
