### ISSUE TITLE
How can i debug my code

### ISSUE THREAD

**Issue by SongJee** [jdneo/vscode-leetcode#244]
Hello! I want to know how can i debug my code after i finish my solution in vscode. can anybody help me

**Comment by jdneo** [comment]
Hi @SongJee, 

Debug is not supported yet. If you want to debug your solution, you need to install related language extensions and write some code to wrap your solution.

**Comment by littlebeandog** [comment]
I dont think this is a concern of this extension though.....

**Comment by Vigilans** [comment]
If you write your solution in cpp, you could try out the bootstrapper code here:
https://github.com/Vigilans/leetcode-bootstrapper/tree/master/cpp
You should provide your solution in `solution.h`, and provide class and method name in `meta.h`.
* If you need `ListNode` or `TreeNode` definition, define `__LIST_NODE` or `__TREE_NODE` in `meta.h`.
* If you need to write a data structure class (Trie, LRU, etc.), define `__SYSTEM_DESIGN` and put your constructor in `__CLASS` macro.

This feature is currently under early discussion, and is a concern of mine.

**Comment by Luanf** [comment]
Just wanted to add that my approach has been using the CodeRunner extension: https://marketplace.visualstudio.com/items?itemName=formulahendry.code-runner

I then add a call to the solution function, like so:
```
// Pre generated template
solution(...) {
    ...
}
// I add this line so running CodeRunner executes the function
solution()
```
Of course you can then add inputs to it:
```
a = 'foo'
b = 'bar'
solution(a, b)
```
Depending on the problem.

**Comment by BrambleXu** [comment]
You can write test cases by yourself. Here is mine.

```
if __name__ == "__main__":
    s = Solution()
    testcases = [
                 ("USA", True), 
                 ("leetcode", True),
                 ("Facebook", True),
                 ("HaWa", False),
                 ]
    for i, (inp, ans) in enumerate(testcases):
        print("Test case: ", i)
        print("answer:   ", s.detectCapitalUse(inp))
        print("expected: ", ans)
        print()
```

**Comment by jdneo** [comment]
Thank you @All for providing the solutions.

I'm closing the issue for now, but the discussion is still open!

For anyone who has his own solution about debugging the code, please feel free to comment.

You can also add 👍 for your favorite solution, which could be a guide for those who need help.
