### ISSUE TITLE
Failed to find some question

### ISSUE THREAD

**Issue by BrambleXu** [jdneo/vscode-leetcode#245]
Can not find 1013 question.

**Comment by jdneo** [comment]
- If you want to see the locked problems(like 277), you need to enable the setting `leetcode.showLocked`. More details: https://github.com/jdneo/vscode-leetcode/wiki/Troubleshooting#thinking-cannot-show-the-locked-problems

- I can find 1013 on my side, need more details to repro.
<img width="298" alt="Screen Shot 2019-03-31 at 6 54 40 PM" src="https://user-images.githubusercontent.com/6193897/55288215-bf628880-53e6-11e9-9805-f95e4b4c6441.png">
<img width="717" alt="Screen Shot 2019-03-31 at 6 54 54 PM" src="https://user-images.githubusercontent.com/6193897/55288216-bf628880-53e6-11e9-9dcc-6c422a35eea3.png">

**Comment by BrambleXu** [comment]
Thanks for the information about locked problems. 
As for 1013, I can find it now after reinstalling vscode-leetcode.
