### ISSUE TITLE
unable to activate the extension.

### ISSUE THREAD

**Issue by LucaPractice** [jdneo/vscode-leetcode#247]
您好，我的vscode版本为1.32.3，nodejs版本为10.15.3，使用插件时仍然有command 'leetcode.xxx' not found的错误提示。

**Comment by jdneo** [comment]
Is there any logs in the console if you open Help > Toggle Developer Tools

**Comment by Vigilans** [comment]
What we be shown if you click the leetcode icon on the left activity bar?

Besides, is there any output message if you press `Ctrl+Shift+U` and toggle the channel from `Tasks` or `任务` to `LeetCode`?

**Comment by jdneo** [comment]
@LucaPractice Just feel free to comment on the root cause and how you solve the problem. This information could help other users who also encounter the same problem.

Thanks.

**Comment by deadoggy** [comment]
I meet the same problem. The day before yesterday I could use the extension normally, today it fails. There is a "There is no data provider registered that can provide view data." on the sidebar and there is "leetcode.xxx not found"
. My environment is ubuntu 18.04lts + vscode 1.32.3 + node 10.15.3 . 

Here is my log:

![Screenshot from 2019-04-03 17-32-35](https://user-images.githubusercontent.com/16058908/55468700-87ea1b00-5636-11e9-8932-1c45d3cac662.png)

**Comment by deadoggy** [comment]
@jdneo Thanks!

**Comment by jdneo** [comment]
@deadoggy I guess the root cause is that the installed files are corrupted. Try to uninstall the extension and remove it. You should be able to find it under `$HOME/.vscode/extensions`. Remove the folder `shengchen.vscode-leetcode-*` and reinstall it.

Please let me know if this could help solve your problem.

**Comment by deadoggy** [comment]
I uninstalled the extension and removed the folder under ~/.vscode/extensions/, but the problem still exists. Here is the console screenshot:

![Screenshot from 2019-04-03 22-41-39](https://user-images.githubusercontent.com/16058908/55488006-c6e19600-5661-11e9-80c5-cf29f83a6a51.png)

It's almost the same as the prior one.

**Comment by jdneo** [comment]
Ah, Have no ideas so far.

But I noticed that there is some other strange output in the console:
![image](https://user-images.githubusercontent.com/6193897/55523993-135abf00-56be-11e9-8c5d-150a3cc10ecf.png)

Not sure if it is something wrong with your environment.

@Vigilans Do you have any ideas?

**Comment by Vigilans** [comment]
Found the problem.

![image](https://user-images.githubusercontent.com/20227484/55534228-60528b80-56e6-11e9-9070-83331f4ac5d4.png)
@deadoggy The line 6 is `require("./LeetCodeStatusBarItem")`, the first letter to be **upper case `L`**.

However, in the published extension, there is

![image](https://user-images.githubusercontent.com/20227484/55534521-3f3e6a80-56e7-11e9-8dd2-008b823276af.png)

the first letter to be **lower case `l`**.

Ubuntu file name is case-sensitive, resulting in the NotFound problem.

---
@jdneo btw, I checked the folder structure in the extension folder and found another thing strange:

![image](https://user-images.githubusercontent.com/20227484/55534118-0356d580-56e6-11e9-8e26-c8d11d8d72b0.png)

So there are two problems with the published extension:
* wrong letter case of `out/src/statusbar/leetcodeStatusBarItem.js`
* redundant file `out/src/leetcodeStatusBarItem.js`

**Comment by LucaPractice** [comment]
I made a low-level mistake. I installed the extension first and then installed nodejs. I found that I can't use it and I reinstalled the extension. I did not restart the vscode after uninstalling the extension, so I can't use it after reinstalling the extension.

**Comment by z774379121** [comment]
@Vigilans 
It can be work when I use upper case L in out/src/statusbar/leetcodeStatusBarItem.js:6:33  
Thanks!

**Comment by deadoggy** [comment]
@jdneo  @Vigilans It works after changing 'l' to 'L'. Thanks a lot!

**Comment by jdneo** [comment]
@All

@Vigilans and I are working on release a hotfix `0.13.3` for this issue.

**Comment by jdneo** [comment]
`0.13.3` released. Please feel free to let us know if you still meet the problem.

Thanks.
