### ISSUE TITLE
Use go write leetcode cant read my GOPATH

### ISSUE THREAD

**Issue by hantmac** [jdneo/vscode-leetcode#248]
## 🐛 Bug Report

I use golang write leetcode,  but report an error ,
<img width="914" alt="屏幕快照 2019-04-01 14 04 29" src="https://user-images.githubusercontent.com/7600925/55306687-9940f500-5487-11e9-972f-16ae1c1e52c5.png">
BUT，I have set the gopath for vscode,
<img width="578" alt="屏幕快照 2019-04-01 14 04 46" src="https://user-images.githubusercontent.com/7600925/55306699-a958d480-5487-11e9-97c2-14b5cb4cb3f0.png">

## Expected behavior

Get my gopath correctly.
## Your Environment

- *os*: mac os
- *extension settings*:  "leetcode.defaultLanguage": "golang",
- *nodejs version*:v8.12.0
- *vscode version*:1.32.3
- *extension version*:0.13.1

**Comment by jdneo** [comment]
This compile error is reported by `leetcode.com`, the extension will not compile your code locally.

Please make sure your solution could run correctly in `leetcode.com`

**Comment by hantmac** [comment]
> This compile error is reported by `leetcode.com`, the extension will not compile your code locally.
> 
> Please make sure your solution could run correctly in `leetcode.com`

Yeah，it is reported by `leetcode.com`,  this is the first time I use go to write leetcode, should I config GOPATH for leetcode.com?? So amazing! 
I can Definitely confirm the package `github.com/golang-collections/collections/stack`, is in my `GOROOT`.It still report this error.
I am confusing, anyway ,thanks for your timely reply.

**Comment by jdneo** [comment]
Hmm, I don't think the `leetcode.com` should honor the `GOPATH` since the judge env is totally different from the users' local env.

You can simply check the discussion pages to find out what other users' `golang` answer looks like, and write your answer in that way.

Closing this issue since this is out of the scope of the extension.

Thank you for trying the extension, happy coding!
