### ISSUE TITLE
Can we cache all the questions?

### ISSUE THREAD

**Issue by gislu** [jdneo/vscode-leetcode#252]
## Motivation
Cache all the questions so we can work on these questions offline.

## Contribution
I can help to analyze the request in order to build web scraper

**Comment by Vigilans** [comment]
The question is in fact cached (by `leetcode-cli`), and you can find them in `$HOME/.lc/leetcode/cache`.

Is there any other inconvenience you find in solving the problems offline?

**Comment by gislu** [comment]
Sorry I didn't mean cache it manually.
Right we can only cache the question we browsered.
Is it feasible to cache all the questions by one time?

**Comment by Vigilans** [comment]
The best way would be to fetch all the question details by one query, but leetcode-cli does not provide such functionality. 

A workaround would be to trigger `leetcode-cli show <id> -x` concurrently, but I don't know its cost and whether it is abuse...If you're of enough interest, you could take a stab at a PR to implement it.

Besides, there are plans to migrate from `leetcode-cli` to an independent library recently, maybe this functionality could be well implemented there.
