### ISSUE TITLE
`command 'leetcode.XXXXX' not found` after Upgrade to 0.13.2

### ISSUE THREAD

**Issue by BoseSean** [jdneo/vscode-leetcode#258]
## 🐛 Bug Report

Any Command will result in `command 'leetcode.XXXXX' not found` error. And downgrade to 0.13.1 will resolve the errors. 

## Extension Output

No output in OUTPUT CONSOLE.

`command 'leetcode.XXXXX' not found` in notification channel.
## Your Environment

```
-> % node -v
v8.10.0
-> % code --version
1.31.1
1b8e8302e405050205e69b59abb3559592bb9e60
x64
-> % uname -a
Linux xinye-Latitude 4.18.20-custom #1 SMP Mon Mar 25 13:49:35 +08 2019 x86_64 x86_64 x86_64 GNU/Linux

```

**Comment by jdneo** [comment]
Is there any output in the console if you click `Help` > `toggle developer tools`?

**Comment by Vigilans** [comment]
Please refer to this comment:
https://github.com/jdneo/vscode-leetcode/issues/247#issuecomment-479770731

**Comment by jdneo** [comment]
Tracking in #247.

Sorry for the confusion I made here.
