### ISSUE TITLE
Key Short cut map?

### ISSUE THREAD

**Issue by cakebytheoceanLuo** [jdneo/vscode-leetcode#262]
Before you submit an question we recommend you to check out the [DOCUMENT](https://github.com/jdneo/vscode-leetcode/blob/master/README.md) and [TROUBLESHOOTING PAGE](https://github.com/jdneo/vscode-leetcode/wiki/Troubleshooting) first.

## 💬 Questions and Help

Is it possible, that we can use some keyboard short cut to 'test' or 'submit'?

**Comment by Vigilans** [comment]
You can bind any of the vscode command to a key binding in `File -> Preferences -> Keyboard Shortcuts`

vscode-leetcode offer these two commands for you:
![image](https://user-images.githubusercontent.com/20227484/55670915-77e36d00-58bc-11e9-93b7-4dba00ff8348.png)
