### ISSUE TITLE
Add "Pick One" button

### ISSUE THREAD

**Issue by stultusverus** [jdneo/vscode-leetcode#263]
## 🚀 Feature Proposal

![image](https://user-images.githubusercontent.com/42622878/55680731-6fd90b00-5958-11e9-995f-6ff14b27536d.png)
This button circled in the image is the Pick One button. It picks a problem with a similar difficulty to your recent submissions. This could be very helpful for those who use leetcode as a daily exercise. Please add it into this addon!

**Comment by Vigilans** [comment]
Using `leetcode show` directly, we could randomly select a problem, yet it does not take recent submissions into account.

![image](https://user-images.githubusercontent.com/20227484/56485897-75ae1f00-6508-11e9-922f-88c0339fc4ad.png)
