### ISSUE TITLE
能否拉取已成功的submittion作为备份

### ISSUE THREAD

**Issue by hbsun2113** [jdneo/vscode-leetcode#264]
## 🚀 Feature Proposal

A clear and concise description of what the feature is.
这个插件很赞！我在使用这个插件前已经提交了很多题目，使用这个插件时发现不能查看之前的提交记录，就还是会依赖网页版。希望开发一个拉取已提交代码的功能。

## Motivation
可以将题目和代码保存到本地，然后push到自己的github仓库中

Please outline the motivation for the proposal.

## Contribution

Please describe the solution if you'd like to submit a PR.

**Comment by jdneo** [comment]
Thanks for reporting. Closing for we already has a same feature request here: https://github.com/jdneo/vscode-leetcode/issues/69
