### ISSUE TITLE
I cant sign in leetcode.com and get an error 

### ISSUE THREAD

**Issue by sepetboy** [jdneo/vscode-leetcode#265]
[ERROR] You are not login yet?
login: login: pass: - Signing in leetcode.com
login: pass: [ERROR] Error: connect ETIMEDOUT 104.24.124.31:443
- Signing in leetcode.com
[ERROR] Error: connect ETIMEDOUT 104.24.124.31:443

**Comment by jdneo** [comment]
Are you behind a proxy?

**Comment by sepetboy** [comment]
I am signed in the company network and should have a proxy

**Comment by jdneo** [comment]
It could be related to that. Could you please try to update the proxy setting to see if it could be solved?

See: https://github.com/jdneo/vscode-leetcode/issues/117#issuecomment-462615941

**Comment by sepetboy** [comment]
I set up the proxy and successfully signed in.

**Comment by jdneo** [comment]
That's good to know!

**Comment by hwm18** [comment]
Can't login VS Code leetcode plugin, I am using the correct user name and password, I can login in leetcode.com with Chrome.


Active  Name               Version         Desc
----------------------------------------------------------------------------------------------------
   √     solution.discuss   2019.02.03      Plugin to fetch most voted solution in discussions.
   √     company            2017.12.18      Plugin to query by company for free user.
   √     cache              default         Plugin to provide local cache.
   √     retry              default         Plugin to retry last failed request if autologin.enable is on.
   ×     leetcode.cn        2018.11.25      Plugin to talk with leetcode-cn APIs.
   √     leetcode           default         Plugin to talk with leetcode APIs.
[ERROR] You are not login yet?
login: pass: - Signing in leetcode.com
[ERROR] invalid password?

**Comment by jdneo** [comment]
@hwm18 See https://github.com/jdneo/vscode-leetcode/issues/478
