### ISSUE TITLE
Add `like` & `dislike` count

### ISSUE THREAD

**Issue by Lw-Cui** [jdneo/vscode-leetcode#267]
## 🚀 Feature Proposal

Add count of number of `like` or `dislike`.

## Motivation

Sometimes it's annoying to spend time on a problem that lots of people dislike it and suppose that it isn't worthy of energy (maybe its description is ambiguous, etc.) Users' feedback matters and it will be very helpful to have such rating.

**Comment by Vigilans** [comment]
Closed via https://github.com/leetcode-tools/leetcode-cli/pull/3 and #257.
