### ISSUE TITLE
Add  a "show top solution" item to the right click menu, pls

### ISSUE THREAD

**Issue by YorksonChang** [jdneo/vscode-leetcode#269]
## 🚀 Feature Proposal

When right click on the editor window，show the  "show the top solution" option in the menu.
Then users needn't look up the problem on the left to get the solution.

## Motivation

直接在代码窗口右键即可查看本问题的最优解法，而不需要在左栏重新找问题然后找答案。

## Contribution

Please describe the solution if you'd like to submit a PR.

**Comment by jdneo** [comment]
Actions to take:

1. Add it into the context menu
2. Add it into the code lens shortcuts
