### ISSUE TITLE
使用邮箱和手机号都不能登录

### ISSUE THREAD

**Issue by CuiYuXi** [jdneo/vscode-leetcode#280]
[ERROR] invalid password?

**Comment by jdneo** [comment]
See： https://github.com/jdneo/vscode-leetcode/wiki/%E7%96%91%E9%9A%BE%E8%A7%A3%E7%AD%94#thinking-%E6%97%A0%E6%B3%95%E7%99%BB%E5%BD%95

**Comment by CuiYuXi** [comment]
可以了，谢谢！
不好意思没有仔细看
