### ISSUE TITLE
Solved status is incorrect to SQL type problems.

### ISSUE THREAD

**Issue by zheeeng** [jdneo/vscode-leetcode#281]
## 🐛 Bug Report

After solving SQL problems, the problem status has no changes, it keeps unsolved, not accepted nor rejected.

![image](https://user-images.githubusercontent.com/1303154/56453958-47033d80-637c-11e9-99d2-bc9d738b2e53.png)

Problem 175, 176, 182, 196 should be marked as solved.

## Your Environment

- *os*: MacOS 10.11.6 (15G1217)
- *extension settings*:
- *nodejs version*:
- *vscode version*: Version 1.33.1 (1.33.1)
- *extension version*: 10.11.6 (15G1217)

**Comment by jdneo** [comment]
Dup with #91

**Comment by zheeeng** [comment]
@jdneo This issue seems different with #91 , we lose SQL problem status icon even after two days. Other type problems have the correct status.

**Comment by jdneo** [comment]
I see, let me take a look later
