### ISSUE TITLE
Shortcut for submitting test cases.

### ISSUE THREAD

**Issue by aqelkp** [jdneo/vscode-leetcode#288]
## 🚀 Feature Proposal
First of all, kudos to the community for making the test submission easier with single click in the editor itself. I was thinking, can we have a keyboard shortcut for submitting test cases?

## Motivation
It is a pain to move the mouse and clicking after I make smaller changes continuously and testing.

## Contribution
Define a keyboard shortcut which user will be able to change in future.

**Comment by jdneo** [comment]
@aqelkp This is achievable by Update the VS Code setting. See: https://github.com/jdneo/vscode-leetcode/wiki/FAQ#thinking-can-i-bind-the-keyboard-shortcut-to-the-extension-command

I'm closing this issue but please feel free to let us know if you have more questions.
