### ISSUE TITLE
The value of the outputFolder should be specify like `leetcode/${difficulty}`

### ISSUE THREAD

**Issue by ZakaryCode** [jdneo/vscode-leetcode#291]
## 🚀 Feature Proposal

The value of the outputFolder should be specify the relative path with the reserved words such as `leetcode/${difficulty}`, not just export problem files in accordance with reserved words or relative path.

## Motivation

Export the problem files in specify path with classification.

**Comment by jdneo** [comment]
Seems to dup with https://github.com/jdneo/vscode-leetcode/issues/151. Please let me know if your request is the same as that one.

**Comment by ZakaryCode** [comment]
Yes, it looks similar. Should I close this issue?

**Comment by jdneo** [comment]
Thank you. Then let's track this in #151
