### ISSUE TITLE
[0.14.0] Bring back supported langs in problem description

### ISSUE THREAD

**Issue by zheeeng** [jdneo/vscode-leetcode#292]
As title.

**Comment by jdneo** [comment]
Thank you for reporting. This is tracked by https://github.com/jdneo/vscode-leetcode/issues/287

**Comment by jdneo** [comment]
We have released `0.14.1` to address this issue. If you want to see the problem description in the code comments. Just open the VS Code `Preferences` search `leetcode.showCommentDescription` and turn it on.
