### ISSUE TITLE
When tried submit from command panel, it throwed [ERROR] File extension-output-#7 not exist

### ISSUE THREAD

**Issue by Leslie-Wong-H** [jdneo/vscode-leetcode#296]
## 💬 Questions and Help
When tried submit from command panel, it throwed 

[ERROR] File extension-output-#7 not exist

No idea of what  was going wrong.

**Comment by jdneo** [comment]
@Leslie-Wong-H Could you please provide more information about this issue.

Like a repro step, screenshot or a gif?

**Comment by Leslie-Wong-H** [comment]
![image](https://user-images.githubusercontent.com/27696701/56859521-cddc9980-69be-11e9-87a5-335c3ebe20a5.png)

**Comment by Leslie-Wong-H** [comment]
The submit button works well, but the command panel way fails.

**Comment by Vigilans** [comment]
I tried to submit two-sum in python3 in 3 ways:
* Execute `Leetcode: Submit to Leetcode` in command palette
* Submit by `Submit` button in codelens
* Submit by right-click `Submit to Leetcode` option.

They all worked.

Could you please paste the complete log by `Ctrl+Shift+U` and switch to `Leetcode` channel?

**Comment by Leslie-Wong-H** [comment]
Sorry to delay. Now when I repeat the same step, it throw the correct output. Quite wired. 

I remember the behavior I took before the error is that I linked my solutions to the GitHub repository, and move the solution files from the original directory .leetcode to a new sub-directory of .leetcode --  leetcode_solution_python, within a new workspace. 

Now that the  error somewhat disappears, only to hope to meet it again and track it in time.

**Comment by jdneo** [comment]
Closing it for now since the issue seems to be resolved. Please feel free to leave the comment when you meet it again.

**Comment by Leslie-Wong-H** [comment]
![image](https://user-images.githubusercontent.com/27696701/61999001-10f7f700-b0eb-11e9-9e08-1f511976944b.png)
![image](https://user-images.githubusercontent.com/27696701/61999005-2c630200-b0eb-11e9-87a8-2d17ae55a869.png)
The problem still exists every time try submit using ctrl+alt+P

**Comment by Leslie-Wong-H** [comment]
It often sticks in this situation for the first several times, and then somehow works. Really no idea of what is going on. Some cache files are not well prepared? In that case, why the way to directly click the submit button works so well?

**Comment by jdneo** [comment]
@Leslie-Wong-H Do you mean:
- directly click the submit button: worked
- Trigger the submit action in command palette: not worked

**Comment by Leslie-Wong-H** [comment]
Only after triggering the submit action in command palette several times then it works. 

Sent From Windows 10 UWP mail 

发件人: Sheng Chen
发送时间: 2019年7月28日 16:38
收件人: jdneo/vscode-leetcode
抄送: Leslie Wong; Mention
主题: Re: [jdneo/vscode-leetcode] When tried submit from command panel, itthrowed [ERROR] File extension-output-#7 not exist (#296)

@Leslie-Wong-H Do you mean:
• directly click the submit button: worked
• Trigger the submit action in command palette: not worked
