### ISSUE TITLE
Fetching Python3 is Python

### ISSUE THREAD

**Issue by shizn** [jdneo/vscode-leetcode#305]
## 🐛 Bug Report

Fetching Python3 is Python

## To Reproduce

Select Python3 as the language when start coding.
![image](https://user-images.githubusercontent.com/3619378/57184877-2dcbb800-6e77-11e9-8abb-69a024dae4e9.png)

You will get this code
![image](https://user-images.githubusercontent.com/3619378/57184882-3b813d80-6e77-11e9-840b-2a8d285ee6a2.png)

But actually if you visit the web page of this problem and select Python3
![image](https://user-images.githubusercontent.com/3619378/57184890-52c02b00-6e77-11e9-9027-a4842fdcef28.png)

## Extension Output

Paste here the LeetCode extension log from output channel.

Guidance: Press `Ctrl+Shift+U`, and toggle the channel to `LeetCode`.

## Your Environment

- *os*: macOS
- *extension settings*:
- *nodejs version*:
- *vscode version*:
- *extension version*:

**Comment by jdneo** [comment]
Hi @shizn,

This might because of the out-of-date cache of the `leetcode-cli`. You can remove the content under the folder `$HOME/.lc` and try it again.

Thanks.
