### ISSUE TITLE
remote-wsl bug

### ISSUE THREAD

**Issue by hourmor** [jdneo/vscode-leetcode#306]
## 🐛 Bug Report
当我尝试登陆时，会出现下面的提示：

[ERROR] Error: connect ECONNREFUSED 104.31.85.65:443
## Your Environment

- *os*: win 10
- *extension settings*: default
- *nodejs version*: stable version in wsl
- *vscode version*: latest vscode insider
- *extension version*: lastest

**Comment by jdneo** [comment]
Please check: https://github.com/jdneo/vscode-leetcode/wiki/%E7%96%91%E9%9A%BE%E8%A7%A3%E7%AD%94 to see if could help

**Comment by hourmor** [comment]
I successfully signed in and get the data in my stable version Vscode , and I'm sure that I did follow the same steps  in my Vscode insider as well.

**Comment by jdneo** [comment]
@hourmor Sorry I didn't quite get your point. Do you mean that you can successfully sign in but just see an error in the output? Is there any broken functionality?

**Comment by hourmor** [comment]
My fault , I should give more details. The occasion is that , I can sign in but I when it try to receive data "Successfully login as xxx
- Downloading problems" then it comes error , "[ERROR] Error: connect ECONNREFUSED " . // the reason why i can't directly post the picture is that i found it work when come back to my dormitory , i can't take screenshot about it. It's so strange , as this  plugin works on my ubuntu and win10 machine . Sorry about disturbing you , now it works on remote-wsl .

**Comment by hourmor** [comment]
My fault , I should give more details. The occasion is that , I can sign in but I when it try to receive data 

"Successfully login as xxx
Downloading problems" then it comes error , "[ERROR] Error: connect ECONNREFUSED " . 

the reason why i can't directly post the picture is that i found it work when i come back to my dormitory , i can't take screenshot about it. It's so strange , as this plugin works on my ubuntu and win10 machine  .  Before it works on remote-wsl , i try many times in classroom but fail , but it wok when i come back to dormitory surprisingly . Sorry about disturbing you .

**Comment by jdneo** [comment]
@hourmor This might be related to the network environment. Maybe you are behind the proxy in your classroom(I guess).

I'm closing it for now since the problem seems to have been resolved. Just free feel to let me know if you have any more questions.

Thanks

**Comment by hourmor** [comment]
it works well in win 10 stable version vscode in my classroom , but it didn't work in remote-wsl / vscode insider . I will check my network .
 
Thank you.

**Comment by jdneo** [comment]
It will be interesting to use the extension in WSL. I'll try it too.
