### ISSUE TITLE
Multiple choices for the  leetcode.showCommentDescription setting

### ISSUE THREAD

**Issue by miafan23** [jdneo/vscode-leetcode#310]
## 🚀 Feature Proposal

Provide multiple choices for the leetcode.showCommentDescription, like "No", "With webview", "Only in comment"

## Motivation

As discussed in #287 , most of the time, I prefer disable the description panel while the description have been displayed in the code file.

## Contribution

Please describe the solution if you'd like to submit a PR.

**Comment by jdneo** [comment]
Just Introduced a new setting `leetcode.showDescription` to control this in #519. You can have the following options:
- In Webview
- In File Comment
- Both
- None

This setting will be released in next version.
