### ISSUE TITLE
Directly click on the problem or right click the problem only has " show problem" option

### ISSUE THREAD

**Issue by YangZhao71** [jdneo/vscode-leetcode#311]

**Comment by jdneo** [comment]
Could you explain more about this issue?

**Comment by ConstanTineYoung** [comment]
> 
> 
> Could you explain more about this issue?
There's no " show top voted solution" option when I right clicked on the problem.

**Comment by jdneo** [comment]
@ConstanTineYoung  what's your extension version?

**Comment by ConstanTineYoung** [comment]
> 
> 
> @ConstanTineYoung what's your extension version?

0.12.0

**Comment by jdneo** [comment]
Please upgrade it to the newest one, which is `0.14.1` right now.

**Comment by ConstanTineYoung** [comment]
I installed it today, it shows 0.14.1 on store, but after I installed it, it shows 0.12.0 on my computer. My operating system is Windows 10 professional.

**Comment by jdneo** [comment]
Please make sure your environment has met the requirement: https://github.com/jdneo/vscode-leetcode#requirements

**Comment by jdneo** [comment]
Closing it since it's inactive for a long time.
