### ISSUE TITLE
can't login in 

### ISSUE THREAD

**Issue by louiewh** [jdneo/vscode-leetcode#312]
## To Reproduce

Steps to reproduce the behavior.

## Extension Output

Paste here the LeetCode extension log from output channel.

Guidance: Press `Ctrl+Shift+U`, and toggle the channel to `LeetCode`.

## Your Environment

- *os*:  linux
- *extension settings*:
- *nodejs version*:v10.15.3
- *vscode version*:1.3.1
- *extension version*:

**Comment by louiewh** [comment]
login: pass: - Signing in leetcode.com
[ERROR] Error: tunneling socket could not be established, cause=write EPROTO 139906267883328:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:252:

**Comment by jdneo** [comment]
Please check: https://github.com/jdneo/vscode-leetcode/wiki/Troubleshooting

**Comment by hwm18** [comment]
Can't login VS code leetcode.com, the leetcode plugin version is 0.15.7. I can use the user name and password login leetcode.com in Chrome.
![image](https://user-images.githubusercontent.com/7017002/70305136-7d30e880-17b8-11ea-980a-d125556ca1d0.png)
