### ISSUE TITLE
Failed to show the problem. Please open the output channel for details.

### ISSUE THREAD

**Issue by JJJAMM** [jdneo/vscode-leetcode#320]
Failed to show the problem. Please open the output channel for details.
LeetCode CN

when open the question 141 and 142, and When click “Code Now”, the system prompts this error and cannot display the code edit box. However, other problems do not have this error for the time being.

**Comment by jdneo** [comment]
Is there any output in the output channel?

**Comment by lightingtime** [comment]
i have the same problem.
the output 
v11.9.0
 Active  Name               Version         Desc
----------------------------------------------------------------------------------------------------
   √     solution.discuss   2019.02.03      Plugin to fetch most voted solution in discussions.
   √     company            2017.12.18      Plugin to query by company for free user.
   √     cache              default         Plugin to provide local cache.
   √     retry              default         Plugin to retry last failed request if autologin.enable is on.
   ×     leetcode.cn        2018.11.25      Plugin to talk with leetcode-cn APIs.
   √     leetcode           default         Plugin to talk with leetcode APIs.
 Active  Name               Version         Desc
----------------------------------------------------------------------------------------------------
   √     solution.discuss   2019.02.03      Plugin to fetch most voted solution in discussions.
   √     company            2017.12.18      Plugin to query by company for free user.
   √     cache              default         Plugin to provide local cache.
   √     retry              default         Plugin to retry last failed request if autologin.enable is on.
   ×     leetcode.cn        2018.11.25      Plugin to talk with leetcode-cn APIs.
   √     leetcode           default         Plugin to talk with leetcode APIs.
 Active  Name               Version         Desc
----------------------------------------------------------------------------------------------------
   √     solution.discuss   2019.02.03      Plugin to fetch most voted solution in discussions.
   √     company            2017.12.18      Plugin to query by company for free user.
   √     cache              default         Plugin to provide local cache.
   √     retry              default         Plugin to retry last failed request if autologin.enable is on.
   √     leetcode.cn        2018.11.25      Plugin to talk with leetcode-cn APIs.
   √     leetcode           default         Plugin to talk with leetcode APIs.
 Active  Name               Version         Desc
----------------------------------------------------------------------------------------------------
   √     solution.discuss   2019.02.03      Plugin to fetch most voted solution in discussions.
   √     company            2017.12.18      Plugin to query by company for free user.
   √     cache              default         Plugin to provide local cache.
   √     retry              default         Plugin to retry last failed request if autologin.enable is on.
   ×     leetcode.cn        2018.11.25      Plugin to talk with leetcode-cn APIs.
   √     leetcode           default         Plugin to talk with leetcode APIs.
 Premium   User                 Host
------------------------------------------------------------
    ×      lightingtime         https://leetcode.com
the left is my leetcode problem so i don't copy here

**Comment by jdneo** [comment]
@lightingtime what if you remove the cache folder `$HOME/.lc/` entirely. And try it again?

**Comment by lightingtime** [comment]
i use windows 10 ,so i can't find folder $HOME/.lc/ entirely , can you tell me more about it ?

**Comment by jdneo** [comment]
@lightingtime you can Call `echo %userprofile%` in the `cmd` to get your home path

**Comment by lightingtime** [comment]
I deleted all the files under the .lc folder, and the problem still have.

**Comment by jdneo** [comment]
Problem 141 and 142?

**Comment by lightingtime** [comment]
i think it is not same

**Comment by jdneo** [comment]
Please provide more information to help diagnostic. So far I cannot repro it on my side. The information could include:

1. Endpoint being used
2. problem number which cannot show
3. If there is any suspicious output in the output channel
4. If there is any output in the console (You can check it by `Help` > `Toggle Developer Tools` > `Console`)

**Comment by lightingtime** [comment]
1.leetcode
2.all the problem
3.output channel is same as i described like above.
4.i have two error show here:
1)workbench.main.js:238 [Extension Host] (node:10864) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
t.log @ workbench.main.js:238
2)workbench.main.js:2365 Failed to show the problem. Please open the output channel for details.

**Comment by jdneo** [comment]
@lightingtime Thank you for the information. Do you have any customized `leetcode` settings?

**Comment by lightingtime** [comment]
<img width="513" alt="41f977e5f66a31623d7120837f9fe64" src="https://user-images.githubusercontent.com/13469581/58686549-b6277500-83b1-11e9-9c1f-935e1049de17.png">
<img width="391" alt="09192f69d49e0639327e62aecea37ad" src="https://user-images.githubusercontent.com/13469581/58686570-c2abcd80-83b1-11e9-8ada-8f53c6cd2b7c.png">
<img width="377" alt="592ff4090e34d6ab42ac275f86eab7c" src="https://user-images.githubusercontent.com/13469581/58686581-c6d7eb00-83b1-11e9-81f1-bc078d767afb.png">
 <img width="428" alt="3e03113c4bd8ec2d23a67d167725fac" src="https://user-images.githubusercontent.com/13469581/58686619-dc4d1500-83b1-11e9-95bc-f948f1bd3d69.png">
<img width="300" alt="5bc1090af395ee2cf4c312c655d88a4" src="https://user-images.githubusercontent.com/13469581/58686650-f129a880-83b1-11e9-9252-4177da8fefba.png">

**Comment by jdneo** [comment]
The problem is the `outputFolder` setting. As the setting description says: Specify the **relative** path to save the problem files. There is no need to provide an absolute path here.

Change your setting to `"leetcode.outputFolder": "${difficulty}"` should resolve your problem.

**Comment by lightingtime** [comment]
<img width="444" alt="eb77029f02ff642c1d4bc19e343951b" src="https://user-images.githubusercontent.com/13469581/58686998-ede2ec80-83b2-11e9-8845-8e2991569206.png">
like this? i restart vscode but i still have the problem, i think the problem is not the outputFolder setting. i used my setting before.

**Comment by jdneo** [comment]
No, I write `"leetcode.outputFolder": "${difficulty}"` is because all the settings are actually json formatted. In your case, just enter `${difficulty}` in the input box should be fine

**Comment by lightingtime** [comment]
emmm, i still have the problem

<img width="414" alt="34aaca1ba28d2cea82f5bee33cb61be" src="https://user-images.githubusercontent.com/13469581/58688240-7fa02900-83b6-11e9-895d-175360f8eed3.png">

**Comment by jdneo** [comment]
What's your setting now? You can check them by clicking the `{}` button
![image](https://user-images.githubusercontent.com/6193897/58688353-c42bc480-83b6-11e9-9de4-628bb8554d19.png)


All the leetcode related settings are starting with `leetcode`

**Comment by lightingtime** [comment]
<img width="633" alt="13ad1829bdd763a1ca42d5267a38e8b" src="https://user-images.githubusercontent.com/13469581/58688461-1240c800-83b7-11e9-922d-41f6cc7bd2a5.png">

**Comment by jdneo** [comment]
No need to escape the `"`. Just 

![image](https://user-images.githubusercontent.com/6193897/58688553-651a7f80-83b7-11e9-9da8-79f5a26bba4b.png)

Or

![image](https://user-images.githubusercontent.com/6193897/58688572-6cda2400-83b7-11e9-8774-80a0dc6d5690.png)

**Comment by lightingtime** [comment]
emmmmm. it does not work.

**Comment by lightingtime** [comment]
...it works ! but i still confused that the previous settings were working.

**Comment by jdneo** [comment]
Follow-up: https://github.com/jdneo/vscode-leetcode/issues/160 should be resolved ASAP to avoid confusion.
