### ISSUE TITLE
leetcode.outputFolder not work

### ISSUE THREAD

**Issue by jjeejj** [jdneo/vscode-leetcode#321]
set `"leetcode.outputFolder": "E:/study/leetcode/${difficulty}/${tag}/${language}",` is not work

 it generate file  in vscode currently open workspace 
![image](https://user-images.githubusercontent.com/15176971/57752384-95a5bc80-771b-11e9-9ed8-7dfaea26869b.png)

version: 1.33.1 (user setup)
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 6.1.7601

LeetCode extend is latest version

**Comment by jdneo** [comment]
Hi @jjeejj,

The setting `leetcode.outputFolder` is to set the relative path, not an absolute path. See: https://github.com/jdneo/vscode-leetcode#settings

To solve your problem, we have several related tracking issues here:
- Let the user set the workspace folder to save the file: https://github.com/jdneo/vscode-leetcode/issues/130
- Support interpolation in output folder settings: https://github.com/jdneo/vscode-leetcode/issues/151

It could be great if you would like to give it a shot for contributing them. 😄 

BYW, I'm closing this issue since it's somehow duplicated with existing issues.

**Comment by jjeejj** [comment]
@jjeejj 
i read the related source code
```js
   const leetCodeConfig: vscode.WorkspaceConfiguration = vscode.workspace.getConfiguration("leetcode");
   let outDir: string = await selectWorkspaceFolder();
   let relativePath: string = (leetCodeConfig.get<string>("outputFolder", "")).trim();
   const matchResult: RegExpMatchArray \| null = relativePath.match(/\$\{(.*?)\}/);
   if (matchResult) {
   const resolvedPath: string \| undefined = await resolveRelativePath(matchResult[1].toLocaleLowerCase(), node, language);
   if (!resolvedPath) {
   leetCodeChannel.appendLine("Showing problem canceled by user.");
   return;
   }
   relativePath = resolvedPath;
   }
   outDir = path.join(outDir, relativePath);
```
the config `leetcode.outputFolder` is relative current workspaceFolder

If the open workspace is inconsistent with the previous one, leetcode.outputFolder relative path  corresponding  actual path is different.

Why not? 
if  the `leetcode.outputFolder` config is absolutely path ,  use this path directly 
if  the `leetcode.outputFolder` config is relative path, join currentWorkspaceFolder path

**Comment by jdneo** [comment]
Just as I have said before. If there is a setting to specify the workspace path for the leetcode files (That's what #130 talks about), then it will be confusing if `leetcode.outputFolder` can set to an absolute path, since there will be some conflicts there.

**Comment by jjeejj** [comment]
I don't think so.
I don't think `the leetcode outputFolder` and `current workspaceFolder`  have anything to do with it.

because i can open one folder  in any path , use leetcode extension
if i do it , it will generator many  leetcode code file in different workspaceFolder
Hard to maintain local leetcode code

**Comment by jdneo** [comment]
The extension can detect if the path is opened in the current workspace. If not, prompt the user to open it or add it into the current workspace

**Comment by jjeejj** [comment]
that menas ，I can't use this feature right now ?

I hope the config `leetcode.outputFolder` support relative path and absolutely path
because I often open different projects using leetcode extension at different times

> Now vscode support multiple workspace , this feature can avoid conflicts, have a try
