### ISSUE TITLE
Error: The environment doesn't meet requirements.

### ISSUE THREAD

**Issue by pgr2015** [jdneo/vscode-leetcode#322]
Hi, I am facing setting problem, leetcode.XXX are all not found. 

os: windows 10
vscode: 1.33.1
node.js: 10.15.3

I have set node.js path as "A:\Program Files\nodejs\node.exe", where is the absolute install path.
When I give command as node -v in terminal, I can get the correct version information, so I guess the node.js is installed properly. 

I am new to vscode settings, so could someone help me?
Thanks in advance!

**Comment by jdneo** [comment]
@pgr2015 Since you have already put node executable into your path, you can just set `leetcode.nodePath` to its default value, which is `node`.

Please let me know if this can help solve your problem. thanks

**Comment by pgr2015** [comment]
@jdneo thank you for your very quick reply, but I still have the problem.

vscode can now find node.js but continue giving error like  leetcode.XXX not found.
I guess, I just don't set up correctly. Any idea?

Thank you very much!

**Comment by jdneo** [comment]
It's hard for me to say what's happening according to the current information. Are you sure the VS Code session has `node` in its path? what if you close all the VS Code instances and start it again? Do not start if from the file explorer because the explorer session may not have node in its path.

**Comment by pgr2015** [comment]
@jdneo thank you so much for your advice, I just reboot my computer and everything starts to work properly.  So you are you are right, all I need to do is just refresh vscode completely.

Thank you!

**Comment by Indomite** [comment]
Error: ' node: command not found Error: The environment doesn't meet requirements. '
When I installed the leetcode plugin in VS code, he reported this error
The solution is to restart the computer, I think it is probably because the environment has not been loaded yet.

**Comment by bi-an** [comment]
I found that for me this was caused by not having all the VSCode SSH extensions enabled. When I enabled those extensions, all the issues like "nodejs not found" or "cannot log into leetcode" went away:
1. Remote Explorer
3. Remote - SSH
4. Remote - SSH: Editing Configuration Files
