### ISSUE TITLE
Can't submit or test my answers ,the console write the [ERROR] Error: read ECONNRESET

### ISSUE THREAD

**Issue by chonley** [jdneo/vscode-leetcode#324]
[ERROR] Error: read ECONNRESET

**Comment by jdneo** [comment]
Please make sure your network environment is ok. If you are behind a proxy, please set the [related setting accordingly](https://github.com/jdneo/vscode-leetcode/wiki/Troubleshooting#thinking-cannot-sign-in).

**Comment by chonley** [comment]
ok, it's work,thanks;

**Comment by eleminsoda** [comment]
I can log in onto leetcode.com, but can't download the problems, and the console log out the same error: [ERROR] Error: read ECONNRESET
But I don't use a proxy. What't the problem?
