### ISSUE TITLE
登陆时是不是描述错误

### ISSUE THREAD

**Issue by asurance** [jdneo/vscode-leetcode#325]
Before you submit an question we recommend you to check out the [DOCUMENT](https://github.com/jdneo/vscode-leetcode/blob/master/README.md) first.

You can also find more information in:
- [TROUBLESHOOTING](https://github.com/jdneo/vscode-leetcode/wiki/Troubleshooting)
- [FAQ](https://github.com/jdneo/vscode-leetcode/wiki/FAQ)

## 💬 Questions and Help

Please outline the questions.
提示输入user name ，但是实际应该输入的是邮箱

**Comment by jdneo** [comment]
Thanks. A better description should be `Username or E-mail`
![image](https://user-images.githubusercontent.com/6193897/57903102-28bb2f80-789f-11e9-92cf-ed9b4b645edf.png)
