### ISSUE TITLE
Error: Cannot find module 'underscore'

### ISSUE THREAD

**Issue by chenyuhu** [jdneo/vscode-leetcode#330]
运行报错，查看不了题目，提示当前没有课提供的视图数据的提供来源注册

**Comment by jdneo** [comment]
@zhouchenzc0824 Could you please try to remove the entire directory: `/Users/<your user name>/.vscode/extensions/shengchen.vscode-leetcode-0.xx.x/` and reinstall the extension again?

> Assume you are windows user

**Comment by chenyuhu** [comment]
Thank you very much, this is feasible.

**Comment by jdneo** [comment]
Close the issue since it seems having been resolved.
