### ISSUE TITLE
ico on side bar disappeared after vscode updated

### ISSUE THREAD

**Issue by Wanger-SJTU** [jdneo/vscode-leetcode#331]
## 🐛 Bug Report

after updating the vscode to 1.34.0, the ico became transparent.

## Your Environment

- *os*: x64 10.0.17134
- *extension settings*:
- *nodejs version*:10.2.0
- *vscode version*:1.34.0
- *extension version*: 0.14.3

**Comment by jdneo** [comment]
Could not repro on my side
![image](https://user-images.githubusercontent.com/6193897/58010049-392f0c80-7b22-11e9-8228-7ab0ccc637c5.png)

Have you tried restarting your VS Code?

**Comment by Wanger-SJTU** [comment]
still nothing to show. 
![image](https://user-images.githubusercontent.com/35162184/58018215-c8ddb680-7b34-11e9-975f-5b7873ca01fe.png)

And buttons got no response
![image](https://user-images.githubusercontent.com/35162184/58018279-f88cbe80-7b34-11e9-9193-0b97fa32c162.png)

**Comment by jdneo** [comment]
Have you tried this? https://github.com/jdneo/vscode-leetcode/wiki/%E7%96%91%E9%9A%BE%E8%A7%A3%E7%AD%94#thinking-%E6%8F%90%E7%A4%BA%E9%94%99%E8%AF%AF-command-leetcodexxx-not-found

**Comment by Wanger-SJTU** [comment]
Tried, but still not work

**Comment by Wanger-SJTU** [comment]
after reinstall, problem solved
