### ISSUE TITLE
the number of problems available is less than on leetcode website

### ISSUE THREAD

**Issue by holajoyce** [jdneo/vscode-leetcode#332]
## To Reproduce

I clicked on the 'all' tab of the tree, and I see that the last problem is 1031, but in leetcode.com there are more problems after 1031.

## Extension Output

Paste here the LeetCode extension log from output channel.

Guidance: Press `Ctrl+Shift+U`, and toggle the channel to `LeetCode`.

## Your Environment

- *os*: macOS mojave 10.14.3
- *extension settings*:
- *nodejs version*:
- *vscode version*: latest
- *extension version*:

**Comment by jdneo** [comment]
@holajoyce Could you please try the solution @oneyuan provided?
