### ISSUE TITLE
Make it possible to customize the shortcuts in editor

### ISSUE THREAD

**Issue by Leslie-Wong-H** [jdneo/vscode-leetcode#335]
Now the latest version of vscode-leetcode adds solution shortcut to the answer file window, yet does not provide a setting to hide the solution shortcut. In my own experience, the solution shortcut is somehow disturbing, forcing me to click it more or less. That's really not good when I try to solve the problem by my own. 

I look through the leetcode settings, only to find Leetcode: Enable Shortcuts ( Show the submit and test shortcuts in editor or not. ) . Hence, It 's necessary to add setting -- Leetcode: Hide Solution Shortcut.

**Comment by jdneo** [comment]
Thank you for the feedback. Let me think about if we can have a way to let the user customize the shortcuts by his own. Like, make the configuration become an array: 

```
leetcode.shortcuts: [
    "test",
    "submit",
]
```

something like that.

Feel free to let me know your thoughts.

**Comment by Leslie-Wong-H** [comment]
> Thank you for the feedback. Let me think about if we can have a way to let the user customize the shortcuts by his own. Like, make the configuration become an array:
> leetcode.shortcuts: [
>     "test",
>     "submit",
> ]
> 
> something like that.
> Feel free to let me know your thoughts.

Sounds like a reasonable proposal.

**Comment by jdneo** [comment]
I'll start working on this these days.

> Note: After adopting this setting, the `leetcode.enableShortcuts` will be deprecated. If you want to disable the shortcuts, just set `leetcode.shortcuts` to `[]`
