### ISSUE TITLE
Enable line break in "Example" section of the LeetCode preview pages

### ISSUE THREAD

**Issue by ysyshtc** [jdneo/vscode-leetcode#342]
## 🚀 Feature Proposal

For some LeetCode problems, such as 190. Reverse Bits, due to the long explanation in "example" section, the rendered webpage is not so user friendly currently. It seems reasonable to have line break there or at least make an enable switch.

## Motivation

Improve the user experience of preview page.

**Comment by jdneo** [comment]
My solution is to add 

```css
code { 
    white-space: pre-wrap; 
}
``` 
into the stylesheet. Works fine so far.

Does anyone know if there is any problem which has code snippets in its description?

**Comment by ysyshtc** [comment]
@jdneo any update?

**Comment by jdneo** [comment]
@ysyshtc The solution I provided works fine. But I want to know if there is any problem which contains code snippets in its description to see the style.

It would be great if you can help me to confirm if there is any that kind of problem.
