### ISSUE TITLE
"Invalid input to fetch the preview data"

### ISSUE THREAD

**Issue by pizzacrystal** [jdneo/vscode-leetcode#344]
## 🐛 Bug Report

after choosing a tag for certain problem, this message pops up every time.

## To Reproduce

sign in, click search, select a problem, set tag, there it is.

## Expected behavior

once upon a time, description of problem can be downloaded automatically and correctly, but not now.

## Extension Output

Paste here the LeetCode extension log from output channel.

Guidance: Press `Ctrl+Shift+U`, and toggle the channel to `LeetCode`.

## Your Environment

- Windows 10 latest, VSCode latest, leetcode ex latest
- .outputfolder ${tags}

**Comment by jdneo** [comment]
Fixed in #345, I'll release this fix in `0.15.1`. The due date should before the end of next week.
