### ISSUE TITLE
插件启动时报错

### ISSUE THREAD

**Issue by blackdogTT** [jdneo/vscode-leetcode#348]
https://user-images.githubusercontent.com/23448498/59576837-ac14ae80-90f3-11e9-9bc7-15ac1b34b61f.png

**Comment by jdneo** [comment]
Could you please try to remove the cached data and try it again? The cached data is located at `$HOME/.lc/`.

**Comment by cnyy7** [comment]
同样的问题

通过删除`.vscode\extensions\shengchen.vscode-leetcode-0.15.1`并重装插件解决了

--------

Same question

Solved by removing `.vscode\extensions\shengchen.vscode-leetcode-0.15.1` and reinstalling the plugin
