### ISSUE TITLE
[ERROR] Not supported language

### ISSUE THREAD

**Issue by Zhuoli** [jdneo/vscode-leetcode#352]
## 🐛 Bug Report
Start from this afternoon, I keeps getting this error from all of my PCs and Mac.
Error: Command "node "C:\Users\XXX\.vscode\extensions\shengchen.vscode-leetcode-0.15.1\node_modules\vsc-leetcode-cli\bin\leetcode",show,193,-c,-l,csharp" failed with exit code "0". Please open the output channel for details.

## To Reproduce

Click on "Code now".

## Expected behavior

Error pops up when click on "Code Now",  and all kinds of languages except "Bash" is shown as not supported.   

## Extension Output

Error: Command "node "C:\Users\XXX\.vscode\extensions\shengchen.vscode-leetcode-0.15.1\node_modules\vsc-leetcode-cli\bin\leetcode",show,193,-c,-l,csharp" failed with exit code "0". Please open the output channel for details.

[ERROR] Not supported language "csharp"
[WARN] Supported languages:  bash 

Guidance: Press `Ctrl+Shift+U`, and toggle the channel to `LeetCode`.

## Your Environment

- *os*: Issue exist on both Windows and MacOS
- *extension settings*:
- *nodejs version*: v10.15.3
- *vscode version*: 1.35.1
- *extension version*:

**Comment by Vigilans** [comment]
The problem 193 is `[Valid Phone Number](https://leetcode.com/problems/valid-phone-numbers/)`, and it indeed only supports bash:
![image](https://user-images.githubusercontent.com/20227484/59827696-e8eada80-936b-11e9-9294-850a13d2d425.png)

What is the original problem you want to solve?

**Comment by jdneo** [comment]
@Zhuoli If you want to solve this problem in `bash`, you can reset the setting `leetcode.defaultLanguage`.

**Comment by littlebeandog** [comment]
1

**Comment by Zhuoli** [comment]
Thanks for the explanation, later I realized that not all the problems support C# language; does that mean for problem 193 it only support Bash? And do you have plan to support C# for all the leetcode problems?

**Comment by jdneo** [comment]
Hi @Zhuoli, 

You can see that the LeetCode official site only support bash for Problem No. 193. 
![image](https://user-images.githubusercontent.com/6193897/59889079-306d7700-93fd-11e9-8357-7d9506e06385.png)

The language support scope for the extension is just the same as the website. So I guess it's actually a question that the LeetCode official team could give an answer.

Since it's not an issue actually, I'm closing it for now.

Thanks.
