### ISSUE TITLE
Favorite List can't sync

### ISSUE THREAD

**Issue by buting2014** [jdneo/vscode-leetcode#355]
add favorite explore in leetcode website ,but  doesn't sync to plugins

**Comment by jdneo** [comment]
@buting2014 Could you please try to re-login to see if this could help?

**Comment by buting2014** [comment]
@jdneo emm, just re-login， but  not work ...

**Comment by jdneo** [comment]
Cannot repro on my side, please make sure the endpoint is correct.

**Comment by loststar** [comment]
I have the same problem.

**Comment by jdneo** [comment]
For anyone who encounters the same issue. Please feel free to comment here. It will be great if you can attach more information to help me understand the problem. Like a gif animation would be great.

**Comment by Feeco-Li** [comment]
I guess, its because it does not work if you add to favorite list from your web account.

however, if you start it in your vscode, it works, the starred problem will be listed in favorite section.
