### ISSUE TITLE
outputFolder可以支持绝对路径么

### ISSUE THREAD

**Issue by qinchenguang** [jdneo/vscode-leetcode#357]
## 🚀 Feature Proposal

1.项目较多。打开leetcode会污染工作空间。
2.本地的leetcode难以维护
3.希望outputFolder支持绝对路径

## Motivation

1.由于业务场景复杂。项目多。想在琐碎的时间中刷题。
2.目前的做法是 在相对路径中增加 超过最大文件夹深度的../ 来使得跳转来

## Contribution

Please describe the solution if you'd like to submit a PR.

**Comment by jdneo** [comment]
Guess your problem should related with this issue: https://github.com/jdneo/vscode-leetcode/issues/130

**Comment by qinchenguang** [comment]
@jdneo sure! I close this issues
