### ISSUE TITLE
Failed to resolve the Node executable path when it contains spaces

### ISSUE THREAD

**Issue by cliffrunner** [jdneo/vscode-leetcode#362]
I installed node.js (v10.16.0) and the latest version of leetcode (0.15), when I tried to click any button on top it kept saying "command xxx not found". I read through the bug reports and it seems similar to an old letter case issue but should already be fixed in v0.13.

Please help. Thank you.

**Comment by jdneo** [comment]
Could you provide the output in the `LeetCode` output channel?

**Comment by cliffrunner** [comment]
`'C:\Program' is not recognized as an internal or external command,
operable program or batch file.
Error: The environment doesn't meet requirements`

Thanks.

**Comment by jdneo** [comment]
I see. Thank you for the information.

**Comment by jdneo** [comment]
@cliffrunner

As a workaround, there is no need to set the setting `nodePath`. Just make sure the `Node.js` executable is in the `Path` environment variable. And reset the `nodePath` to the default value `node`.

**Comment by cliffrunner** [comment]
Thanks a lot for the help. I added the executable to both system and user path but the problem still persists. Now the output is: `Error: The Node.js executable does not exist on path`

**Comment by jdneo** [comment]
@cliffrunner

- Can you run Node.js if simply enter `node` in your `cmd`?
- If yes, Please make sure all the VS Code windows are closed, and then start it. (Don't start it by right-clicking from the file explorer)
- If the step two is not working for you, log out from your OS and re-login.
