### ISSUE TITLE
当我在编辑键盘快捷键的时候，when字段应该填写什么呢

### ISSUE THREAD

**Issue by Gwzlchn** [jdneo/vscode-leetcode#369]
比方说我现在有一个·提交的快捷键，但在任何时间都可用，可不可以仅在leetcode代码页面生效的时候再可用呢。谢谢解答。
{
        "key": "ctrl+shift+q",
        "command": "leetcode.submitSolution",
        "when": "editorTextFocus"
    },

**Comment by jdneo** [comment]
I'm afraid it's not achievable so far, considering the current supported when clause. More information about available when clause can be found here: https://code.visualstudio.com/docs/getstarted/keybindings#_when-clause-contexts.
