### ISSUE TITLE
Some way to get back a random question 

### ISSUE THREAD

**Issue by huchenme** [jdneo/vscode-leetcode#374]
## 🚀 Feature Proposal

It will be fun to get back a random question by clicking a button. So you could just work on one randomly assigned question every day.

## Motivation

To form a habit of working on algorithms every day, one questions a day. It will be good if you could keep refreshing your algorithm skills daily, but not spend too much mental energy deciding which question to work on.

**Comment by jdneo** [comment]
Thanks, that's a valid request. duplicated with #263
