### ISSUE TITLE
Command ""C:\Program Files\nodejs\node.exe" "C:\Users\。。。\.vscode\extensions\shengchen.vscode-leetcode-0.15.2\node_modules\vsc-leetcode-cli\bin\leetcode",plugin,-i,company" failed with exit code "1"

### ISSUE THREAD

**Issue by Yihemu** [jdneo/vscode-leetcode#375]
## To Reproduce

Steps to reproduce the behavior.

## Extension Output

Paste here the LeetCode extension log from output channel.

Guidance: Press `Ctrl+Shift+U`, and toggle the channel to `LeetCode`.

## Your Environment

- *os*:
- *extension settings*:
- *nodejs version*:
- *vscode version*:
- *extension version*:

**Comment by jdneo** [comment]
Is your problem solved?

**Comment by Yihemu** [comment]
> Is your problem solved?

nope

**Comment by jdneo** [comment]
Anything in the LeetCode output channel?

**Comment by Yihemu** [comment]
> Anything in the LeetCode output channel?
![image](https://user-images.githubusercontent.com/43208747/62004254-2e61ab00-b155-11e9-978b-6cc9e0894967.png)

**Comment by jdneo** [comment]
Please follow this step and try again:
- Uninstall the extension
- Remove the cached folder: `C:\Users\Aragaki YUI\.vscode\extensions\shengchen.vscode-leetcode-xx\`
- Reinstall the extension.

**Comment by Yihemu** [comment]
> Please follow this step and try again:
> 
> * Uninstall the extension
> * Remove the cached folder: `C:\Users\Aragaki YUI\.vscode\extensions\shengchen.vscode-leetcode-xx\`
> * Reinstall the extension.

no use

**Comment by jdneo** [comment]
Remove the cache files? The folder is `$home/.lc/`

**Comment by Yihemu** [comment]
its work！！thank you

**Comment by zhangwhitemouse** [comment]
win10、nodejs 10.16.3
I clicked show problem then happen
Error: Command "node "c:\Users\users\.vscode\extensions\shengchen.vscode-leetcode-0.15.4\node_modules\vsc-leetcode-cli\bin\leetcode",show,7,-c,-l,python3" failed with exit code "0". Please open the output channel for details.

**Comment by jdneo** [comment]
@zhangwhitemouse See: https://github.com/jdneo/vscode-leetcode/issues/430

**Comment by rafee** [comment]
This problem is reintroduced with latest commit. Get the error as follows:
`[ERROR] Not supported language "typescript"`

**Comment by daojinjin** [comment]
> Remove the cache files? The folder is `$home/.lc/`
how to find this file path?

**Comment by JinghuaOriental** [comment]
If the leetcode plugin output shows "Node.js v18.18.2[ERROR] Error: connect ETIMEDOUT ...", maybe you can try to reinstall node to fix the problem, and it works for me.
