### ISSUE TITLE
[ERROR] Error: self signed certificate in certificate chain

### ISSUE THREAD

**Issue by mrjihai** [jdneo/vscode-leetcode#381]
## 🐛 Bug ### Report

[ERROR] You are not login yet?
login: pass: - Signing in leetcode.com
[ERROR] Error: self signed certificate in certificate chain
 
- *os*: mac
- *extension settings*:default 
- *nodejs version*:V10.16.0
- *vscode version*:latest

**Comment by jdneo** [comment]
Dup with #370.
