### ISSUE TITLE
some item only support only language,like sql if i selcet golang before,it will get Error

### ISSUE THREAD

**Issue by labulaka521** [jdneo/vscode-leetcode#382]
## 🐛 Bug Report

Error: Command "node "/Users/xxx/.vscode/extensions/shengchen.vscode-leetcode-0.15.2/node_modules/vsc-leetcode-cli/bin/leetcode",show,193,-cx,-l,golang" failed with exit code "0". Please open the output channel for details.
## To Reproduce

Steps to reproduce the behavior.

## Extension Output

Paste here the LeetCode extension log from output channel.

Guidance: Press `Ctrl+Shift+U`, and toggle the channel to `LeetCode`.

## Your Environment

- *os*:
- *extension settings*:
- *nodejs version*:
- *vscode version*:
- *extension version*:

**Comment by jdneo** [comment]
Thank you for reporting the issue. This problem could be resolved if we resolve #234.
