### ISSUE TITLE
How to remove the comment like this?

### ISSUE THREAD

**Issue by EricTao66** [jdneo/vscode-leetcode#383]
```cpp
/*
 * @lc app=leetcode.cn id=4 lang=cpp
 *
 * [4] 寻找两个有序数组的中位数
 */
```
A comment like this is automatically generated in front of a new file whenever I create it.
Hope add a setting to remove it.

**Comment by jdneo** [comment]
Hi @EricTao66,

This comment is needed to provide metadata of the program.

```
@lc app=leetcode.cn id=4 lang=cpp
```

Without it, the extension could not know the problem id of the file, thus might fail to submit/test it.

I think this request will not be in the roadmap of the extension so far. But will revisit it if we figure out a better way to get the metadata of the file. Hope you can understand.

Thanks,
