### ISSUE TITLE
Submission result not rendered property

### ISSUE THREAD

**Issue by jasonsun0310** [jdneo/vscode-leetcode#384]
The stdout message does not print line break properly. This causes the debug print info hard to read. I use the latest version of vscode and leetcode-plugin. 
![Screen Shot 2019-08-05 at 1 22 50 AM](https://user-images.githubusercontent.com/22034141/62440857-e4ae2d00-b71f-11e9-805d-eabc448317fb.jpg)

**Comment by jdneo** [comment]
Could you provide the problem number?
