### ISSUE TITLE
Icon disappear after VSCode update to 1.37.0

### ISSUE THREAD

**Issue by ATRiiX** [jdneo/vscode-leetcode#387]
I'm using the extention with Node environment in WSL:Debian of Win10, and it worked well for a long time until VSCode updated to version 1.37.0 today. The icons of the buttons disappear, while the buttons can still work functionally.

![Snipaste](https://user-images.githubusercontent.com/14856798/62751752-74910580-ba97-11e9-87b4-087a5c4a4b85.png)
![Snipaste](https://user-images.githubusercontent.com/14856798/62751759-7bb81380-ba97-11e9-9afe-283f3ede32c1.png)
![image](https://user-images.githubusercontent.com/14856798/62751768-81adf480-ba97-11e9-8bc6-faa979ca2c1a.png)
![Snipaste](https://user-images.githubusercontent.com/14856798/62751762-7d81d700-ba97-11e9-9a4c-5e8fa07946cd.png)

The Node version of WSL:Debian is 12.7.0

**Comment by ATRiiX** [comment]
fixed after several reboots of the operating system..

**Comment by jdneo** [comment]
Seems sometime it may happen for some unknown reason. If anyone knows the root cause please let me know.
