### ISSUE TITLE
Actual stdout (console.log) layout enhancement: to display content in multi-line mode.

### ISSUE THREAD

**Issue by karlli1976** [jdneo/vscode-leetcode#388]
## 🚀 Feature Proposal

Actual stdout (console.log) layout enhancement: to display content in multi-line mode.

## Motivation

console.log output all in one line, not friendly to program debug. 

e.g., in vs description win:

    stdout: 'l1={"val":1,"next":{"val":8,"next":null}}\nl2={"val":0,"next":null}\nadv=0\n-----\n

while in leetcode page:

    l1={"val":1,"next":{"val":8,"next":null}}
    l2={"val":0,"next":null}
    adv=0
    -----

## Contribution

1. stdout support multi-line mode;
2. convert \n into a new line.

**Comment by jdneo** [comment]
Can you provide the number of the problem?

**Comment by howhowcan** [comment]
@jdneo If you mean you want to know which leetcode problems have this issue, actually every problems have if you output something containing more than one line.

**Comment by jdneo** [comment]
@howhowcan Just give me one problem number is fine. I need one to repro and understand the issue.

BTW, PR is also welcome!

**Comment by howhowcan** [comment]
@jdneo Problem 1, for example :
![未命名](https://user-images.githubusercontent.com/39648162/63491667-6c4eb680-c4ea-11e9-87af-b5edfbd900a8.png)

(Of course the problem number is arbitrary)

**Comment by jdneo** [comment]
It seems that this issue only occurs in `test`, right?

**Comment by howhowcan** [comment]
It seems like there is the same issue for 'testcase' in submit.
![未命名](https://user-images.githubusercontent.com/39648162/63496860-36fb9600-c4f5-11e9-923e-8cc789359b08.png)
