### ISSUE TITLE
[ERROR] Error: unable to verify the first certificate

### ISSUE THREAD

**Issue by jianlong-yuan** [jdneo/vscode-leetcode#391]
When sigining in, i set proxy. But i get an error [ERROR] Error: unable to verify the first certificate

**Comment by jdneo** [comment]
Guess dup with #370

**Comment by jianlong-yuan** [comment]
So, do you have idea to solve this?

**Comment by jdneo** [comment]
So far I have no idea about this kind of issue. Mostly it's related with the network issue, like the user is behind a proxy or something like that...

**Comment by jianlong-yuan** [comment]
Actually, i am also behind the proxy. But i have set proxy, and get the same error

**Comment by jdneo** [comment]
Do you have the same error if you run the [LeetCode CLI](https://github.com/skygragon/leetcode-cli) directly?

**Comment by jianlong-yuan** [comment]
Sorry, i do not try that. Is it necessary？

**Comment by jdneo** [comment]
The extension use the LeetCode CLI as the backend. If this issue could not repro when running CLI directly. Then I can check what's the difference. 

I cannot repro the issue from my side so I can not do it by myself.
