### ISSUE TITLE
Update the sidebar icon

### ISSUE THREAD

**Issue by hologerry** [jdneo/vscode-leetcode#395]
With the new vscode icons being released 🎉 ([microsoft/vscode#8017](https://github.com/microsoft/vscode/issues/8017)) ... the icon definitely needs to be updated to match the new icons' styles!

<img width="45" alt="Screen Shot 2019-08-21 at 00 42 15" src="https://user-images.githubusercontent.com/11660168/63366556-97cb8700-c3ac-11e9-949b-c8d05765c42a.png">

**Comment by jdneo** [comment]
Need some help here, since I'm not good at design. 😞

**Comment by poppinlp** [comment]
It’s time to invite UX colleagues to have some drinks. LOL

**Comment by poppinlp** [comment]
![image](https://user-images.githubusercontent.com/1970625/63736451-b6061b00-c8b5-11e9-9328-caec55a16fc9.png)
@jdneo Hi. What do you think about this new icon?

**Comment by jdneo** [comment]
@poppinlp That's awesome! I pretty like it!

Would you like to send a PR to update that?
