### ISSUE TITLE
I don't want to open the preview window when click the show problem, how to do that?

### ISSUE THREAD

**Issue by ttskym** [jdneo/vscode-leetcode#396]
Before you submit an question we recommend you to check out the [DOCUMENT](https://github.com/jdneo/vscode-leetcode/blob/master/README.md) first.

You can also find more information in:
- [TROUBLESHOOTING](https://github.com/jdneo/vscode-leetcode/wiki/Troubleshooting)
- [FAQ](https://github.com/jdneo/vscode-leetcode/wiki/FAQ)

## 💬 Questions and Help

I don't want to open the preview window when click the show problem, how to do that?

**Comment by jdneo** [comment]
You can set the `enableSideMode` to `false`. While we will have a new centralized setting to handle this problem in the future.

**Comment by jdneo** [comment]
Just Introduced a new setting `leetcode.showDescription` to control this in #519. You can have the following options:
- In Webview
- In File Comment
- Both
- None

This setting will be released in next version.
