### ISSUE TITLE
Update the extension icon to align with the new VS Code design

### ISSUE THREAD

**Issue by jdneo** [jdneo/vscode-leetcode#401]
The icon we are using now is not align with the VS Code new design.
![icon](https://raw.githubusercontent.com/jdneo/vscode-leetcode/master/resources/LeetCode.png)

**Comment by poppinlp** [comment]
I've asked my friend for the logo.
Actually, he has asked me if there are some UI/UX design which we need, after he gave me that sidebar icon.

**Comment by jdneo** [comment]
That would be great if he is willing to help. So far the extension icon and the sidebar icon is enough I think.

Does he has a GitHub account? We should thank to his contribution in our document.

**Comment by poppinlp** [comment]
![image](https://user-images.githubusercontent.com/1970625/64581808-1f118680-d3be-11e9-8220-26ceb58132eb.png)
@jdneo We get 2 versions of the icon. The first one is closer to the new vscode icon. The second one is closer to the leetcode icon. Which one do you prefer?

**Comment by jdneo** [comment]
Thanks @poppinlp. I prefer the first one, what do you think?

**Comment by poppinlp** [comment]
Yep. Me too.
Okey. I'll send PR then. And adding him in the `Acknowledgement` part for his contribution.

**Comment by jdneo** [comment]
Can't wait for it!! 😄

**Comment by jdneo** [comment]
Hey @poppinlp ,

Any updates for the new icon PR? I'm planning to make a new release recently and wish we can have the new icon in the new release. 😄

**Comment by poppinlp** [comment]
Sorry for the late update. I've send a PR for it.
The original svg image got something wrong, so I asked my friend to give me a new one this morning.

**Comment by jdneo** [comment]
That's fine. Don't worry.
