### ISSUE TITLE
Find better place to put Code Lens

### ISSUE THREAD

**Issue by bonaluo** [jdneo/vscode-leetcode#407]
Issue Type: <b>Bug</b>

Display error
![image](https://user-images.githubusercontent.com/27731323/64123852-090d3000-cdd8-11e9-988e-491e41d45d4a.png)

Extension version: 0.15.2
VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:17:55.855Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz (4 x 2195)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.91GB (6.72GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by jdneo** [comment]
Since it's hard to determine where the Code Lens should be placed for different language, our implementation is just put it for the last line of the code. So as a workaround, you can just add an empty line to your answer.

BTW, an empty line at EOF is recommended actually: https://stackoverflow.com/a/2287990/11620529

**Comment by jdneo** [comment]
Resolved by #426 

The CodeLens will be placed above the tag `@lc code=end`
