### ISSUE TITLE
[Help Wanted] Cannot sign in to leetcode-cn

### ISSUE THREAD

**Issue by luopeixiang** [jdneo/vscode-leetcode#410]
Get http error [code=500] when logining leetcode-cn, but I can log in normally on the webpage.
Is it an error caused by a change in the api of [leetcode-cn](https://leetcode-cn.com/)?
The output information:
``` 
v8.9.3
 Active  Name               Version         Desc
----------------------------------------------------------------------------------------------------
   ✔     solution.discuss   2019.02.03      Plugin to fetch most voted solution in discussions.
   ✔     company            2017.12.18      Plugin to query by company for free user.
   ✔     cache              default         Plugin to provide local cache.
   ✔     retry              default         Plugin to retry last failed request if autologin.enable is on.
   ✔     leetcode.cn        2018.11.25      Plugin to talk with leetcode-cn APIs.
   ✔     leetcode           default         Plugin to talk with leetcode APIs.
 Active  Name               Version         Desc
----------------------------------------------------------------------------------------------------
   ✔     solution.discuss   2019.02.03      Plugin to fetch most voted solution in discussions.
   ✔     company            2017.12.18      Plugin to query by company for free user.
   ✔     cache              default         Plugin to provide local cache.
   ✔     retry              default         Plugin to retry last failed request if autologin.enable is on.
   ✔     leetcode.cn        2018.11.25      Plugin to talk with leetcode-cn APIs.
   ✔     leetcode           default         Plugin to talk with leetcode APIs.
 Active  Name               Version         Desc
----------------------------------------------------------------------------------------------------
   ✔     solution.discuss   2019.02.03      Plugin to fetch most voted solution in discussions.
   ✔     company            2017.12.18      Plugin to query by company for free user.
   ✔     cache              default         Plugin to provide local cache.
   ✔     retry              default         Plugin to retry last failed request if autologin.enable is on.
   ✔     leetcode.cn        2018.11.25      Plugin to talk with leetcode-cn APIs.
   ✔     leetcode           default         Plugin to talk with leetcode APIs.
 Active  Name               Version         Desc
----------------------------------------------------------------------------------------------------
   ✔     solution.discuss   2019.02.03      Plugin to fetch most voted solution in discussions.
   ✔     company            2017.12.18      Plugin to query by company for free user.
   ✔     cache              default         Plugin to provide local cache.
   ✔     retry              default         Plugin to retry last failed request if autologin.enable is on.
   ✔     leetcode.cn        2018.11.25      Plugin to talk with leetcode-cn APIs.
   ✔     leetcode           default         Plugin to talk with leetcode APIs.
[ERROR] You are not login yet?
login: pass: - Signing in leetcode.com
[ERROR] http error [code=500]
```

------
Update by @jdneo:

I tried it locally, seems it has been fixed from the leetcode-cn side. Is there anyone still having this issue?

Please let us know if it has been fixed at your side.

------
Added by @jdneo:

Thank you all for reporting the issue. If you met this issue as well. You can simply click the 👍 icon to vote up for it. It's not recommended to add comments like `+1`, `me too`, since it will cause the thread too long and make some of the key information hard to find.

So far @poppinlp and I will take a look to it. If anyone is willing to give some help, feel free to let us know.

Thanks @poppinlp in advance.

**Comment by Ehco1996** [comment]
meet this too

**Comment by zerrol** [comment]
when login, get [ERROR] http error [code=500] too

and change the internet to my hot spot，still 500

**Comment by KoreSamuel** [comment]
```
- Downloading maximum-product-subarray
[ERROR] http error [code=500]
```

**Comment by zhanzekun** [comment]
meet this too

**Comment by MosesRen** [comment]
I meet it too

**Comment by lcxq** [comment]
me too

**Comment by Haichen-Leo** [comment]
me too

**Comment by xnuohz** [comment]
```
v10.15.3
 Active  Name               Version         Desc
----------------------------------------------------------------------------------------------------
   √     solution.discuss   2019.02.03      Plugin to fetch most voted solution in discussions.
   √     company            2017.12.18      Plugin to query by company for free user.
   √     cache              default         Plugin to provide local cache.
   √     retry              default         Plugin to retry last failed request if autologin.enable is on.
   √     leetcode.cn        2018.11.25      Plugin to talk with leetcode-cn APIs.
   √     leetcode           default         Plugin to talk with leetcode APIs.
 Active  Name               Version         Desc
----------------------------------------------------------------------------------------------------
   √     solution.discuss   2019.02.03      Plugin to fetch most voted solution in discussions.
   √     company            2017.12.18      Plugin to query by company for free user.
   √     cache              default         Plugin to provide local cache.
   √     retry              default         Plugin to retry last failed request if autologin.enable is on.
   √     leetcode.cn        2018.11.25      Plugin to talk with leetcode-cn APIs.
   √     leetcode           default         Plugin to talk with leetcode APIs.
 Active  Name               Version         Desc
----------------------------------------------------------------------------------------------------
   √     solution.discuss   2019.02.03      Plugin to fetch most voted solution in discussions.
   √     company            2017.12.18      Plugin to query by company for free user.
   √     cache              default         Plugin to provide local cache.
   √     retry              default         Plugin to retry last failed request if autologin.enable is on.
   √     leetcode.cn        2018.11.25      Plugin to talk with leetcode-cn APIs.
   √     leetcode           default         Plugin to talk with leetcode APIs.
 Active  Name               Version         Desc
----------------------------------------------------------------------------------------------------
   √     solution.discuss   2019.02.03      Plugin to fetch most voted solution in discussions.
   √     company            2017.12.18      Plugin to query by company for free user.
   √     cache              default         Plugin to provide local cache.
   √     retry              default         Plugin to retry last failed request if autologin.enable is on.
   √     leetcode.cn        2018.11.25      Plugin to talk with leetcode-cn APIs.
   √     leetcode           default         Plugin to talk with leetcode APIs.
 Premium   User                 Host
------------------------------------------------------------
    ×      xnouhz               https://leetcode-cn.com
- Downloading problems
[ERROR] http error [code=500]
login: 
```

**Comment by andyzheung** [comment]
Me too...
Is the plugin is forbidded?

**Comment by illcat** [comment]
我也是......

**Comment by qinzhiwei037** [comment]
me too

**Comment by dustinksi** [comment]
Maybe leetcode upgrade its API? I met the error about 8 hours ago, wish the author can fix the bug soon~~~

**Comment by jdneo** [comment]
Hey guys,

Thank you for reporting the issue. I'll try ti figure out what's going on. But I'm busying with my work recently. It would be great if we can have any volunteer to help.

**Comment by dustinksi** [comment]
Maybe this is an error from 'leetcode-cli' ?

**Comment by sosamuel** [comment]
me too

**Comment by stack-stark** [comment]
+1

**Comment by zhanght9527** [comment]
me too, can't login in leetcode-cn, wish the author can fix the bug soon~

**Comment by zpqq132555** [comment]
me too
Active  Name               Version         Desc
----------------------------------------------------------------------------------------------------
   √     solution.discuss   2019.02.03      Plugin to fetch most voted solution in discussions.
   √     company            2017.12.18      Plugin to query by company for free user.
   √     cache              default         Plugin to provide local cache.
   √     retry              default         Plugin to retry last failed request if autologin.enable is on.
   ×     leetcode.cn        2018.11.25      Plugin to talk with leetcode-cn APIs.
   √     leetcode           default         Plugin to talk with leetcode APIs.
[ERROR] You are not login yet?
login:  Active  Name               Version         Desc
----------------------------------------------------------------------------------------------------
   √     solution.discuss   2019.02.03      Plugin to fetch most voted solution in discussions.
   √     company            2017.12.18      Plugin to query by company for free user.
   √     cache              default         Plugin to provide local cache.
   √     retry              default         Plugin to retry last failed request if autologin.enable is on.
   √     leetcode.cn        2018.11.25      Plugin to talk with leetcode-cn APIs.
   √     leetcode           default         Plugin to talk with leetcode APIs.
Successfully logout as null-228
login: pass: - Signing in leetcode.com
[ERROR] http error [code=500]

**Comment by poppinlp** [comment]
Sry for all guys.

@jdneo I'll check it tonight.

**Comment by jdneo** [comment]
Thank you @poppinlp. I'll also take a look if I have time tonight. Thank you for offering the help.

**Comment by sosamuel** [comment]
it works now

**Comment by lryong** [comment]
httpcode:500, Seems leetcode-cn.com's  website internal error?

**Comment by farqq** [comment]
我也是
mee too

**Comment by jdneo** [comment]
I tried it locally, seems it has been fixed from the leetcode-cn side. Is there anyone still having this issue?

Please let us know if it has been fixed at your side.

**Comment by dustinksi** [comment]
Already fixed! Thanks~

**Comment by zerrol** [comment]
> Hey guys,
> 
> Thank you for reporting the issue. I'll try to figure out what's going on. But I'm busying with my work recently. It would be great if we can have any volunteer to help.

thanks, fixed

**Comment by jdneo** [comment]
Thank you all. I'm closing this issue since the issue should already fixed.

Happy coding!

**Comment by salehsami** [comment]
i am facing this issue
anyone help me sort it out?
