### ISSUE TITLE
Can't get the latest result about question that i have solved

### ISSUE THREAD

**Issue by bonaluo** [jdneo/vscode-leetcode#411]
Issue Type: <b>Bug</b>

My account number is used for two computers when finish one problem on one and the other did'nt get the latest result. The only way to solve it is to logout and sign in again

Extension version: 0.15.3
VS Code version: Code 1.38.0 (3db7e09f3b61f915d03bbfa58e258d6eee843f35, 2019-09-03T21:49:13.459Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.91GB (2.96GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by jdneo** [comment]
Seems dup with #367
