### ISSUE TITLE
Show the analysis article in the solution section?

### ISSUE THREAD

**Issue by hyt589** [jdneo/vscode-leetcode#424]
## 🚀 Feature Proposal

Instead of just showing the top solution, show the analysis article as well.  

show this:
![image](https://user-images.githubusercontent.com/31054388/65011996-a5a8f500-d8e3-11e9-8bc0-e62e40cf9933.png)

instead of just this:
![image](https://user-images.githubusercontent.com/31054388/65012117-0b957c80-d8e4-11e9-88f8-1c3212cc0d8c.png)

## Motivation

Sometimes just reading the code of other people's submission doesn't really help you understand the intuition behind it. Reading the analysis of the problem provides a deeper understanding of the problem. It would be nice if this could be integrated into the extension so people wouldn't have to leave vs code and go to the actual website.

**Comment by jdneo** [comment]
Since the link of the solution page is formatted as: `https://leetcode.com/problems/<name>/solution/`. We can put a link in the description page, which is very similar with https://github.com/jdneo/vscode-leetcode/pull/421

Any volunteer for this feature?

**Comment by iFun** [comment]
I can take on this
