### ISSUE TITLE
默认登录lintcode

### ISSUE THREAD

**Issue by Wanger-SJTU** [jdneo/vscode-leetcode#425]
## 🐛 Bug Report

切换登录站点的时候，显示的总是 
```
login: login: pass: - Signing in lintcode.com
[ERROR] invalid password?
```
输入了正确的账号密码也不能登录。

## Your Environment

- *os*:win10
- *nodejs version*: v10.15.3
- *vscode version*:1.38.1
- *extension version*:0.15.4

**Comment by jdneo** [comment]
If you want to sign in to lintcode, sorry the extension does not support it yet.

If you want to sign in to leetcode, I guess you have used the LeetCode CLI before. Please try this: https://github.com/jdneo/vscode-leetcode/wiki/Troubleshooting#thinking-cannot-sign-in

**Comment by Wanger-SJTU** [comment]
It's the log tells me that I was  trying to signin lintcode, while I want to signin leetcode or leetcode-cn, No matter what I choose.

**Comment by jdneo** [comment]
Please try to remove the cache folder: `$home/.lc/` and try again

**Comment by Wanger-SJTU** [comment]
It works. Thanks a  lot.
