### ISSUE TITLE
[ERROR] Problem not found!

### ISSUE THREAD

**Issue by tsinghua96** [jdneo/vscode-leetcode#430]
## 🐛 Bug Report
click "preview problem",show the error:"[ERROR] Problem not found!"
click "show top voted solution",then show the error:
Error: Command "node "c:\Users\xxxx\\.vscode\extensions\shengchen.vscode-leetcode-0.15.4\node_modules\vsc-leetcode-cli\bin\leetcode",show,4,--solution,-l,c" failed with exit code "0"..

## Your Environment

- *os*:window10 1903
- *extension settings*:
- *nodejs version*:10.16.0
- *vscode version*:1.38.1
- *extension version*:0.15.4

**Comment by RuyiLuo** [comment]
I have been encountered same problems with you.

**Comment by HopeCollector** [comment]
my friend has the same problen with u

**Comment by codyi96** [comment]
facing same issue @jdneo

**Comment by jdneo** [comment]
@all

I found a potential problem and provided a fix here: https://github.com/leetcode-tools/leetcode-cli/pull/24.

Before I release the fix, you can manually modify the file at: `$home/.vscode/extensions/shengchen.vscode-leetcode-0.15.4/node_modules/vsc-leetcode-cli/lib/core.js:95⁩` just the same as the PR I referenced above.

**Comment by RuyiLuo** [comment]
> @ALL
> 
> I found a potential problem and provided a fix here: [leetcode-tools/leetcode-cli#24](https://github.com/leetcode-tools/leetcode-cli/pull/24).
> 
> Before I release the fix, you can manually modify the file at: `$home/.vscode/extensions/shengchen.vscode-leetcode-0.15.4/node_modules/vsc-leetcode-cli/lib/core.js:95⁩` just the same as the PR I referenced above.

it works for me, thanks.

**Comment by tsinghua96** [comment]
> @ALL
> 
> I found a potential problem and provided a fix here: [leetcode-tools/leetcode-cli#24](https://github.com/leetcode-tools/leetcode-cli/pull/24).
> 
> Before I release the fix, you can manually modify the file at: `$home/.vscode/extensions/shengchen.vscode-leetcode-0.15.4/node_modules/vsc-leetcode-cli/lib/core.js:95⁩` just the same as the PR I referenced above.

Thank you,It works out perfectly.

**Comment by illcat** [comment]
> @ALL
> 
> I found a potential problem and provided a fix here: [leetcode-tools/leetcode-cli#24](https://github.com/leetcode-tools/leetcode-cli/pull/24).
> 
> Before I release the fix, you can manually modify the file at: `$home/.vscode/extensions/shengchen.vscode-leetcode-0.15.4/node_modules/vsc-leetcode-cli/lib/core.js:95⁩` just the same as the PR I referenced above.

Show Top Voted Solution function  is also [ERROR] Problem not found!

**Comment by ZoeQgOgO** [comment]
Can’t fetch the problem preview!
Error message :
Error running command leetcode.previewProblem: Running the contributed command:'leetcode.previewProblem' failed. This is likely caused by the extention that contributes leetocde.previewProblem.
