### ISSUE TITLE
when filename is empty it uses the folder name to create a file

### ISSUE THREAD

**Issue by iFun** [jdneo/vscode-leetcode#432]
## 🐛 Bug Report

    "leetcode.filePath": {
        "default": {
            // relative folder path
            "folder": "${tag}/${language}",
            // file name
            "filename": ""
        }
    },

I leave the filename as blank because I wanted the old default filename and run into cannot create file error because it uses the folder name as the filename
## To Reproduce

copy above and see the result

## Expected behavior

folder name should be use as the filename

## Extension Output

Paste here the LeetCode extension log from output channel.

Guidance: Press `Ctrl+Shift+U`, and toggle the channel to `LeetCode`.

## Your Environment

- *os*:
- *extension settings*:
- *nodejs version*:
- *vscode version*:
- *extension version*:

**Comment by jdneo** [comment]
> ## Expected behavior
>
> folder name should be use as the filename

Is this sentence wrongly expressed?

**Comment by iFun** [comment]
> > ## Expected behavior
> > folder name should be use as the filename
> 
> Is this sentence wrongly expressed?
![Capture](https://user-images.githubusercontent.com/4850036/65739228-7e57e200-e0b2-11e9-9ba9-13c7ee95a5e9.PNG)

yeah sorry, The expect behavior is that the folder name should not be use as filename. In the capture above the tag in the foldername is used as create filename which causes problem
