### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by JasmineCAicai** [jdneo/vscode-leetcode#435]
- Issue Type: `Performance`
- Extension Name: `vscode-leetcode`
- Extension Version: `0.15.4`
- OS Version: `Windows_NT x64 10.0.18362`
- VSCode version: `1.38.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\ThinkPad\shengchen.vscode-leetcode-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by jdneo** [comment]
Could you please provide the `cpuprofile.txt`?

**Comment by JasmineCAicai** [comment]
Of course.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Sheng Chen"<notifications@github.com&gt;;
发送时间:&nbsp;2019年9月28日(星期六) 下午4:36
收件人:&nbsp;"jdneo/vscode-leetcode"<vscode-leetcode@noreply.github.com&gt;;
抄送:&nbsp;"tangerine🐇"<1105111422@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [jdneo/vscode-leetcode] Extension causes high cpu load (#435)




Could you please provide the cpuprofile.txt?
