### ISSUE TITLE
[Help]Can not code from the problem

### ISSUE THREAD

**Issue by Loushuaw** [jdneo/vscode-leetcode#436]
## 💬 Questions and Help

Can not open the new code file.
As the picture shows:

![log](https://user-images.githubusercontent.com/15009016/65811674-ad736e00-e1ee-11e9-95d7-15be2a9d59a1.gif)

**Comment by 997282173** [comment]
是不是改了目录, 去设置里面改下看看

**Comment by Loushuaw** [comment]
重装重新配置目录解决了
