### ISSUE TITLE
默认语言的问题

### ISSUE THREAD

**Issue by choboboybbob** [jdneo/vscode-leetcode#450]
设定了默认语言后, 比如配置了```"leetcode.defaultLanguage": "java",```, 有一些题目只支持特定语言的, 比如[[192] 统计词频](https://leetcode-cn.com/problems/word-frequency/description/), 这时打开题目要取消特定语言的配置. 挺不方便的.

**Comment by jdneo** [comment]
Thank you for the feedback.

The request is duplicated with #234, so I'm going to closing this one and track it in the original one. Thank you for the understanding.
