### ISSUE TITLE
Couldn't sign in for both CN or US version, ERROR tunneling socket could not be established

### ISSUE THREAD

**Issue by JourneyChanger** [jdneo/vscode-leetcode#451]
[ERROR] Error: tunneling socket could not be established, cause=connect ECONNREFUSED 127.0.0.1:8080

occurs to both version , so I couldn't sign in,what's that?
my Note.js's PATH is right

**Comment by taoweicn** [comment]
Seems to be caused by the proxy.

**Comment by YuanhuiCheng** [comment]
> [ERROR] Error: tunneling socket could not be established, cause=connect ECONNREFUSED 127.0.0.1:8080
> 
> occurs to both version , so I couldn't sign in,what's that?
> my Note.js's PATH is right

Have you resolved the issue? I just met the same issue, which is annoying.

**Comment by yihong0618** [comment]
GFW. 
Please try to use your phone as a hotspot and try again.

**Comment by jdneo** [comment]
Seems to be a network/proxy issue.

Could you please try to change to another network environment and have a try?

**Comment by YuanhuiCheng** [comment]
@yihong0618 @jdneo  I have already tried using my phone hotspot and another network environment and still don't think it works. This issue happens after I upgraded my OS version to 10.15.2(macOS Catalina). Here is the specific issue: 

```
[ERROR] You are not login yet?
login: pass: - Signing in leetcode.com
[ERROR] Error: tunneling socket could not be established, cause=connect ECONNREFUSED 127.0.0.1:80
```
