### ISSUE TITLE
Get All Your solved file in VsCode which you have already solved in leet.com directly

### ISSUE THREAD

**Issue by yogain123** [jdneo/vscode-leetcode#454]
## 🚀 Feature Proposal

Get All Your solved file in VsCode which you have already solved in leet.com directly

## Motivation

let say you have solved questions 2,3 in leetcode.com directly, then if you go to vscode, get All Solved files in vscode

**Comment by jdneo** [comment]
Dup with #69

**Comment by yogain123** [comment]
please add this feature, don't close my issue

**Comment by jdneo** [comment]
Closing does not mean I won't support this. It's recommended to track the same issue in one place. But so far I have no ETA for this feature.

BTW, contribution is welcome, if you would like to add this feature, just feel free to send out a PR for it.
