### ISSUE TITLE
Get All Your solved file in VsCode which you have already solved in leet.com directly #454

### ISSUE THREAD

**Issue by yogain123** [jdneo/vscode-leetcode#456]
Please add this. It's highly useful and required

**Comment by jdneo** [comment]
Please do not repeatedly open the same issue. I believe this request is duplicated with #69. Have duplicated issues opening just for the same thing is not the right way to track the tasks. It's recommended to track the same issue in one place.

And if you think this feature is highly useful. Just feel free to send out a PR to add it. I'm willing to accept any contribution for the extension.

Thank you for your understanding.

**Comment by yogain123** [comment]
okay.
