### ISSUE TITLE
can't use "Test" function

### ISSUE THREAD

**Issue by yiruacm** [jdneo/vscode-leetcode#457]
## 🐛 Bug Report

Cannot read property 'slice' of undefined

## To Reproduce

click the button "Test",then report error.

## Extension Output

`      results[0].stdout = results[0].stdout.slice(1, -1).replace(/\\n/g, '\n');
                                            ^

TypeError: Cannot read property 'slice' of undefined`

## Your Environment

- *os*:windows10
- *extension settings*:default
- *nodejs version*:10.15.1
- *vscode version*:1.38.1
- *extension version*:0.15.6

**Comment by jdneo** [comment]
Dup with #455
