### ISSUE TITLE
Please update the icons with new outline style icons (provided by VS Code)

### ISSUE THREAD

**Issue by hologerry** [jdneo/vscode-leetcode#460]
Please update the icons in extension with the [vscode-icons](https://github.com/microsoft/vscode-icons).

<img width="249" alt="Screen Shot 2019-10-09 at 23 34 36" src="https://user-images.githubusercontent.com/11660168/66499363-4ad57880-eaf2-11e9-8cbc-dd50f694067c.png">

<img width="469" alt="Screen Shot 2019-10-10 at 00 10 53" src="https://user-images.githubusercontent.com/11660168/66499518-92f49b00-eaf2-11e9-9f37-9b4a13c711e7.png">
<img width="475" alt="Screen Shot 2019-10-10 at 00 11 02" src="https://user-images.githubusercontent.com/11660168/66499529-96882200-eaf2-11e9-8502-3fae58a2d7a9.png">

<img width="480" alt="Screen Shot 2019-10-10 at 00 12 33" src="https://user-images.githubusercontent.com/11660168/66499609-b61f4a80-eaf2-11e9-84a3-53808a5ba1e0.png">

<img width="446" alt="Screen Shot 2019-10-10 at 00 11 12" src="https://user-images.githubusercontent.com/11660168/66499535-9851e580-eaf2-11e9-9bac-45c06f77d96d.png">

I tried with replacing these svgs, but the endpoint (globe) icon does not work.

<img width="339" alt="Screen Shot 2019-10-10 at 00 20 50" src="https://user-images.githubusercontent.com/11660168/66500432-16fb5280-eaf4-11e9-84d3-d13bf1434127.png">

Thanks a lot!

**Comment by jdneo** [comment]
@hologerry That's a good finding. Would you like to send out a PR? I can take a look at the globe icon based on your contribution.

**Comment by hologerry** [comment]
OK, I will do it today.
