### ISSUE TITLE
HOW TO GET MY HISTORY CODES WRITTEN IN WEBSITES？

### ISSUE THREAD

**Issue by Areshyy** [jdneo/vscode-leetcode#462]
Before you submit an question we recommend you to check out the [DOCUMENT](https://github.com/jdneo/vscode-leetcode/blob/master/README.md) first.

You can also find more information in:
- [TROUBLESHOOTING](https://github.com/jdneo/vscode-leetcode/wiki/Troubleshooting)
- [FAQ](https://github.com/jdneo/vscode-leetcode/wiki/FAQ)

## 💬 Questions and Help

Please outline the questions.

**Comment by jdneo** [comment]
dup with #69.

I'm closing this issue and let's track it there.
