### ISSUE TITLE
Not supported language "javascript"

### ISSUE THREAD

**Issue by yogain123** [jdneo/vscode-leetcode#464]
## 🐛 Bug Report

My Default language set is Javascript, but for question **193: Valid phone Numbers**  Error comes **Not supported language "javascript".**
Maybe you can popup options to select Language if default language doesn't meet with the required language.

To Solve problem 193 which required **Bash** Language, I changed the default language to Bash, and then later changed it to Javascript.

**Comment by jdneo** [comment]
Thanks for reporting the issue. This is duplicated with https://github.com/jdneo/vscode-leetcode/issues/234. So I'm closing this one.
