### ISSUE TITLE
show past submissions in the UI

### ISSUE THREAD

**Issue by kongda** [jdneo/vscode-leetcode#468]
## 🚀 Feature Proposal

show past submissions in the UI

## Motivation

If the UI shows past submissions, users don't have to go to leetcode.com to find past submissions.

**Comment by jdneo** [comment]
Hi @kongda, thank you for your feedback. We have another issue tracking this request. So I'm going to close this one and track this issue there. Thanks for understanding.

**Comment by kongda** [comment]
jdneo@ thank you very much for your prompt response! I appreciate it! I'm wondering if you could paste the link of the other issue here for future reference?

**Comment by jdneo** [comment]
Sorry I forgot to paste it. https://github.com/jdneo/vscode-leetcode/issues/69
