### ISSUE TITLE
增加一键进入白板模式（一键取消语法高亮和自动补全）

### ISSUE THREAD

**Issue by zhangddjs** [jdneo/vscode-leetcode#470]
## 🚀 Feature Proposal

如题，可以增加一个一键进入白板模式的功能吗？

**Comment by jdneo** [comment]
Hi @zhangddjs, 

Though this is a valid request. But I'm afraid this is not achievable so far since the syntax highlighting and auto-completion are all controlled by VS Code, which is out of the scope of LeetCode extension. If you want, please raise an issue at VS Code side.

Thanks.

**Comment by zhangddjs** [comment]
got it~ thank you
