### ISSUE TITLE
Unexpected token 

### ISSUE THREAD

**Issue by wppwzk** [jdneo/vscode-leetcode#471]
SyntaxError: Unexpected token 
undefined:1

SyntaxError: Unexpected token 
Error: Command "node "c:\Users\bocai.yang\.vscode\extensions\shengchen.vscode-leetcode-0.15.7\node_modules\vsc-leetcode-cli\bin\leetcode",plugin,-i,company" failed with exit code "1".

**Comment by jdneo** [comment]
Please try to remove the folder `$HOME/.lc` and try again

**Comment by wppwzk** [comment]
解决了，谢谢发自我的华为手机-------- 原始邮件 --------发件人： Sheng Chen <notifications@github.com>日期： 2019年10月30日周三 17:16收件人： jdneo/vscode-leetcode <vscode-leetcode@noreply.github.com>抄送： Icarus <q11w1e1r@sina.com>, Author <author@noreply.github.com>主    题： Re: [jdneo/vscode-leetcode] Unexpected token  (#471)Please try to remove the folder $HOME/.lc and try again

**Comment by Li-Shu14** [comment]
I met the same problem which bothered me serveral weeks ... and solved by delete $HOME/.lc  !!
