### ISSUE TITLE
could this be used on vscode-server?

### ISSUE THREAD

**Issue by epiciskandar** [jdneo/vscode-leetcode#473]
I am trying using this extension on my vscode-server,the version(1.39.2) match requirements, and node.js 12 installed, but the extension cannot response my login request, clicking 'Sign in to LeetCode' just not working, nothing pop out.

at the OUTPUT:LeetCode, could see these:

v12.13.0
 Active  Name               Version         Desc
----------------------------------------------------------------------------------------------------
   ✔     solution.discuss   2019.02.03      Plugin to fetch most voted solution in discussions.
   ✔     company            2017.12.18      Plugin to query by company for free user.
   ✔     cache              default         Plugin to provide local cache.
   ✔     retry              default         Plugin to retry last failed request if autologin.enable is on.
   ✘     leetcode.cn        2018.11.25      Plugin to talk with leetcode-cn APIs.
   ✔     leetcode           default         Plugin to talk with leetcode APIs.
 Active  Name               Version         Desc
----------------------------------------------------------------------------------------------------
   ✔     solution.discuss   2019.02.03      Plugin to fetch most voted solution in discussions.
   ✔     company            2017.12.18      Plugin to query by company for free user.
   ✔     cache              default         Plugin to provide local cache.
   ✔     retry              default         Plugin to retry last failed request if autologin.enable is on.
   ✘     leetcode.cn        2018.11.25      Plugin to talk with leetcode-cn APIs.
   ✔     leetcode           default         Plugin to talk with leetcode APIs.
 Active  Name               Version         Desc
----------------------------------------------------------------------------------------------------
   ✔     solution.discuss   2019.02.03      Plugin to fetch most voted solution in discussions.
   ✔     company            2017.12.18      Plugin to query by company for free user.
   ✔     cache              default         Plugin to provide local cache.
   ✔     retry              default         Plugin to retry last failed request if autologin.enable is on.
   ✔     leetcode.cn        2018.11.25      Plugin to talk with leetcode-cn APIs.
   ✔     leetcode           default         Plugin to talk with leetcode APIs.
 Active  Name               Version         Desc
----------------------------------------------------------------------------------------------------
   ✔     solution.discuss   2019.02.03      Plugin to fetch most voted solution in discussions.
   ✔     company            2017.12.18      Plugin to query by company for free user.
   ✔     cache              default         Plugin to provide local cache.
   ✔     retry              default         Plugin to retry last failed request if autologin.enable is on.
   ✘     leetcode.cn        2018.11.25      Plugin to talk with leetcode-cn APIs.
   ✔     leetcode           default         Plugin to talk with leetcode APIs.
[ERROR] You are not login yet?

**Comment by jdneo** [comment]
Do you mean the [Code-Server](https://github.com/cdr/code-server)?

**Comment by sunerpy** [comment]
I reopen this issue, when I use code-server, click the button "Open Visual Studio Code", nothing happend.
And there are some infomations from F12 （devloper  console）:
```
Launched external handler for 'vscode://leetcode.vscode-leetcode?&cookie=xxx'.
vscode/:1  Access to fetch at 'https://sentry1.lingkou.xyz/api/2/envelope/?sentry_key=xxx&sentry_version=7&sentry_client=sentry.javascript.nextjs%2F7.51.2' from origin 'https://leetcode.cn' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
_app-fbf8e42e1f91fa81.js:9   POST https://sentry1.lingkou.xyz/api/2/envelope/?sentry_key=xxx&sentry_version=7&sentry_client=sentry.javascript.nextjs%2F7.51.2 net::ERR_FAILED 502 (Bad Gateway)
```
