### ISSUE TITLE
How to login by three party auth

### ISSUE THREAD

**Issue by godlockin** [jdneo/vscode-leetcode#475]
I read & searched the readme and issues but can't finger out that, how to login the vscode-leetcode by three party way, e.g. github auth?

**Comment by BarryYan** [comment]
Just login with web and change password, then use email & password to login

**Comment by MandyJCho** [comment]
Has anyone had any success with doing that though? It keeps failing me.

**Comment by MandyJCho** [comment]
@godlockin This isn't supported yet but there is a [feature request](https://github.com/jdneo/vscode-leetcode/issues/62) out there to get this implemented. If you're still having trouble logging in, trying following the steps [here](https://github.com/jdneo/vscode-leetcode/issues/478) to login using a cookie.

**Comment by yihong0618** [comment]
I think change password is a better way. Third-party login is not so simple.

**Comment by MandyJCho** [comment]
For sure! It kept erroring out for me even after setting a password, so I ended up having to use the cookie.

**Comment by jdneo** [comment]
Close for duplication with #62.

And FYI @yihong0618 is working on this feature, see: #496
