### ISSUE TITLE
Can't successfully log in 

### ISSUE THREAD

**Issue by mpirbhoy** [jdneo/vscode-leetcode#477]
After entering my email and password, get an alert: "Failed to sign in" with "[ERROR] invalid password?" in the console output.

I am copying the password exactly as it is shown on the browser through which I can log in successfully. 

I'm also logging in against the correct end point (leetcode.com), yet I still have this issue. Any help in solving this is appreciated.

**Comment by queensferryme** [comment]
It seems we are facing the same issue (#478) 😁
