### ISSUE TITLE
how to build it from source code?

### ISSUE THREAD

**Issue by LincolnZeng** [jdneo/vscode-leetcode#481]
Before you submit an question we recommend you to check out the [DOCUMENT](https://github.com/jdneo/vscode-leetcode/blob/master/README.md) first.

You can also find more information in:
- [TROUBLESHOOTING](https://github.com/jdneo/vscode-leetcode/wiki/Troubleshooting)
- [FAQ](https://github.com/jdneo/vscode-leetcode/wiki/FAQ)

## 💬 Questions and Help

Please outline the questions.
May I ask what's the steps to build it from source code and then add it to vscode? Thank you~!

**Comment by jdneo** [comment]
You can just run the script in the travis.yml: https://github.com/jdneo/vscode-leetcode/blob/master/.travis.yml

**Comment by jdneo** [comment]
Closing for it being inactive for a long time.
