### ISSUE TITLE
Login Failed after Becoming a Premium Member

### ISSUE THREAD

**Issue by luoxinran28** [jdneo/vscode-leetcode#482]
Hi. I failed to log in my account after purchasing a Premium member on LeetCode. I tried to change the password and login with the account name and email but it still shows Invalid Password. Thanks.

你好，我购买了LeetCode高级会员之后，我就无法通过插件登录了，账号和邮箱都试过一直显示的是错误密码。谢谢了！

**Comment by jdneo** [comment]
dup with #478
