### ISSUE TITLE
cannot download problems

### ISSUE THREAD

**Issue by shaojintian** [jdneo/vscode-leetcode#484]
## 🐛 Bug Report

cannot download problems

## To Reproduce

click pick one ,and occurs this bug

## Expected behavior

downloaded problems set

## Extension Output

- Downloading problems
- Downloading questions titles
/Users/shaojintian/.vscode/extensions/shengchen.vscode-leetcode-0.15.7/node_modules/vsc-leetcode-cli/lib/plugins/leetcode.cn.js:118
    body.data.translations.forEach(function(x) {
                           ^

TypeError: Cannot read property 'forEach' of null
    at Request._callback (/Users/shaojintian/.vscode/extensions/shengchen.vscode-leetcode-0.15.7/node_modules/vsc-leetcode-cli/lib/plugins/leetcode.cn.js:118:28)
    at Request.self.callback (/Users/shaojintian/.vscode/extensions/shengchen.vscode-leetcode-0.15.7/node_modules/request/request.js:185:22)
    at Request.emit (events.js:210:5)
    at Request.<anonymous> (/Users/shaojintian/.vscode/extensions/shengchen.vscode-leetcode-0.15.7/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:210:5)
    at IncomingMessage.<anonymous> (/Users/shaojintian/.vscode/extensions/shengchen.vscode-leetcode-0.15.7/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:299:28)
    at IncomingMessage.emit (events.js:215:7)
    at endReadableNT (_stream_readable.js:1183:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
/Users/shaojintian/.vscode/extensions/shengchen.vscode-leetcode-0.15.7/node_modules/vsc-leetcode-cli/lib/plugins/leetcode.cn.js:118
    body.data.translations.forEach(function(x) {
## Your Environment

- *os*:macos catalina
- *extension settings*:normal
- *nodejs version*:12.13.0
- *vscode version*:14.0
- *extension version*:0.15.7

**Comment by ZhangGang12** [comment]
i meet the same problem,
my environment :
os:window10
extension settings:normal
nodejs version:12.13.1
vscode version:14.02
extension version:0.15.7

**Comment by cattlesheep** [comment]
os:window10
extension settings:normal
nodejs version:12.4.0
vscode version:1.40.1
extension version:0.15.7

**Comment by F5fly** [comment]
os: macos mojave
extension settings:normal
nodejs version:12.12.0
vscode version:1.40.2
extension version:0.15.7

**Comment by jdneo** [comment]
@all Does this problem still occur?

Will it help if you remove the cache at `$home/.lc`?

**Comment by rockNwater** [comment]
The same problem happens to me. Removal of cache in ~/.lc does NOT work.

os: Ubuntu 16.04
vs code Version: 1.41.1
node.js: 8.17.0
extension version:0.16.0

The follows are extension output:
v8.17.0
 Active  Name               Version         Desc
----------------------------------------------------------------------------------------------------
   ✔     solution.discuss   2019.02.03      Plugin to fetch most voted solution in discussions.
   ✔     company            2017.12.18      Plugin to query by company for free user.
   ✔     cache              default         Plugin to provide local cache.
   ✔     retry              default         Plugin to retry last failed request if autologin.enable is on.
   ✘     leetcode.cn        2018.11.25      Plugin to talk with leetcode-cn APIs.
   ✔     leetcode           default         Plugin to talk with leetcode APIs.
 Active  Name               Version         Desc
----------------------------------------------------------------------------------------------------
   ✔     solution.discuss   2019.02.03      Plugin to fetch most voted solution in discussions.
   ✔     company            2017.12.18      Plugin to query by company for free user.
   ✔     cache              default         Plugin to provide local cache.
   ✔     retry              default         Plugin to retry last failed request if autologin.enable is on.
   ✘     leetcode.cn        2018.11.25      Plugin to talk with leetcode-cn APIs.
   ✔     leetcode           default         Plugin to talk with leetcode APIs.
 Active  Name               Version         Desc
----------------------------------------------------------------------------------------------------
   ✔     solution.discuss   2019.02.03      Plugin to fetch most voted solution in discussions.
   ✔     company            2017.12.18      Plugin to query by company for free user.
   ✔     cache              default         Plugin to provide local cache.
   ✔     retry              default         Plugin to retry last failed request if autologin.enable is on.
   ✔     leetcode.cn        2018.11.25      Plugin to talk with leetcode-cn APIs.
   ✔     leetcode           default         Plugin to talk with leetcode APIs.
 Active  Name               Version         Desc
----------------------------------------------------------------------------------------------------
   ✔     solution.discuss   2019.02.03      Plugin to fetch most voted solution in discussions.
   ✔     company            2017.12.18      Plugin to query by company for free user.
   ✔     cache              default         Plugin to provide local cache.
   ✔     retry              default         Plugin to retry last failed request if autologin.enable is on.
   ✘     leetcode.cn        2018.11.25      Plugin to talk with leetcode-cn APIs.
   ✔     leetcode           default         Plugin to talk with leetcode APIs.
 Premium   User                 Host
------------------------------------------------------------
    ✘      [username]             https://leetcode.com
- Downloading problems

**Comment by SuyashGoylit** [comment]
> The same problem happens to me. Removal of cache in ~/.lc does NOT work.
> 
> os: Ubuntu 16.04 vs code Version: 1.41.1 node.js: 8.17.0 extension version:0.16.0
> ## The follows are extension output:
> v8.17.0
> Active Name Version Desc
> ## heavy_check_mark solution.discuss 2019.02.03 Plugin to fetch most voted solution in discussions.
> heavy_check_mark company 2017.12.18 Plugin to query by company for free user.
> heavy_check_mark cache default Plugin to provide local cache.
> heavy_check_mark retry default Plugin to retry last failed request if autologin.enable is on.
> ✘ leetcode.cn 2018.11.25 Plugin to talk with leetcode-cn APIs.
> heavy_check_mark leetcode default Plugin to talk with leetcode APIs.
> Active Name Version Desc
> ## heavy_check_mark solution.discuss 2019.02.03 Plugin to fetch most voted solution in discussions.
> heavy_check_mark company 2017.12.18 Plugin to query by company for free user.
> heavy_check_mark cache default Plugin to provide local cache.
> heavy_check_mark retry default Plugin to retry last failed request if autologin.enable is on.
> ✘ leetcode.cn 2018.11.25 Plugin to talk with leetcode-cn APIs.
> heavy_check_mark leetcode default Plugin to talk with leetcode APIs.
> Active Name Version Desc
> ## heavy_check_mark solution.discuss 2019.02.03 Plugin to fetch most voted solution in discussions.
> heavy_check_mark company 2017.12.18 Plugin to query by company for free user.
> heavy_check_mark cache default Plugin to provide local cache.
> heavy_check_mark retry default Plugin to retry last failed request if autologin.enable is on.
> heavy_check_mark leetcode.cn 2018.11.25 Plugin to talk with leetcode-cn APIs.
> heavy_check_mark leetcode default Plugin to talk with leetcode APIs.
> Active Name Version Desc
> ## heavy_check_mark solution.discuss 2019.02.03 Plugin to fetch most voted solution in discussions.
> heavy_check_mark company 2017.12.18 Plugin to query by company for free user.
> heavy_check_mark cache default Plugin to provide local cache.
> heavy_check_mark retry default Plugin to retry last failed request if autologin.enable is on.
> ✘ leetcode.cn 2018.11.25 Plugin to talk with leetcode-cn APIs.
> heavy_check_mark leetcode default Plugin to talk with leetcode APIs.
> Premium User Host
> 
> ```
> ✘      [username]             https://leetcode.com
> ```
> 
>     * Downloading problems

I'm facing the same issue. Did anybody find the solution to this problem?
