### ISSUE TITLE
Cannot Login to leetcode using VSCode

### ISSUE THREAD

**Issue by ahmealy** [jdneo/vscode-leetcode#486]
## 🐛 Bug Report

I'm not able to sign in using leetcode extension,
every time i log in using the username and password. 
it gives me this error 'failed to sign in'
"login: pass: - Signing in leetcode.com
[ERROR] invalid password?"

although i log in with the same username and password in the leetcode website normally.

## Extension Output
"login: pass: - Signing in leetcode.com
[ERROR] invalid password?"

## Your Environment

- *os*: windows 10
- *nodejs version*: 12.3.1
- *vscode version*: 1.40.2 (user setup)
- *extension version*: 0.15.7

**Comment by jdneo** [comment]
Dup with #478
