### ISSUE TITLE
[ERROR] http error [code=400]

### ISSUE THREAD

**Issue by huang-kun** [jdneo/vscode-leetcode#489]
I install the leetcode plugin from vscode and login successfully with leetcode-cn account, but it fails downloading contents.

```
- Downloading problems
- Downloading questions titles
[ERROR] http error [code=400]
```

I like this plugin. It really improves leetcode experience. But it doesn't work now. Can you help me?

**Comment by ws2020** [comment]
+1

**Comment by lemongeek** [comment]
+1

**Comment by MaybeSilent** [comment]
I also meet this problem

**Comment by RenZMin** [comment]
i met this problem too

**Comment by arron7856d** [comment]
+1

**Comment by tumumu-awesome** [comment]
+1

**Comment by pwf2006** [comment]
+1

**Comment by liushaoxiong10** [comment]
+1

**Comment by zhanghengjie1993** [comment]
+1

**Comment by yihong0618** [comment]
Hi @all @jdneo 
I try to locate this bug. 
And I found that  leetcode-cn just change their payload in here.
![image](https://user-images.githubusercontent.com/15976103/70373982-c9029f80-1928-11ea-919d-0c27c9ec7d46.png)
I try to change it to new payload, found it worked, and I need more time for debug it.
![image](https://user-images.githubusercontent.com/15976103/70374004-17b03980-1929-11ea-901e-feda02944772.png)
But today I'm a little busy and I will find someway maybe tomorrow night~

**Comment by yihong0618** [comment]
If you want to quick fix this you can find the file in plugin/leetcode-can.js , you can change the payload like mine then change the question.title below(I forget the very name) because I have no computer right now~

**Comment by YinDongFang** [comment]
> 
> 
> Hi @ALL @jdneo
> I try to locate this bug.
> And I found that leetcode-cn just change their payload in here.
> ![image](https://user-images.githubusercontent.com/15976103/70373982-c9029f80-1928-11ea-919d-0c27c9ec7d46.png)
> I try to change it to new payload, found it worked, and I need more time for debug it.
> ![image](https://user-images.githubusercontent.com/15976103/70374004-17b03980-1929-11ea-901e-feda02944772.png)
> But today I'm a little busy and I will find someway maybe tomorrow night~

change code at line 117 to following:
body.data.translations.forEach(function(x) {
      titles[x.questionId] = x.title;
    });

**Comment by yihong0618** [comment]
> > Hi @ALL @jdneo
> > I try to locate this bug.
> > And I found that leetcode-cn just change their payload in here.
> > ![image](https://user-images.githubusercontent.com/15976103/70373982-c9029f80-1928-11ea-919d-0c27c9ec7d46.png)
> > I try to change it to new payload, found it worked, and I need more time for debug it.
> > ![image](https://user-images.githubusercontent.com/15976103/70374004-17b03980-1929-11ea-901e-feda02944772.png)
> > But today I'm a little busy and I will find someway maybe tomorrow night~
> 
> change code at line 117 to following:
> body.data.translations.forEach(function(x) {
> titles[x.questionId] = x.title;
> });

Yes but my laptop is power off ...

**Comment by jjeejj** [comment]
I also met this problem on my Mac pro
but window system is right

leetcode extension version is latest
vscode 1.40.2
Node.js: 12.4.0
mac 10.15.1 (19B88)

**Comment by bubble93** [comment]
Where is plugin / leetcode-cn.js?
I searched the whole computer. We can't find it.

**Comment by yihong0618** [comment]
> Where is plugin / leetcode-cn.js?
> I searched the whole computer. We can't find it.

sorry，I don't remember the filename. maybe leetcode.cn.js（filename）

**Comment by zhanghengjie1993** [comment]
C:\Users\hengjie\.vscode\extensions\shengchen.vscode-leetcode-0.15.7\node_modules\vsc-leetcode-cli\lib\plugins\leetcode.cn.js

> Where is plugin / leetcode-cn.js?
> I searched the whole computer. We can't find it.
the path in my environment is 
C:\Users\hengjie\.vscode\extensions\shengchen.vscode-leetcode-0.15.7\node_modules\vsc-leetcode-cli\lib\plugins\leetcode.cn.js

**Comment by zhanghengjie1993** [comment]
> Where is plugin / leetcode-cn.js?
> I searched the whole computer. We can't find it.

the path in my environment is  C:\Users\hengjie\.vscode\extensions\shengchen.vscode-leetcode-0.15.7\node_modules\vsc-leetcode-cli\lib\plugins\leetcode.cn.js

**Comment by jiawei6636** [comment]
Mark!

**Comment by bubble93** [comment]
> > Where is plugin / leetcode-cn.js?
> > I searched the whole computer. We can't find it.
> 
> the path in my environment is C:\Users\hengjie\.vscode\extensions\shengchen.vscode-leetcode-0.15.7\node_modules\vsc-leetcode-cli\lib\plugins\leetcode.cn.js

Thank you very much. I found it

**Comment by Shihongji** [comment]
Sorry, is this right?
Still not work
![image](https://user-images.githubusercontent.com/7557349/70383101-191e4800-19a3-11ea-8196-dfc263746c76.png)

**Comment by yihong0618** [comment]
> Sorry, is this right?
> Still not work
> ![image](https://user-images.githubusercontent.com/7557349/70383101-191e4800-19a3-11ea-8196-dfc263746c76.png)

you have to change x.question.questionId to x.questionId

**Comment by RenZMin** [comment]
> Sorry, is this right?
> Still not work
> ![image](https://user-images.githubusercontent.com/7557349/70383101-191e4800-19a3-11ea-8196-dfc263746c76.png)
i cha

> > Sorry, is this right?
> > Still not work
> > ![image](https://user-images.githubusercontent.com/7557349/70383101-191e4800-19a3-11ea-8196-dfc263746c76.png)
> 
> you have to change x.question.questionId to x.questionId and the payload （should exactly like mine

![1575772617(1)](https://user-images.githubusercontent.com/42882641/70383313-b929a080-19a6-11ea-88db-a6a1436139bd.png)
sorry，，i have changed  x.question.questionId to x.questionId and the payload 。the picture is my leetcode.cn.js.But it didn't work. Is there anything with my changes? Thank you.

**Comment by yihong0618** [comment]
@RenZMin 
You have one more field “question”

**Comment by YinDongFang** [comment]
default leetcode.cn.js path: C:\Users\[your user name]\.vscode\extensions\shengchen.vscode-leetcode-0.15.7\node_modules\vsc-leetcode-cli\lib\plugins\leetcode.cn.js
```javascript
'use strict'
var request = require('request');

var config = require('../config');
var h = require('../helper');
var log = require('../log');
var Plugin = require('../plugin');
var session = require('../session');

//
// [Usage]
//
// https://github.com/skygragon/leetcode-cli-plugins/blob/master/docs/leetcode.cn.md
//
var plugin = new Plugin(15, 'leetcode.cn', '2018.11.25',
    'Plugin to talk with leetcode-cn APIs.');

plugin.init = function() {
  config.app = 'leetcode.cn';
  config.sys.urls.base            = 'https://leetcode-cn.com';
  config.sys.urls.login           = 'https://leetcode-cn.com/accounts/login/';
  config.sys.urls.problems        = 'https://leetcode-cn.com/api/problems/$category/';
  config.sys.urls.problem         = 'https://leetcode-cn.com/problems/$slug/description/';
  config.sys.urls.graphql         = 'https://leetcode-cn.com/graphql';
  config.sys.urls.problem_detail  = 'https://leetcode-cn.com/graphql';
  config.sys.urls.test            = 'https://leetcode-cn.com/problems/$slug/interpret_solution/';
  config.sys.urls.session         = 'https://leetcode-cn.com/session/';
  config.sys.urls.submit          = 'https://leetcode-cn.com/problems/$slug/submit/';
  config.sys.urls.submissions     = 'https://leetcode-cn.com/api/submissions/$slug';
  config.sys.urls.submission      = 'https://leetcode-cn.com/submissions/detail/$id/';
  config.sys.urls.verify          = 'https://leetcode-cn.com/submissions/detail/$id/check/';
  config.sys.urls.favorites       = 'https://leetcode-cn.com/list/api/questions';
  config.sys.urls.favorite_delete = 'https://leetcode-cn.com/list/api/questions/$hash/$id';
};

// FIXME: refactor those
// update options with user credentials
function signOpts(opts, user) {
  opts.headers.Cookie = 'LEETCODE_SESSION=' + user.sessionId +
                        ';csrftoken=' + user.sessionCSRF + ';';
  opts.headers['X-CSRFToken'] = user.sessionCSRF;
  opts.headers['X-Requested-With'] = 'XMLHttpRequest';
}

function makeOpts(url) {
  const opts = {};
  opts.url = url;
  opts.headers = {};

  if (session.isLogin())
    signOpts(opts, session.getUser());
  return opts;
}

function checkError(e, resp, expectedStatus) {
  if (!e && resp && resp.statusCode !== expectedStatus) {
    const code = resp.statusCode;
    log.debug('http error: ' + code);

    if (code === 403 || code === 401) {
      e = session.errors.EXPIRED;
    } else {
      e = {msg: 'http error', statusCode: code};
    }
  }
  return e;
}

plugin.getProblems = function(cb) {
  plugin.next.getProblems(function(e, problems) {
    if (e) return cb(e);

    plugin.getProblemsTitle(function(e, titles) {
      if (e) return cb(e);

      problems.forEach(function(problem) {
        const title = titles[problem.id];
        if (title)
          problem.name = title;
      });

      return cb(null, problems);
    });
  });
};

plugin.getProblemsTitle = function(cb) {
  log.debug('running leetcode.cn.getProblemNames');

  const opts = makeOpts(config.sys.urls.graphql);
  opts.headers.Origin = config.sys.urls.base;
  opts.headers.Referer = 'https://leetcode-cn.com/api/problems/algorithms/';

  opts.json = true;
  opts.body = {
    query: [
      'query getQuestionTranslation($lang: String) {',
      '  translations: allAppliedQuestionTranslations(lang: $lang) {',
      '    title',
      '    questionId',
      '  }',
      '}',
      ''
    ].join('\n'),
    variables:     {},
    operationName: 'getQuestionTranslation'
  };

  const spin = h.spin('Downloading questions titles');
  request.post(opts, function(e, resp, body) {
    spin.stop();
    e = checkError(e, resp, 200);
    if (e) return cb(e);

    const titles = [];
    body.data.translations.forEach(function(x) {
      titles[x.questionId] = x.title;
    });

    return cb(null, titles);
  });
};

module.exports = plugin;
```

**Comment by hongguang-alt** [comment]
I just `npm i leetcode-cli -g` and it work

**Comment by Daisybiubiubiu** [comment]
same Error 400 issue.. the updated version already fixed the file leetcode.cn.js, but I still got this error message.

**Comment by jackielics** [comment]
> I just `npm i leetcode-cli -g` and it work

I'll give it a try.
