### ISSUE TITLE
登录不上

### ISSUE THREAD

**Issue by sunznx** [jdneo/vscode-leetcode#49]
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2844 [shengchen.vscode-leetcode]This socket has been ended by the other party

/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2844 Error: This socket has been ended by the other party
	at Socket.writeAfterFIN [as write] (net.js:305:12)

**Comment by jdneo** [comment]
The plugin is using leetcode-cli as the back-end. If you cannot login through the plugin, could you please try login with leetcode-cli directly? The steps are:

1. Install leetcode cli: `npm install -g leetcode-cli`
2. `leetcode user -l`

**Comment by sunznx** [comment]
我用 leetcode-cli 来操作是可以的，感觉是 vscode 的 bug

**Comment by sunznx** [comment]
网络问题 - -
