### ISSUE TITLE
能够登陆成功，但是题目列表为空

### ISSUE THREAD

**Issue by jiujiujiujiujiuaia** [jdneo/vscode-leetcode#491]
打印日志如下：
![image](https://user-images.githubusercontent.com/27950614/70385224-70361400-19c7-11ea-84f9-bd501040c525.png)

登陆的是中国站点，账号也登陆成功了。
node环境是v8.16.2
插件是最新版本
机器环境是ubuntu16.04

**Comment by WeiYongqiang55** [comment]
+1

**Comment by WeiYongqiang55** [comment]
我重新安装leetcode插件之后好了

**Comment by jdneo** [comment]
Should be fixed in 0.15.8

**Comment by jiujiujiujiujiuaia** [comment]
thanks
