### ISSUE TITLE
hot-100 list support

### ISSUE THREAD

**Issue by Gahon1995** [jdneo/vscode-leetcode#492]
## 🚀 Feature Proposal
Add a feature to display top100 or popular topics

## Motivation
I want to solve the problem according to the top100 of leetcode, but there is no list that allows me to solve the problem according to the order. I can only look at the problem in the webpage first, and then search in vscode.

**Comment by jdneo** [comment]
The same as: #356?

**Comment by Gahon1995** [comment]
> The same as: #356?

yes,  but when I filter questions based on 'hot-100', the number of questions displayed is 0

**Comment by jdneo** [comment]
It's because we do not have the meta data like this for each question.

Track in #356
