### ISSUE TITLE
Support leetcode-cn

### ISSUE THREAD

**Issue by Xeonacid** [jdneo/vscode-leetcode#50]
[LeetCode 中国](https://leetcode-cn.com/) is the Chinese version of LeetCode. It provides a more comfortable experience for Chinese users, I think.

However, data of the universal version and the Chinese version of LeetCode is not shared. If we want, we have to sync them manually. So can we choose which version to use? 😃 

Thanks!

BTW, I have learned that this extension is based on the [leetcode-cli](https://github.com/skygragon/leetcode-cli) project. Maybe I had better open an issue there...

**Comment by Xeonacid** [comment]
duplicate, sorry for annoying

**Comment by jdneo** [comment]
@Xeonacid I've received a lot of feedbacks about the `LeetCode China`. I think we can open an issue at the `leetcode-cli` and vote for it. Or even we can contribute for it.

Anyway, open an issue first is a good start I think.

**Comment by Xeonacid** [comment]
@jdneo I have found something below

https://github.com/skygragon/leetcode-cli/issues/93 

https://github.com/skygragon/leetcode-cli-plugins/blob/master/plugins/leetcode.cn.js

I think these will be helpful...

**Comment by jdneo** [comment]
@Xeonacid Cool. Let me take a look.

**Comment by jdneo** [comment]
@zouyonghao Yes, I'm planning to add that plugin into the extension too. Will support leetcode.cn in next release.

**Comment by jdneo** [comment]
@Xeonacid @zouyonghao Can you submit solution to leetcode-cn using leetcode-cli? From my side I'm always getting `[ERROR] session expired, please login again [-1]`.

**Comment by zouyonghao** [comment]
@jdneo It seems there is a bug in leetcode.cn plugin, I have submit a pull request here
https://github.com/skygragon/leetcode-cli-plugins/pull/19/files

**Comment by jdneo** [comment]
@zouyonghao Cool. Let's have some discussion there.

**Comment by zouyonghao** [comment]
@jdneo That's cool, appreciate your working.

**Comment by jdneo** [comment]
@all

LeetCode for VS Code 0.8.0 has been published in marketplace. Please have a try.

**Comment by Xeonacid** [comment]
@jdneo Thanks! Good job! 👍 
What about show Chinese problem name at the Problem Set when using leetcode-cn?

**Comment by jdneo** [comment]
Haha, that could be a useful feature. Let’s tracking on that.
