### ISSUE TITLE
How to solve Undefined identifier when us cpp

### ISSUE THREAD

**Issue by SedationH** [jdneo/vscode-leetcode#506]
when I us cpp to solve problems, it always appear Undefined identifier "ListNode" or "string",Although I can use it normally,i still want to know how to solve it.

![image](https://user-images.githubusercontent.com/56129212/74117477-be97a700-4bf2-11ea-88b3-4f6fe65e1701.png)
🆘 🆘 🆘 😭

**Comment by jdneo** [comment]
@SedationH These errors are reported by the C++ extension (which you may have installed it into your own VS Code).

A quick workaround could be: `disable the C++ extension for your LeetCode's workspace`.

**Comment by SedationH** [comment]
@jdneo Thank you 
![image](https://user-images.githubusercontent.com/56129212/74119439-5cdb3b00-4bfa-11ea-90e3-8e5147294ea0.png)
