### ISSUE TITLE
unexpected syntax errors

### ISSUE THREAD

**Issue by zunlihu** [jdneo/vscode-leetcode#51]
When I open a problem in C++, it cannot identify vector, unordered_map...
In this way, I have to include all all I need in this program，e.g.  #include <vector>
Although it can succeed to submit to leetcode, it is a little troublesome...
![image](https://user-images.githubusercontent.com/21325921/43352486-f272563a-9256-11e8-9f15-7e349633694a.png)

**Comment by jdneo** [comment]
So you also installed c++ extension, right?
