### ISSUE TITLE
Add New Problems List

### ISSUE THREAD

**Issue by haozibi** [jdneo/vscode-leetcode#512]
## 🚀 Feature Proposal

Thanks for your extension, I found that leetcode-cn has added a new list of problems( [剑指 Offer（第 2 版）](https://leetcode-cn.com/problemset/lcof/) / [Cracking the Coding Interview Book](https://leetcode-cn.com/problemset/lcci/))

hope you can add these problems

**Comment by jdneo** [comment]
Dup with #200
