### ISSUE TITLE
logined with a premium account, but cannot show locked problem

### ISSUE THREAD

**Issue by ijpq** [jdneo/vscode-leetcode#513]
## 🐛 Bug Report

logined with a premium account, but cannot show locked problem
## Expected behavior

show locked problem

## Extension Output

Error: Command "node "/Users/ketang/.vscode/extensions/shengchen.vscode-leetcode-0.16.0/node_modules/vsc-leetcode-cli/bin/leetcode",show,426,-x" failed with exit code "0". Please open the output channel for details.

## Your Environment

- *os*: Mac 10.15
- *extension settings*: showlocked : true
- *nodejs version*:v10.15.3
- *vscode version*:1.40.2
- *extension version*:0.16.0

**Comment by jdneo** [comment]
@ijpq Have set the `leetcode.showLocked` to `true`?

**Comment by ijpq** [comment]
have set

发自我的iPhone

在 2020年2月20日，19:09，Sheng Chen <notifications@github.com> 写道：

﻿

@ijpq<https://github.com/ijpq> Have set the leetcode.showLocked to true?

**Comment by ijpq** [comment]
可能的原因是使用插件一段时间后，才充值了会员

**Comment by jdneo** [comment]
@ijpq Please provide more information to help diagnostic, like the output in the output channel.

**Comment by ijpq** [comment]
> @ijpq Please provide more information to help diagnostic, like the output in the output channel.

Error: Command "node "/Users/ketang/.vscode/extensions/shengchen.vscode-leetcode-0.16.0/node_modules/vsc-leetcode-cli/bin/leetcode",show,694,-cx,-l,python3" failed with exit code "0". Please open the output channel for details.

**Comment by jdneo** [comment]
Are you using LeetCode CN endpoint?

**Comment by ijpq** [comment]
> Are you using LeetCode CN endpoint?

yes

**Comment by jdneo** [comment]
I see. It's duplicated with #409.
