### ISSUE TITLE
VS code load extension error

### ISSUE THREAD

**Issue by haotingliu1990** [jdneo/vscode-leetcode#515]
## To Reproduce

Steps to reproduce the behavior.

Run the extension on vs code

## Extension Output

Paste here the LeetCode extension log from output channel.

v12.14.1
undefined:1

SyntaxError: Unexpected token 
undefined:1

SyntaxError: Unexpected token 
Error: Command "node "c:\Users\Haoting Liu\.vscode\extensions\shengchen.vscode-leetcode-0.16.0\node_modules\vsc-leetcode-cli\bin\leetcode",plugin,-i,company" failed with exit code "1".

Guidance: Press `Ctrl+Shift+U`, and toggle the channel to `LeetCode`.

## Your Environment

- *os*: Windows insider version 19564.100
- *extension settings*: default settings
- *nodejs version*: 6.13.4
- *vscode version*: 1.42.1
- *extension version*: 0.16.0

**Comment by jdneo** [comment]
Will it help if you remove the folder `$HOME/.lc/`?

**Comment by haotingliu1990** [comment]
> Will it help if you remove the folder `$HOME/.lc/`?

Yes, this works. Thanks.
