### ISSUE TITLE
leetcode-cn account cannot find problem of the book: Coding Interviews

### ISSUE THREAD

**Issue by cparadox** [jdneo/vscode-leetcode#526]
Before you submit an question we recommend you to check out the [DOCUMENT](https://github.com/jdneo/vscode-leetcode/blob/master/README.md) first.

You can also find more information in:
- [TROUBLESHOOTING](https://github.com/jdneo/vscode-leetcode/wiki/Troubleshooting)
- [FAQ](https://github.com/jdneo/vscode-leetcode/wiki/FAQ)

## 💬 Questions and Help

It's a so nice project! But it seems that the leetcode-cn account can only find the problem of algorithms. In the website, I can find other problem like this: 
![image](https://user-images.githubusercontent.com/38486041/75955124-31ddc180-5ef0-11ea-8745-15ec350d72d6.png)
It's so great if you can add these problem!

**Comment by jdneo** [comment]
Dup with #356
