### ISSUE TITLE
how can i sign in leetcode? 

### ISSUE THREAD

**Issue by yangjax** [jdneo/vscode-leetcode#53]
the user name and passwd is ?

**Comment by jdneo** [comment]
@yangjax It's just the same as your `https://leetcode.com` account

If you are a user of `https://leetcode-cn.com/`. Currently the extension not supports it yet. But we will add this support in the next release.

**Comment by jdneo** [comment]
Hi @yangjax. Please let me know if you have problems to sign in to LeetCode in the extension.

**Comment by jdneo** [comment]
Closing since no more reply for a long time.
