### ISSUE TITLE
关于调试

### ISSUE THREAD

**Issue by garyliu0816** [jdneo/vscode-leetcode#530]
## 🚀 Feature Proposal

希望增加一个代码调试的功能，如支持junit这种。

## Motivation

有时候测试用例不能通过，寻找错误原因比较困难，特别是边界条件这种。

**Comment by jdneo** [comment]
Hi @garyliu0816 

Supporting debugging the program is so far not in the roadmap, for the follow reasons:
- Almost impossible to provide a general debug framework for all languages
- Too much uncertainties, any of the dependent language extension changes its API, we breaks.

So I suggest if anyone has the interest to support debugging, he can just write his own extension to enable this scenario.

BTW, if you want to know how to debug in Java, hope this article could help you: https://zhuanlan.zhihu.com/p/62521108

**Comment by wangtao0101** [comment]
Insert an AD: [Debug LeetCode](https://marketplace.visualstudio.com/items?itemName=wangtao0101.debug-leetcode)

Currently the extension support js and python, and in few weeks i will support c and c++, next java....

插一个广告[Debug LeetCode](https://marketplace.visualstudio.com/items?
目前支持js和python，几周内会支持c and c++，然后java。。。

**Comment by chumingqian** [comment]
> Insert an AD: [Debug LeetCode](https://marketplace.visualstudio.com/items?itemName=wangtao0101.debug-leetcode)
> 
> Currently the extension support js and python, and in few weeks i will support c and c++, next java....

You  really  done it,  Great  :)
