### ISSUE TITLE
我在 leetCode 中文站点上提交了答案，而 插件中并没有显示绿色的勾

### ISSUE THREAD

**Issue by 2234839** [jdneo/vscode-leetcode#532]
## 🐛 Bug Report
我在 leetCode 中文站点上提交了答案，而 插件中并没有显示绿色的勾

## To Reproduce

1. leetCode 中文站点上提交了答案通过
2. 插件内点刷新也没有显示勾

## Expected behavior

我希望插件能同步站点的提交结果

## Your Environment

- *os*: win10
- *extension settings*:
- *nodejs version*: 13
- *vscode version*: 1.44
- *extension version*: 0.16.1

**Comment by taoweicn** [comment]
和 #367 重复了吧

**Comment by jdneo** [comment]
Thanks @taoweicn. Yes it's dup with #367 

Let's track the issue in one place.
