### ISSUE TITLE
need unlock those locking subject for the login LeetCode member

### ISSUE THREAD

**Issue by LinDaFeiiiiii** [jdneo/vscode-leetcode#533]
## 🚀 Feature Proposal

hope can unlock those locking subject for the login LeetCode member

**Comment by jdneo** [comment]
Do you mean that you have bought premium account but cannot answer those locked problem?

**Comment by LinDaFeiiiiii** [comment]
yes

**Comment by jdneo** [comment]
Thanks, it's dup with #409
