### ISSUE TITLE
Will the session in extension be merged to web account?

### ISSUE THREAD

**Issue by Hangzhi** [jdneo/vscode-leetcode#534]
I noticed that the session fetched the session data from the web account, but I cannot find a method to merge the session to web. Could you please help me?

**Comment by jdneo** [comment]
@Hangzhi I'm not quite get your idea. The sessions should be shared between web and extension. What do you mean by `merge the session to web`?

**Comment by Hangzhi** [comment]
> @Hangzhi I'm not quite get your idea. The sessions should be shared between web and extension. What do you mean by `merge the session to web`

**Comment by Hangzhi** [comment]
Thank you for your reply. I found the record in vscode wasn't updated on the website but was updated later on. This inconsistency should be due to network latency.
