### ISSUE TITLE
leetcode plugin  version: 0.16.2.  [ERROR] failed to load locked problem

### ISSUE THREAD

**Issue by JianmingS** [jdneo/vscode-leetcode#542]
## 🐛 Bug Report

[ERROR] failed to load locked problem!

## To Reproduce

1. signed in a premium account (leetcode-cn.com).
2. when search problem 425, prompt “[ERROR] failed to load locked problem!”

## Your Environment

- *os*: mac os catalina 10.15.4
- *extension settings*: 
- *nodejs version*: 
- *vscode version*: 1.44.2
- *extension version*: 0.16.2

**Comment by JianmingS** [comment]
leetcode plugin version: 0.16.2
I have signed in a premium account.
when search problem 425, prompt me “[ERROR] failed to load locked problem!”

**Comment by jdneo** [comment]
Dup with #409
