### ISSUE TITLE
Leetcode extension does not upload solution to leetcode account

### ISSUE THREAD

**Issue by justinzw** [jdneo/vscode-leetcode#543]
This probably is a known issue, but when I submit my solution it does not upload it to my leetcode account.

**Comment by jdneo** [comment]
@justinzw I cannot repro this, please share a detailed repro steps of this issue

**Comment by justinzw** [comment]
Thanks for your reply. When I submit the code using the extension in visual studio code (even when it succeeds) the solution does not get uploaded to leetcode.com

When I go to leetcode.com to the same problem I don't see my solution. Also when I submit the code on leetcode.com I don't see it in VSCode even when I log in. 

I think they aren't syncing.

**Comment by jdneo** [comment]
Still cannot repro.

![image](https://user-images.githubusercontent.com/6193897/79717205-7fc95000-830b-11ea-8da1-8e4f8843e8ae.png)

This is what I just tried for the problem `two-sum` in `leetcode.com`

> When I go to leetcode.com to the same problem I don't see my solution.

Suppose the `solution` you mean is the submission, please make sure the account you are using is the same

> Also when I submit the code on leetcode.com I don't see it in VSCode even when I log in.

The extension will show the pass/fail result. So far there is no such feature to show the submit history in the extension

**Comment by justinzw** [comment]
Thank you. I guess I wasn't looking right and now I see that it works.

Quick question: When I submit code through the VScode extension it doesn't "save" it in the leetcode website. When I open leetcode.com the solution is still the default empty one.

Is that the expected result?

**Comment by jdneo** [comment]
@justinzw You should see the solution in the submission history. You cannot see it in the editing area since it is cached in the browser I guess. Solving problem in VS Code won't affect the browser cache.
