### ISSUE TITLE
Does it support auto login

### ISSUE THREAD

**Issue by LikeSundayLikeRain** [jdneo/vscode-leetcode#56]
I know it's available in leetcode-cli, does it available in this plugin as well ?

**Comment by jdneo** [comment]
@LikeSundayLikeRain Yes as long as the session is still valid. The experience should be the same as leetcode-cli.

**Comment by jdneo** [comment]
@LikeSundayLikeRain 

I'm closing this issue for now. Please feel free to reopen it or create a new issue if you have further questions.

Thanks.
