### ISSUE TITLE
all problems occur twice in list

### ISSUE THREAD

**Issue by Eskibear** [jdneo/vscode-leetcode#6]
![image](https://user-images.githubusercontent.com/2351748/36522085-5efb9f70-17d5-11e8-8d7b-6f41db46160d.png)

e.g. in above image, `Hard` = [4, 10, 23, ..., 782, 786, **4, 10, 23, ..., 782, 786**]
Tried signing out and in again, it's the same result.

**Comment by jdneo** [comment]
Great finding! This issue should be fixed in this commit: https://github.com/jdneo/vscode-leetcode/commit/8024c3db00a15c59d7567ab31c685d57cf7aa3fb

**Comment by shuiqingliu** [comment]
This issue appearing again When I click the refresh button on the top. 

System info:
* vs-code version is 1.31.1
* leetcode version is 0.10.2
* I'm in anonymous session 
* my os is  Mac OS.

please contact to me if you need other information.Thanks.
