### ISSUE TITLE
Support third-party login, for example: Login through GitHub

### ISSUE THREAD

**Issue by cutpictureboy** [jdneo/vscode-leetcode#62]
如题

**Comment by jdneo** [comment]
目前还不支持

**Comment by niudiewei** [comment]
前来请求添加支持。。

**Comment by glazec** [comment]
可以重置第三方登录的邮箱的密码来登陆

**Comment by jjeejj** [comment]
我也来问一下，现在添加支持了吗？？

**Comment by YoungForest** [comment]
> 可以重置第三方登录的邮箱的密码来登陆

亲测有效。我一直是通过Github第三方登陆网页版来刷题的。通过修改密码，可以拥有一个local的密码。使用用户名和密码直接登陆LeetCode。也就可以登陆插件了。
如下图所示：
![image](https://user-images.githubusercontent.com/13612111/60325166-380ebc00-99b9-11e9-98cc-8f01e2ef9c7f.png)
![image](https://user-images.githubusercontent.com/13612111/60325194-48269b80-99b9-11e9-9541-693077e766bc.png)

**Comment by jdneo** [comment]
@all

FYI @yihong0618 is working on this feature, see: #496

**Comment by jdneo** [comment]
Finally arrive in 0.16.0
