### ISSUE TITLE
Even though I have logged in, it still returns an error.

### ISSUE THREAD

**Issue by nomoreplay** [jdneo/vscode-leetcode#64]
[ERROR] session expired, please login again [-1]

not able to test or commit.

**Comment by jdneo** [comment]
Are you use LeetCode or LeetCode-cn?

**Comment by nomoreplay** [comment]
I have account in both these two sites. They share the same username.

**Comment by nomoreplay** [comment]
I’ve re-login many times, when I test or summit, it returns this error.

**Comment by jdneo** [comment]
OK.

Could you please do the following to help troubleshooting:
1. Will this issue still occur if you trigger the clean cache command? Enter `F1` and then find `leetcode.deleteCache`
2. Will this issue still occur if you use the [leetcode-cli](https://skygragon.github.io/leetcode-cli/) directly?

**Comment by nomoreplay** [comment]
Problem solved. I toggle on the activity bar in vscode and login either leetcode or leetcode-cn. And I can commit right now.Thanks.
