### ISSUE TITLE
可以登录，但是不能展示题目

### ISSUE THREAD

**Issue by SkyLin0909** [jdneo/vscode-leetcode#68]
[ERROR] Not supported language "javascript" [0]
[WARN] Supported languages:  mssql   mysql   oraclesql

**Comment by jie-feng** [comment]
I have the same issue for python3. How did you solve this issue? Thanks

**Comment by toutiay** [comment]
请问你这个是怎么解决的？

**Comment by jdneo** [comment]
@toutiay Please make sure your are using a valid language.

**Comment by toutiay** [comment]
@jdneo 明白了，vscode我设置的默认语言是JavaScript，但是有个题目是不支持JavaScript这种语言解决的。
建议这种情况处理一下，刚使用插件出这个错有点懵。

**Comment by toutiay** [comment]
@jdneo 非常感谢，这个插件超好的

**Comment by jdneo** [comment]
@toutiay You are welcome. Happy Coding!
