### ISSUE TITLE
node已经在路径了，但是安装不正确

### ISSUE THREAD

**Issue by zssasa** [jdneo/vscode-leetcode#71]
windows7环境
vscode: 1.28.0
![image](https://user-images.githubusercontent.com/11346619/46927995-ed3b5700-d06a-11e8-9c52-2dea7a2c01c6.png)
提示 LeetCode extension needs Node.js installed in environment path

**Comment by jdneo** [comment]
What if you close the VS Code and start it again?

**Comment by zssasa** [comment]
> What if you close the VS Code and start it again?

It's not working.

**Comment by jdneo** [comment]
@zssasa Is there any output in the output panel in VS Code?

**Comment by zssasa** [comment]
> @zssasa Is there any output in the output panel in VS Code?

重启电脑ok了 - -

**Comment by kissjanna** [comment]
I fixed it by uninstall my vscode and reinstall it. (macos)
