### ISSUE TITLE
failed to load locked problem! [0]

### ISSUE THREAD

**Issue by belovedred1892** [jdneo/vscode-leetcode#73]
failed to load locked problem! [0]
when even I have signed in a premium account 
was searching/click question: 
Two Sum III - Data structure design

**Comment by jdneo** [comment]
@belovedred1892 Will it help if you delete the cache? You can find the command in the command palette.

**Comment by belovedred1892** [comment]
This problem still exist after delete cache.............

**Comment by jdneo** [comment]
@belovedred1892 

Found a root cause issue here: https://github.com/skygragon/leetcode-cli/issues/91

Looks like I need to update the cli version to resolve the problem.

**Comment by belovedred1892** [comment]
Thanks for the investigation!

**Comment by jdneo** [comment]
On vacation these days. Will prepare the new release when I get back. Thanks

**Comment by belovedred1892** [comment]
Enjoy your vacation! Wait for your back

**Comment by ismailhkose** [comment]
I also have a similar problem.
settings.json have the following definition, but it still doesn't work.
`"leetcode.showLocked": true`

Thanks @jdneo

**Comment by jdneo** [comment]
Hi all,

I'm back from the vacation and will work on a new release this week. Sorry for the late reply...

**Comment by jdneo** [comment]
I tested the leetcode-cli@2.6.0

But I cannot submit answer on Windows, though I can achieve that on Mac.

See the original issue here: https://github.com/skygragon/leetcode-cli/issues/134

Does anyone has the same issue as mine?

**Comment by belovedred1892** [comment]
I haven't tried submitted answer directly from VS code

**Comment by jdneo** [comment]
Can it work using cli directly with version 2.6.0?

**Comment by belovedred1892** [comment]
Try a previous version in CLI? 2.5.4

**Comment by belovedred1892** [comment]
Woooow~~  This problem is fixed now, Thanks so much for the fabulous work

**Comment by chungchi300** [comment]
The problem still exists on 13.1 in Centos VSCode 1.32.2

**Comment by http600** [comment]
still there v0.17.0

**Comment by labuladong** [comment]
Try [this extension](https://mp.weixin.qq.com/s/z4mqiiJV9pZ3t6SIPa2kTA):
![image](https://user-images.githubusercontent.com/37220920/197193186-44284a07-cc53-473c-a179-40e2ea677882.png)
