### ISSUE TITLE
Power operator displays in a wrong way

### ISSUE THREAD

**Issue by labulaka521** [jdneo/vscode-leetcode#74]
![](https://ws1.sinaimg.cn/large/005Oh4GZly1fx1y99qxiij31a004sq40.jpg)
![](https://ws1.sinaimg.cn/large/005Oh4GZly1fx1y99r9v7j30s405u0tj.jpg)
pow will change
i think you could instend `^`

**Comment by jdneo** [comment]
This might be caused by the leetcode-cli, the text is wrongly parsed.

**Comment by labulaka521** [comment]
oh..thanks you, but fortunately, it has little effect on me

**Comment by jdneo** [comment]
Trying to send a [PR](https://github.com/skygragon/leetcode-cli/pull/144) to fix this...

**Comment by labulaka521** [comment]
thanks you very much

**Comment by jdneo** [comment]
PR gets merged, waiting for the new CLI get released...
