### ISSUE TITLE
Can not successfully login.

### ISSUE THREAD

**Issue by LightingX** [jdneo/vscode-leetcode#78]
I have input the username "LightingX" and the correct password, but it doesn't work, why?
the feedback is at list.

> v9.8.0
> [ERROR] You are not login yet? [0]
> login: pass: [ERROR] invalid password? [0]

**Comment by jdneo** [comment]
@LightingX Are you using the right endpoint? We have two endpoint now:
- LeetCode
- LeetCode.cn

**Comment by LightingX** [comment]
So, how could I switch the endpoint? the command "Switch endpoint" doesn't exist.

**Comment by jdneo** [comment]
Could you see any logs in the output channel?

**Comment by jdneo** [comment]
Close because inactive for a long time.

**Comment by githubuserhk** [comment]
Is your problem solved? I also encountered this problem, everytime i input the right password,it shows message like "Failed to sign in. Please open the output channel for details", hopefully you can help me! thanks a lot.
