### ISSUE TITLE
sign in 时报错,不能登陆

### ISSUE THREAD

**Issue by Dye8** [jdneo/vscode-leetcode#82]
``` 
C:\Users\xxx\.vscode\extensions\shengchen.vscode-leetcode-0.8.1\node_modules\ora\index.js:62
		const {frames} = this.spinner;
		      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:404:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\xxx\.vscode\extensions\shengchen.vscode-leetcode-0.8.1\node_modules\leetcode-cli\lib\helper.js:3:11)
    at Module._compile (module.js:397:26)
    at Object.Module._extensions..js (module.js:404:10)
```

**Comment by Dye8** [comment]
signin 能正常弹出输入用户名的对话框,但是回车后就没反应了.
上面的日志是在signin的时候输出的,不是在回车的时候.

**Comment by jdneo** [comment]
删除`$HOME/.lc`能解决问题吗？

**Comment by Dye8** [comment]
删除 `$home/.lc` 好像不管用
我升级了一下node.js 好了

**Comment by Dye8** [comment]
但是现在有个新问题 
我用户名和密码都是正确的,不知道为什么登陆不上
```
v10.15.0 
[ERROR] You are not login yet?
 Active  Name               Version         Desc
----------------------------------------------------------------------------------------------------
   √     cache              default         Plugin to provide local cache.
   √     retry              default         Plugin to retry last failed request if autologin.enable is on.
   ×     leetcode.cn        2018.11.25      Plugin to talk with leetcode-cn APIs.
   √     leetcode           default         Plugin to talk with leetcode APIs.
login: login: pass: - Signing in leetcode.com
[ERROR] invalid password?
```

**Comment by jdneo** [comment]
OK  可能你之前的node版本过低 不支持`{}`语法。

登陆不上的问题，你看一下你用的是不是leetcode.cn的账户，这个插件默认是用的leetcode.com。这两个用户系统不通用。

如果确实是这样的话，可以`switch endpoint` 切换到cn

**Comment by Dye8** [comment]
好了 完美解决 感谢
升级前`node.js`版本是`v5.4.1`  (捂脸
登陆不上的确是因为`switch endpoint` 以为那个红点是中国

**Comment by jdneo** [comment]
@Dye8 这个图标是没设计好，后面要改改

**Comment by kaiyulee** [comment]
@jdneo 国内的 endpoint 是 leetcode.cn 还是 leetcode-cn.com?  我现在登录一直报 500.

switch endpoint 也切换不了. output 信息:

```
 Active  Name               Version         Desc
----------------------------------------------------------------------------------------------------
   ✘     solution.discuss   2019.02.03      Plugin to fetch most voted solution in discussions.
   ✘     company            2017.12.18      Plugin to query by company for free user.
   ✔     cache              default         Plugin to provide local cache.
   ✔     retry              default         Plugin to retry last failed request if autologin.enable is on.
   ✔     leetcode.cn        2018.11.25      Plugin to talk with leetcode-cn APIs.
   ✔     leetcode           default         Plugin to talk with leetcode APIs.
[ERROR] You are not login yet?
login: pass: login: pass: - Signing in leetcode.com
[ERROR] http error [code=500]
```

**Comment by lryong** [comment]
> @jdneo 国内的 endpoint 是 leetcode.cn 还是 leetcode-cn.com? 我现在登录一直报 500.
> 
> switch endpoint 也切换不了. output 信息:
> 
> ```
>  Active  Name               Version         Desc
> ----------------------------------------------------------------------------------------------------
>    ✘     solution.discuss   2019.02.03      Plugin to fetch most voted solution in discussions.
>    ✘     company            2017.12.18      Plugin to query by company for free user.
>    ✔     cache              default         Plugin to provide local cache.
>    ✔     retry              default         Plugin to retry last failed request if autologin.enable is on.
>    ✔     leetcode.cn        2018.11.25      Plugin to talk with leetcode-cn APIs.
>    ✔     leetcode           default         Plugin to talk with leetcode APIs.
> [ERROR] You are not login yet?
> login: pass: login: pass: - Signing in leetcode.com
> [ERROR] http error [code=500]
> ```
> 
> 当前 `node -v` node 12.3.1

也遇到相同的问题， 500报错应该是leecode-cn.com服务端访问出错了
