### ISSUE TITLE
Failed to get submission beat ratio 

### ISSUE THREAD

**Issue by maywzh** [jdneo/vscode-leetcode#88]
After submit my solution to leetcode, I can get the score without beat ratio.
Got the message: " [WARN] Failed to get submission beat ratio. "

**Comment by jdneo** [comment]
Will investigate...

**Comment by taoweicn** [comment]
I got the same issue several days ago, it was caused by leetcode's site upgrade and is normal now.

**Comment by jdneo** [comment]
@taoweicn Thank you for the information.

@maywzh Could you please confirm that this issue still occurs on your side？

**Comment by maywzh** [comment]
@jdneo thanks, It's normal now

**Comment by wgqimut** [comment]
Actually I have the same issue again. @jdneo

**Comment by taoweicn** [comment]
See #105 @wgqimut

**Comment by guguji5** [comment]
me too

**Comment by elliottzhou** [comment]
me too
