### ISSUE TITLE
In version 0.18.2, there is an issue where local vscode.exe cannot be opened after redirecting to the authorized login page on the web.

### ISSUE THREAD

**Issue by GKNEETIEMAY** [jdneo/vscode-leetcode#951]
The problem is as indicated by the title, and the re-login succeeded after rolling back to the old version

**Comment by Candysad** [comment]
I got the same issue.

The way to login is changing back to [0.18.1](https://marketplace.visualstudio.com/items?itemName=LeetCode.vscode-leetcode) and then login with cookie.
